import type { Metadata } from "next";
import s from "./rtb.module.css";
const demand="https://form.jotform.com/262738772653065";
const business="https://form.jotform.com/262743093043050";
export const metadata:Metadata={title:{absolute:"Riot Training Base｜TRAIN / ASSESS / SELECT / PARTNER"},description:"仙台のRiot Training Base。トレーニング、パフォーマンス評価、RTB SELECT、チーム・法人・ブランド連携まで、身体を動かす現場からつなぎます。",robots:{index:false,follow:false}};
const personal=[
 ["01 / TRAIN","Personal Training","個別","目的、競技、経験に合わせて、基礎筋力からパフォーマンスまで段階的に積み上げます。","相談する","mailto:riot.training.base@gmail.com?subject=RTB"],
 ["02 / ASSESS","Movement / Performance Check","¥3,300〜","医療診断ではなく、基本動作とトレーニング目標を整理するための入口。正式メニューは需要確認後に公開します。","先行案内",demand],
 ["03 / SELECT","RTB SELECT","商品別","実際に使う理由があるものだけ。委託、予約、小ロットを中心に、在庫を積まずに選びます。","SELECTを見る","/rtb-select"],
];
const businessCards=[
 ["01 / TEAM","Team S&C","個別見積","競技チームの目的、年代、頻度に合わせてS&Cを設計。バスケットボールに限定しません。"],
 ["02 / CORPORATE","Corporate Performance","個別見積","企業向けの運動・コンディショニング支援。単発から継続契約まで相談できます。"],
 ["03 / BRAND","Product Test / Pop-up","個別設計","RTBで実際に試し、顧客反応と販売を検証。ポジティブな評価や売上を保証する広告商品ではありません。"],
];
export default function Page(){return <div className={s["rtb-site"]}>
<div className={s["rtb-shell"]}><header className={s["rtb-header"]}><a className={s["rtb-brand"]} href="/rtb"><span className={s["rtb-mark"]}>RTB</span><span><strong>RIOT TRAINING BASE</strong><small>PERFORMANCE / SENDAI</small></span></a><nav className={s["rtb-nav"]}><a href="#services">SERVICES</a><a href="/rtb-select">SELECT</a><a href="#business">BUSINESS</a><a className={s["rba-link"]} href="/ja">RBA / BASKETBALL ↗</a></nav></header>
<section className={s["rtb-hero"]}><div><p className={s["rtb-eyebrow"]}>RIOT TRAINING BASE / SENDAI</p><h1><span>TRAIN.</span><span>ASSESS.</span><span>BUILD.</span></h1><p className={s["rtb-lede"]}>トレーニングを入口に、身体を理解し、必要なものを選び、次のパフォーマンスへつなげる。</p></div><aside className={s["rtb-aside"]}><p>RTBはRBAの物販ページではありません。仙台のトレーニング拠点として、個人・チーム・企業・ブランドにそれぞれ独立した価値を提供します。</p><a className={s["rtb-button"]} href="mailto:riot.training.base@gmail.com?subject=RTB">RTBに相談する</a></aside></section></div>
<div className={s["rtb-band"]}><div className={s["rtb-shell"]}><strong>TRAINING IS THE ENTRY.</strong><span>RBAはバスケットボール育成事業。RTBはトレーニング／パフォーマンス事業。</span></div></div>
<section id="services" className={s["rtb-section"]}><div className={s["rtb-shell"]}><div className={s["rtb-head"]}><div><p className={s["rtb-eyebrow"]}>FOR INDIVIDUALS</p><h2>まず身体を動かす。<br/>必要なものは、その後に。</h2></div><p>商品販売を先に置きません。トレーニングと目的が中心です。Assessment、SELECT、将来のMembershipは、その体験を支えるサービスとして設計します。</p></div><div className={s["rtb-grid"]}>{personal.map(([tag,title,price,body,cta,href])=><article className={s["rtb-card"]} key={tag}><span>{tag}</span><h3>{title}</h3><p>{body}</p><footer><strong>{price}</strong><a href={href} target={href.startsWith("http")?"_blank":undefined} rel="noreferrer">{cta} →</a></footer></article>)}</div></div></section>
<section className={s["rtb-section"]+" "+s["rtb-orange"]}><div className={s["rtb-shell"]}><div className={s["rtb-head"]}><div><p className={s["rtb-eyebrow"]}>RTB SELECT</p><h2>在庫を並べる店ではなく、<br/>選ぶ理由がある売場。</h2></div><p>TRAIN / RECOVER / WEAR。需要を先に確認し、委託・サンプル・予約・小ロットを優先。売れたカテゴリーだけを残し、将来のRTB ORIGINALへつなげます。</p></div><a className={s["rtb-button"]} href="/rtb-select">RTB SELECTを見る →</a></div></section>
<section id="business" className={s["rtb-section"]+" "+s["rtb-dark"]}><div className={s["rtb-shell"]}><div className={s["rtb-head"]}><div><p className={s["rtb-eyebrow"]}>FOR TEAMS / COMPANIES / BRANDS</p><h2>施設そのものを、<br/>実施環境にする。</h2></div><p>チームS&C、法人向け運動支援、商品テスト、POP-UP。RTBの現場を使って実施し、結果を確認できる形で連携します。</p></div><div className={s["rtb-grid"]}>{businessCards.map(([tag,title,price,body])=><article className={s["rtb-card"]} key={tag}><span>{tag}</span><h3>{title}</h3><p>{body}</p><footer><strong>{price}</strong><a href={business} target="_blank" rel="noreferrer">相談する →</a></footer></article>)}</div></div></section>
<section className={s["rtb-section"]+" "+s["rtb-dark"]}><div className={s["rtb-shell"]+" "+s["rtb-rba-bridge"]}><div><p className={s["rtb-eyebrow"]}>BASKETBALL DEVELOPMENT</p><h2 style={{fontSize:"clamp(38px,5vw,68px)",lineHeight:1,letterSpacing:"-.05em",margin:0}}>Basketball belongs to RBA.</h2></div><div className={s["rtb-rba-box"]}><h3>RIOT BASKETBALL ACADEMY</h3><p>育成年代バスケットボール、Development Camp、RBA UNITED、指導者学習、MY HOME COURT、国際交流はRBAへ。RTBとRBAは連携しますが、入口と役割を混同させません。</p><a className={s["rtb-button"]+" "+s.light} href="/ja">RBAへ移動する →</a></div></div></section>
<footer className={s["rtb-footer"]}><div className={s["rtb-shell"]}><div><strong>RIOT TRAINING BASE</strong><p>TRAINING · PERFORMANCE · SELECT<br/>Sendai, Japan</p></div><div><a href="/rtb-select">RTB SELECT</a><a href={business} target="_blank" rel="noreferrer">BUSINESS</a><a href="/ja">RBA</a></div></div></footer>
</div>}