import type { Metadata } from "next";
import { ArrowRight, Camera, MessageCircle } from "lucide-react";
import { InnerPage } from "@/components/inner-page";

export const metadata: Metadata = { title: "Work With RBA", description: "Development services and international collaboration for youth basketball coaches, academies and organisers.", alternates:{canonical:"/work-with-rba"} };

const services = [
  { code: "FIELD", name: "Clinic & Development Camp", for: "Players · teams · organisers", copy: "Age-appropriate, game-based sessions designed around a clear learning problem—not a catalogue of drills.", action: "Request a programme" },
  { code: "COACH", name: "Coach Practice Review", for: "Individual coaches", copy: "A focused review of one practice plan or video, with concrete observations and the next design decision.", action: "Request a quote" },
  { code: "DESIGN", name: "U12 Practice Design", for: "Coaches · programmes", copy: "A purpose-built session structure connecting perception, decision, execution, spacing and load.", action: "Request a quote" },
  { code: "ACADEMY", name: "Academy Development Audit", for: "Academies · club leaders", copy: "A structured review of pathway, practice design, coach alignment and development environment.", action: "Request a quote" },
];

export default function WorkPage() {
  return <InnerPage index="03" kicker="WORK WITH RBA" title={<>Start with the<br />development problem.</>} intro="We work with coaches, academies and organisers who want a clearer youth-development environment—not a borrowed drill package or a one-off appearance." next={{ label: "Enter RBA Radio", href: "/radio" }}>
    <section className="request-banner section-pad"><div><p className="section-index">PRIORITY FOR ORGANISERS</p><h2>Request a clinic<br />or a formal estimate.</h2><p>Share the real conditions first. We will shape the response around your players, venue and development goal.</p></div><a className="button button-light" href="/clinic-request">Open request / estimate form <ArrowRight size={17} /></a></section>
    <section className="services section-pad">{services.map(s => <article key={s.code}><p className="service-code">{s.code}</p><div><p className="note-tag">{s.for}</p><h2>{s.name}</h2><p>{s.copy}</p><a className="text-link" href={`/contact?topic=${s.code.toLowerCase()}`}>{s.action} <ArrowRight size={16} /></a></div></article>)}</section>
    <section className="lab-feature section-pad"><div className="lab-label"><span>30</span><p>DAY<br />PILOT</p></div><div><p className="section-index inverse">RBA ASIA PRACTICE EXCHANGE LAB</p><h2>One shared question.<br />Two practice environments.</h2><p>One overseas academy and one Japan-side environment examine the same youth-development question. Coaches document context, compare observation, redesign practice and retest what changed.</p><div className="lab-phases"><span>BASELINE</span><span>OBSERVE</span><span>COMPARE</span><span>RETEST</span></div><p className="lab-price">Pilot enquiries · scope, timing and price agreed before booking</p><a className="button button-light" href="/contact?topic=asia-lab">Discuss a shared question <ArrowRight size={17} /></a></div></section>
    <section className="fit-section section-pad"><div><p className="section-index">A GOOD FIT</p><h2>We work best when...</h2></div><ul><li>You can name a real development question.</li><li>Your coaches are willing to observe before prescribing.</li><li>Player welfare and safeguarding are non-negotiable.</li><li>You want adaptation, not “the Japanese way.”</li><li>You are open to an honest debrief after delivery.</li></ul></section>
    <section className="partner-call section-pad"><div><p className="section-index inverse">ASIA PARTNER SEARCH</p><h2>Help raise the level of youth development across Asia.</h2><p>RBA is looking for academies, clubs, coach educators, performance specialists, event organisers and aligned brands that want to build repeatable exchange—not a one-off photo opportunity.</p></div><div className="partner-contact-grid"><a href="https://wa.me/818032483703?text=Hello%20RBA%2C%20we%20are%20interested%20in%20an%20Asia%20basketball%20partnership.%20Our%20organisation%20is%3A%20" target="_blank" rel="noreferrer"><MessageCircle size={25}/><span>FASTEST CONTACT</span><strong>WhatsApp RBA</strong></a><a href="https://www.instagram.com/riot.basketball.academy/" target="_blank" rel="noreferrer"><Camera size={25}/><span>SEE THE WORK</span><strong>Instagram</strong></a><a href="https://www.threads.com/@riot.basketball.academy" target="_blank" rel="noreferrer"><MessageCircle size={25}/><span>JOIN THE DIALOGUE</span><strong>Threads</strong></a></div></section>
  </InnerPage>;
}