import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, ArrowUpRight, Check, MapPin } from "lucide-react";
import { SiteFrame } from "@/components/site-frame";
import { eventPayments, formatJPY } from "@/components/payment-data";

const applyUrl="https://form.jotform.com/262591727805061";
export const metadata:Metadata={title:"Kobe Development Camp 2026 | International Player Guide",description:"Join RBA's youth basketball development camp in Tatsuno, Hyogo, Japan, November 20–23, 2026. Open to Grades 5–9 with English, Japanese, Traditional Chinese and Korean support.",alternates:{canonical:"/journal/kobe-development-camp-2026"},openGraph:{title:"Kobe Development Camp 2026",description:"A multi-day basketball development camp in Japan for Grades 5–9. November 20–23, 2026.",type:"article",url:"/journal/kobe-development-camp-2026"}};

const days=[
  {date:"FRI · NOV 20",title:"Night Session",time:"18:00–20:30",focus:"See → decide → move the ball → move yourself → create the next advantage"},
  {date:"SAT · NOV 21",title:"See & Decide",time:"DAY 1",focus:"Perception, decision-making, movement preparation, 1-on-1, 2-on-2, 3-on-3 and reflection"},
  {date:"SUN · NOV 22",title:"Connect & Create",time:"DAY 2",focus:"Finishing, shooting, two-player actions, small-sided games, 3x3, 4x4 and competition"},
  {date:"MON · NOV 23",title:"Adapt & Compete",time:"DAY 3",focus:"Player-led preparation, decision challenges, small-sided games, final competition and awards"},
] as const;

export default function KobeCampArticle(){return <SiteFrame><article className="kobe-article">
  <section className="kobe-hero section-pad"><Link className="back-link" href="/journal">← RBA Journal</Link><div><p className="section-index inverse">INTERNATIONAL PLAYER GUIDE · REGISTRATION OPEN</p><h1>KOBE<br/>DEVELOPMENT<br/>CAMP 2026</h1><p className="kobe-lede">Four days in Japan for players who want to see more, decide better, connect with teammates and adapt under pressure.</p><div className="kobe-actions"><a className="button button-light" href={applyUrl} target="_blank" rel="noreferrer">Apply now <ArrowUpRight size={17}/></a><a className="text-link light-link" href="#programme">View the programme <ArrowRight size={16}/></a></div></div><div className="kobe-facts"><div><strong>20–23</strong><span>NOVEMBER 2026</span></div><div><strong>5–9</strong><span>ELIGIBLE GRADES</span></div><div><strong>4</strong><span>SUPPORTED LANGUAGES</span></div></div></section>
  <section className="kobe-intro section-pad"><p className="section-index">WHY THIS CAMP</p><div><h2>Skills matter.<br/>The game decides when to use them.</h2><p>RBA does not separate technique from the information players must read. The camp moves from perception and individual decisions to two-player connections, small-sided games and competitive situations.</p><p>The objective is not to collect more moves. It is to help players recognise the moment, choose an option, execute with purpose and adjust when the situation changes.</p><div className="kobe-pill-row"><span><Check size={15}/> Perception</span><span><Check size={15}/> Decision-making</span><span><Check size={15}/> Connection</span><span><Check size={15}/> Adaptability</span></div></div></section>
  <section id="programme" className="kobe-programme section-pad"><div className="section-head"><div><p className="section-index inverse">THE PROGRAMME</p><h2>One flow.<br/>Four ways to enter.</h2></div><p>Join the Friday night session, a half day, one full day or a multi-day programme. Times and content may be adjusted during final planning.</p></div><div className="kobe-day-grid">{days.map((d,i)=><article key={d.date}><span>0{i+1} / {d.date}</span><strong>{d.time}</strong><h3>{d.title}</h3><p>{d.focus}</p></article>)}</div></section>
  <section className="kobe-location section-pad"><div><p className="section-index">LOCATION</p><MapPin size={48}/><h2>Tatsuno,<br/>Hyogo, Japan.</h2></div><div className="kobe-location-details"><div><span>TRAINING VENUE</span><strong>Mitsu Gymnasium</strong></div><div><span>ACCOMMODATION</span><strong>Summer House Kamome</strong></div><div><span>PLAYER AGE</span><strong>Grades 5–9</strong></div><div><span>LANGUAGE SUPPORT</span><strong>Japanese · English · Traditional Chinese · Korean</strong></div></div></section>
  <section className="kobe-pricing section-pad"><div className="section-head"><div><p className="section-index">PARTICIPATION OPTIONS</p><h2>Apply first.<br/>Then select your plan.</h2></div><p>Submit the registration form first. Then open the matching secure payment page below and use the same email address.</p></div><div className="kobe-price-list">{eventPayments.kobe.map(option=><a href={`/api/commerce/checkout/${option.id}`} key={option.id}><span>{option.label}</span><strong>{formatJPY(option.amount)} <ArrowUpRight size={18}/></strong></a>)}</div></section>
  <section className="kobe-international section-pad"><p className="section-index inverse">FOR INTERNATIONAL FAMILIES & ACADEMIES</p><div><h2>International players are welcome.</h2><p>RBA can communicate in English, Japanese, Traditional Chinese and Korean around the programme. The application form collects the information needed for participation.</p><p>Before booking travel, families and organisations should complete the application and make sure their own travel, supervision, medical information and insurance arrangements are appropriate.</p><a className="button button-light" href={applyUrl} target="_blank" rel="noreferrer">Open the application form <ArrowUpRight size={17}/></a></div></section>
  <section className="kobe-final section-pad"><p>RIOT BASKETBALL ACADEMY · JAPAN</p><h2>See more.<br/>Decide better.<br/>Play together.</h2><a className="button button-orange" href={applyUrl} target="_blank" rel="noreferrer">Apply for Kobe 2026 <ArrowUpRight size={17}/></a><p className="kobe-contact-line">Questions: riot.training.base@gmail.com · WhatsApp +81 80 3248 3703</p></section>
</article></SiteFrame>}
