"use client";
import { ChangeEvent, useState } from "react";
import { CalendarPlus, CheckCircle2, FileUp, LoaderCircle } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
import type { Locale } from "./site-frame";


type ImportRow={title:string;starts_at:string;ends_at:string|null;event_type:string;venue:string|null};
const words={
  ja:{title:"既存のカレンダーを取り込む",body:"Googleカレンダーなどから書き出したICSまたはCSVファイルを読み込めます。内容を確認し、取り込みを実行するまではデータを送信しません。",choose:"ICS／CSVファイルを選ぶ",found:"件の予定を読み込みました",import:"確認した予定を取り込む",done:"予定を取り込みました",error:"ファイルを読み取れませんでした。ファイル形式と日時をご確認ください。"},
  en:{title:"Import an existing calendar",body:"Import ICS exported from Google Calendar or a CSV. Nothing is sent until you review and confirm.",choose:"Choose ICS / CSV",found:"items ready",import:"Import reviewed events",done:"Events imported",error:"We could not read that file. Check its format and dates."},
  "zh-tw":{title:"匯入現有日曆",body:"可匯入Google Calendar等匯出的ICS或CSV。確認匯入前不會傳送資料。",choose:"選擇ICS／CSV",found:"項已讀取",import:"匯入已確認行程",done:"已匯入行程",error:"無法讀取。請確認格式與日期。"},
  ko:{title:"기존 캘린더 가져오기",body:"Google Calendar 등에서 내보낸 ICS 또는 CSV를 가져옵니다. 확인 전에는 데이터가 전송되지 않습니다.",choose:"ICS／CSV 선택",found:"개 준비됨",import:"확인한 일정 가져오기",done:"일정을 가져왔습니다",error:"파일을 읽을 수 없습니다. 형식과 날짜를 확인하세요."}
} as const;
function icsDate(value:string){const raw=value.trim();if(/^\d{8}$/.test(raw))return new Date(`${raw.slice(0,4)}-${raw.slice(4,6)}-${raw.slice(6,8)}T09:00:00+09:00`).toISOString();const m=raw.match(/^(\d{4})(\d{2})(\d{2})T(\d{2})(\d{2})(\d{2})(Z?)$/);if(!m)throw new Error("date");return new Date(`${m[1]}-${m[2]}-${m[3]}T${m[4]}:${m[5]}:${m[6]}${m[7]?"Z":"+09:00"}`).toISOString();}
function parseIcs(text:string):ImportRow[]{const unfolded=text.replace(/\r?\n[ \t]/g,"");return unfolded.split("BEGIN:VEVENT").slice(1).map(block=>{const value=(key:string)=>block.split(/\r?\n/).find(line=>line.startsWith(key))?.split(":").slice(1).join(":").replace(/\\,/g,",").replace(/\\n/g," ")||"";const start=value("DTSTART");if(!start)return null;const end=value("DTEND");return{title:value("SUMMARY")||"Imported event",starts_at:icsDate(start),ends_at:end?icsDate(end):null,event_type:"event",venue:value("LOCATION")||null};}).filter((row):row is ImportRow=>Boolean(row));}
function csvCells(line:string){const cells:string[]=[];let current="",quote=false;for(let i=0;i<line.length;i++){const char=line[i];if(char==='"'&&line[i+1]==='"'){current+='"';i++;}else if(char==='"')quote=!quote;else if(char===","&&!quote){cells.push(current.trim());current="";}else current+=char;}cells.push(current.trim());return cells;}
function parseCsv(text:string):ImportRow[]{const lines=text.replace(/^\uFEFF/,"").split(/\r?\n/).filter(Boolean);if(lines.length<2)return[];const headers=csvCells(lines[0]).map(x=>x.toLowerCase().replace(/\s+/g,"_"));const find=(row:string[],keys:string[])=>{const i=headers.findIndex(h=>keys.includes(h));return i>=0?row[i]:"";};return lines.slice(1).map(line=>{const row=csvCells(line),title=find(row,["title","summary","event","予定名","件名"]),start=find(row,["starts_at","start","start_date","date","開始","開始日時"]);if(!title||!start)return null;const starts=new Date(start);if(Number.isNaN(starts.getTime()))return null;const end=find(row,["ends_at","end","end_date","終了","終了日時"]),ends=end?new Date(end):null;return{title,starts_at:starts.toISOString(),ends_at:ends&&!Number.isNaN(ends.getTime())?ends.toISOString():null,event_type:find(row,["event_type","type","種類"])||"event",venue:find(row,["venue","location","場所"])||null};}).filter((row):row is ImportRow=>Boolean(row));}
export function CalendarImport({locale,teamId,timezone,userId,onImported}:{locale:Locale;teamId:string;timezone:string;userId:string;onImported:()=>Promise<void>}){const c=words[locale], [rows,setRows]=useState<ImportRow[]>([]),[state,setState]=useState<"idle"|"busy"|"done"|"error">("idle");async function choose(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;try{const text=await file.text(),parsed=file.name.toLowerCase().endsWith(".ics")?parseIcs(text):parseCsv(text);if(!parsed.length)throw new Error("empty");setRows(parsed.slice(0,250));setState("idle");}catch{setRows([]);setState("error");}}async function run(){setState("busy");const supabase=createClient();const {error}=await supabase.from("team_events").insert(rows.map(row=>({...row,team_id:teamId,timezone,availability_status:"confirmed",created_by:userId})));if(error){setState("error");return;}setRows([]);setState("done");await onImported();}return <section className="calendar-import"><div><FileUp/><h2>{c.title}</h2><p>{c.body}</p></div><label><input type="file" accept=".ics,.csv,text/calendar,text/csv" onChange={choose}/><span>{c.choose}</span></label>{rows.length?<div className="calendar-import-preview"><strong>{rows.length} {c.found}</strong>{rows.slice(0,4).map((row,i)=><span key={`${row.starts_at}-${i}`}>{new Date(row.starts_at).toLocaleDateString(locale)} · {row.title}</span>)}{rows.length>4?<small>+ {rows.length-4}</small>:null}<button type="button" disabled={state==="busy"} onClick={run}>{state==="busy"?<LoaderCircle className="spin"/>:<CalendarPlus/>}{c.import}</button></div>:null}{state==="done"?<p className="calendar-import-result"><CheckCircle2/>{c.done}</p>:null}{state==="error"?<p className="member-form-error">{c.error}</p>:null}</section>}
