import { ContactForm } from "./contact-form";
import { ArrowDown, ArrowRight, Building2, CalendarCheck, CheckCircle2, ClipboardCheck, FileText, Mail, MapPin, MessageCircle, MessageSquare, Search, ShieldCheck, TrainFront, Trophy, Users, WalletCards } from "lucide-react";
import { Locale, SiteFrame } from "@/components/site-frame";

const copy={
  en:{
    kicker:"HOST AN RBA CLINIC",title:["From the first message","to clinic day."],intro:"You do not need a finished plan. Tell us the city, players and purpose. RBA will organise the learning design, quote and next actions with you.",heroCta:"Start a free enquiry",heroSub:"No booking or charge is created by sending an enquiry.",
    flowLabel:"HOW IT WORKS",flowTitle:"Five clear steps to the court.",flowIntro:"The organiser and RBA confirm each condition before any booking is final.",steps:[["01","Send an enquiry","Share the city, preferred period, age group, expected player count and what you want the players to learn."],["02","15–30 min consultation","We clarify the development goal, court situation, travel conditions and roles. Online is usually enough."],["03","Programme & quote","RBA proposes the session format, coach structure, schedule and an itemised estimate. The quote is free."],["04","Confirm the event","We confirm the date, venue, payment terms, recruitment method, safety arrangements and cancellation terms in writing."],["05","Recruit & deliver","The organiser recruits locally; RBA prepares and delivers the clinic, then connects players to an appropriate next step."]],
    priceLabel:"HOW MUCH?",priceTitle:"The price follows the actual conditions.",priceLead:"There is currently no single nationwide clinic price. You receive the total before confirming the event—never after the fact.",free:"Enquiry & initial quote",freeValue:"¥0",formula:"Clinic total",plus:"+",items:[["Programme / coaching fee","Session length, number of sessions, coaches and required preparation"],["Travel & accommodation","Actual transport and lodging costs from Sendai, when required"],["Local operating costs","Venue, equipment, insurance and interpretation only when needed"]],priceNote:"The organiser may provide the venue or transport directly. We separate these items so the same cost is not charged twice.",
    readyLabel:"WHAT TO PREPARE",readyTitle:"Five answers are enough to begin.",ready:["City and possible venue","Preferred date or period","Age group and expected players","The development problem to solve","Approximate working budget"],
    rolesLabel:"WHO DOES WHAT",rolesTitle:"Clear roles keep the event simple.",organiser:"Local organiser",organiserItems:["Secure or suggest the court","Recruit players and manage local notices","Provide a responsible adult and emergency contact","Share venue rules and local constraints"],rba:"RBA",rbaItems:["Design the learning programme","Assign and brief coaches","Provide recruitment copy and required information","Deliver the clinic and propose the next development step"],
    contactLabel:"CONTACT",contactTitle:"The official route is the enquiry form.",contactBody:"After submission, RBA reviews the conditions and replies by email. WhatsApp is available for a quick question, but the final scope and quote are confirmed in writing.",formCta:"Open the enquiry form",direct:"Direct contact",whatsapp:"Ask a quick question on WhatsApp"
  },
  ja:{
    kicker:"RBAクリニックを開催する",title:["最初のご相談から、","開催当日まで。"],intro:"企画内容がまだ固まっていなくても問題ありません。開催地域、対象年代、目的をお知らせください。育成内容、見積もり、準備の進め方をRBAが一緒に整理します。",heroCta:"無料で開催相談をする",heroSub:"相談フォームを送信しただけで、予約が確定したり料金が発生したりすることはありません。",
    flowLabel:"開催までの流れ",flowTitle:"ご相談から開催当日まで、5つのステップで進めます。",flowIntro:"日程、費用、役割分担など、すべての条件を書面で確認したうえで正式決定となります。",steps:[["01","開催相談を送る","開催地域、希望時期、対象年代、予定人数、選手に学んでほしい内容をフォームからお知らせください。"],["02","15〜30分の事前相談","育成の目的、会場やコートの状況、移動条件、主催者とRBAの役割分担を確認します。通常はオンラインで完結します。"],["03","内容と見積もりをご案内","練習内容、指導体制、当日の流れ、費用の内訳をご提案します。ご相談と初回の見積もりは無料です。"],["04","日程・会場を正式に決定","日程、会場、支払条件、募集方法、安全管理、キャンセル条件を書面で確認します。"],["05","参加者を募集して開催","地域での参加者募集は主催者が、プログラムの準備と当日の指導はRBAが担当します。開催後は、次の育成機会についてもご案内します。"]],
    priceLabel:"料金について",priceTitle:"実際の開催条件に合わせて算出します。",priceLead:"現在、全国一律のクリニック料金は設定していません。開催確定前に総額と内訳を提示し、合意後に進めます。",free:"開催相談・初回見積り",freeValue:"¥0",formula:"開催費用",plus:"＋",items:[["企画・指導料","実施時間、回数、担当コーチ数、事前準備の内容で算定"],["交通・宿泊実費","仙台からの移動費と、必要な場合のみ宿泊費"],["現地運営費","会場、備品、保険、通訳など、必要な項目だけを計上"]],priceNote:"会場や移動手段を主催者側で用意できる場合は、その分を重ねて請求しません。見積書で項目を分けて確認できます。",
    readyLabel:"最初に必要な情報",readyTitle:"まずは、この5項目だけで大丈夫です。",ready:["開催したい地域・会場候補","希望日または開催時期","対象年代・予定人数","解決したい育成課題","ご予算の目安"],
    rolesLabel:"役割分担",rolesTitle:"誰が何をするか、最初に整理します。",organiser:"地域の主催者",organiserItems:["体育館の確保または候補提示","地域での募集・参加者連絡","責任者・緊急連絡先の設定","会場ルールや地域事情の共有"],rba:"RBA",rbaItems:["育成プログラムの設計","担当コーチの調整・共有","募集文面と必要情報の提供","当日の指導と次の育成機会の提案"],
    contactLabel:"連絡方法",contactTitle:"正式な窓口は、開催相談フォームです。",contactBody:"送信後、RBAが条件を確認し、メールでご連絡します。簡単な質問はWhatsAppでも可能ですが、開催内容と見積りは必ず書面で確定します。",formCta:"開催相談フォームを開く",direct:"直接連絡",whatsapp:"WhatsAppで簡単に質問する"
  },
  "zh-tw":{
    kicker:"舉辦RBA訓練營",title:["從第一次聯絡，","到活動當天。"],intro:"即使企劃尚未完成也沒關係。告訴我們城市、對象與目的，RBA會與您整理培育內容、報價和準備順序。",heroCta:"開始免費諮詢",heroSub:"提交諮詢不代表預約成立，也不會產生費用。",
    flowLabel:"舉辦流程",flowTitle:"五個步驟，清楚走到球場。",flowIntro:"所有條件均以書面確認後，才正式確定舉辦。",steps:[["01","提交舉辦需求","提供城市、希望期間、年齡層、預計人數和學習目標。"],["02","15–30分鐘諮詢","確認培育目標、場地、交通條件，以及雙方分工。通常可線上完成。"],["03","方案與報價","RBA提出課程、教練配置、時程及分項估價。諮詢與初次報價免費。"],["04","正式確認活動","以書面確認日期、場地、付款、招募、安全安排與取消條件。"],["05","招募並舉辦","主辦單位負責當地招募，RBA負責準備與指導，活動後再連結下一階段培育。"]],
    priceLabel:"費用",priceTitle:"依實際舉辦條件計算。",priceLead:"目前沒有全日本統一價格。正式確認前會先提供總額與明細。",free:"諮詢與初次報價",freeValue:"¥0",formula:"活動總費用",plus:"＋",items:[["企劃與教練費","依時數、場次、教練人數與準備內容計算"],["交通與住宿實費","從仙台出發的交通及必要住宿"],["當地營運費","僅計入所需的場地、器材、保險或口譯"]],priceNote:"若主辦單位直接提供場地或交通，相關費用不會重複計算。",
    readyLabel:"開始前需要",readyTitle:"先提供五項資訊即可。",ready:["城市與場地候選","希望日期或期間","年齡層與預計人數","希望改善的培育課題","大致預算範圍"],rolesLabel:"雙方分工",rolesTitle:"先說清楚由誰負責。",organiser:"當地主辦單位",organiserItems:["安排或提議場地","當地招募與參加者聯絡","設定負責人與緊急聯絡","提供場地規則及當地條件"],rba:"RBA",rbaItems:["設計培育課程","安排並簡報教練","提供招募文案與必要資訊","現場指導並提出下一階段建議"],contactLabel:"聯絡方式",contactTitle:"正式窗口為舉辦諮詢表單。",contactBody:"送出後，RBA將審核條件並以電郵回覆。簡單問題可使用WhatsApp，但內容與報價會以書面確認。",formCta:"開啟舉辦諮詢表單",direct:"直接聯絡",whatsapp:"透過WhatsApp快速提問"
  },
  ko:{
    kicker:"RBA 클리닉 개최",title:["첫 문의부터","클리닉 당일까지."],intro:"완성된 기획이 없어도 괜찮습니다. 지역, 대상과 목적을 알려 주시면 RBA가 성장 프로그램, 견적과 준비 순서를 함께 정리합니다.",heroCta:"무료 개최 상담 시작",heroSub:"문의만으로 예약이 확정되거나 비용이 발생하지 않습니다.",
    flowLabel:"개최 절차",flowTitle:"코트까지 이어지는 다섯 단계.",flowIntro:"모든 조건을 서면으로 확인한 뒤 개최가 확정됩니다.",steps:[["01","개최 문의 보내기","지역, 희망 시기, 연령, 예상 인원과 학습 목표를 알려 주세요."],["02","15–30분 사전 상담","육성 목표, 코트, 이동 조건과 역할을 확인합니다. 보통 온라인으로 가능합니다."],["03","프로그램과 견적","훈련 내용, 코치 구성, 일정과 항목별 견적을 제안합니다. 상담과 최초 견적은 무료입니다."],["04","일정·장소 확정","일정, 장소, 결제 조건, 모집, 안전 관리와 취소 조건을 서면으로 확인합니다."],["05","모집 및 개최","지역 모집은 주최자가, 프로그램 준비와 현장 지도는 RBA가 담당합니다. 이후 성장 단계도 안내합니다."]],
    priceLabel:"비용",priceTitle:"실제 개최 조건에 따라 산정합니다.",priceLead:"현재 전국 공통 고정 가격은 없습니다. 개최 확정 전에 총액과 세부 내역을 안내합니다.",free:"상담·최초 견적",freeValue:"¥0",formula:"개최 총비용",plus:"＋",items:[["기획·지도비","시간, 횟수, 코치 수와 사전 준비에 따라 산정"],["교통·숙박 실비","센다이 출발 교통비와 필요한 경우 숙박비"],["현지 운영비","필요한 장소, 장비, 보험과 통역 비용만 반영"]],priceNote:"주최자가 장소나 이동 수단을 직접 준비하면 해당 비용은 중복 청구하지 않습니다.",
    readyLabel:"준비할 정보",readyTitle:"다섯 가지만 알려 주세요.",ready:["개최 지역과 장소 후보","희망 날짜 또는 기간","대상 연령과 예상 인원","해결하려는 성장 과제","대략적인 예산"],rolesLabel:"역할 분담",rolesTitle:"누가 무엇을 하는지 먼저 정합니다.",organiser:"지역 주최자",organiserItems:["체육관 확보 또는 후보 제안","지역 모집과 참가자 안내","책임자와 긴급 연락처 지정","장소 규칙과 지역 조건 공유"],rba:"RBA",rbaItems:["육성 프로그램 설계","담당 코치 배정 및 브리핑","모집 문구와 필수 정보 제공","현장 지도와 다음 성장 단계 제안"],contactLabel:"연락 방법",contactTitle:"공식 창구는 개최 문의 양식입니다.",contactBody:"제출 후 RBA가 조건을 확인하고 이메일로 회신합니다. 간단한 질문은 WhatsApp도 가능하지만 내용과 견적은 서면으로 확정합니다.",formCta:"개최 문의 양식 열기",direct:"직접 연락",whatsapp:"WhatsApp으로 간단히 문의"
  }
} as const;

const stepIcons=[MessageSquare,Search,FileText,CalendarCheck,Trophy];
const costIcons=[ClipboardCheck,TrainFront,Building2];

export function ClinicRequest({locale}:{locale:Locale}){
  const c=copy[locale];
  const subject=locale==="ja"?"RBAクリニック開催相談":locale==="zh-tw"?"RBA訓練營舉辦諮詢":locale==="ko"?"RBA 클리닉 개최 상담":"RBA Clinic Hosting Enquiry";
  const system=({
    en:[["01","BRIEF","City · players · purpose"],["02","DESIGN","Programme · roles · quote"],["03","DELIVER","Recruit · prepare · clinic"]],
    ja:[["01","相談","地域・対象・育成目的"],["02","設計","内容・役割・見積り"],["03","開催","募集・準備・クリニック"]],
    "zh-tw":[["01","諮詢","地區・對象・培育目的"],["02","設計","內容・角色・報價"],["03","執行","招募・準備・訓練營"]],
    ko:[["01","상담","지역・대상・성장 목표"],["02","설계","내용・역할・견적"],["03","개최","모집・준비・클리닉"]],
  } as const)[locale];
  return <div lang={locale==="zh-tw"?"zh-Hant-TW":locale}><SiteFrame locale={locale} languagePage="clinic-request">
    <section className="request-hero request-hero-visual section-pad"><div><p className="section-index">{c.kicker}</p><h1>{c.title[0]}<br/>{c.title[1]}</h1><p>{c.intro}</p><a className="button button-orange" href="#request-form">{c.heroCta}<ArrowDown size={17}/></a><small><ShieldCheck size={16}/>{c.heroSub}</small></div><div className="request-hero-system" aria-label={c.flowTitle}><p>RBA / CLINIC DELIVERY SYSTEM</p>{system.map(([number,title,detail])=><div key={number}><span>{number}</span><strong>{title}</strong><small>{detail}</small></div>)}<b>FROM SENDAI<br/>TO YOUR COURT.</b></div></section>
    <section className="hosting-flow section-pad"><div className="section-head"><div><p className="section-index">{c.flowLabel}</p><h2>{c.flowTitle}</h2></div><p>{c.flowIntro}</p></div><ol>{c.steps.map(([n,title,body],i)=>{const Icon=stepIcons[i];return <li key={n}><div className="flow-icon"><Icon aria-hidden="true"/><span>{n}</span></div><h3>{title}</h3><p>{body}</p>{i<c.steps.length-1&&<ArrowRight className="flow-arrow" aria-hidden="true"/>}</li>})}</ol></section>
    <section className="hosting-price section-pad"><div className="hosting-price-head"><p className="section-index inverse">{c.priceLabel}</p><h2>{c.priceTitle}</h2><p>{c.priceLead}</p><div className="free-estimate"><span>{c.free}</span><strong>{c.freeValue}</strong></div></div><div className="price-formula" aria-label={c.formula}><div className="price-total"><WalletCards/><span>{c.formula}</span></div>{c.items.map(([title,body],i)=>{const Icon=costIcons[i];return <div className="price-item" key={title}><span className="price-plus">{i===0?"=":c.plus}</span><Icon/><div><strong>{title}</strong><p>{body}</p></div></div>})}<p className="price-note">{c.priceNote}</p></div></section>
    <section className="hosting-ready section-pad"><div><p className="section-index">{c.readyLabel}</p><h2>{c.readyTitle}</h2></div><ul>{c.ready.map((item,i)=><li key={item}><span>{String(i+1).padStart(2,"0")}</span><strong>{item}</strong><CheckCircle2 aria-hidden="true"/></li>)}</ul></section>
    <section className="hosting-roles section-pad"><div className="section-head"><div><p className="section-index inverse">{c.rolesLabel}</p><h2>{c.rolesTitle}</h2></div></div><div className="role-grid"><article><MapPin aria-hidden="true"/><h3>{c.organiser}</h3><ul>{c.organiserItems.map(x=><li key={x}>{x}</li>)}</ul></article><article><Users aria-hidden="true"/><h3>{c.rba}</h3><ul>{c.rbaItems.map(x=><li key={x}>{x}</li>)}</ul></article></div></section>
    <section className="hosting-contact section-pad"><div><p className="section-index">{c.contactLabel}</p><h2>{c.contactTitle}</h2><p>{c.contactBody}</p></div><a className="button button-orange" href="#request-form">{c.formCta}<ArrowDown size={17}/></a></section>
    <ContactForm locale={locale}/>
    <section className="request-fallback section-pad"><p className="section-index">{c.direct}</p><div><a href={"mailto:riot.training.base@gmail.com?subject="+encodeURIComponent(subject)}><Mail size={19}/>riot.training.base@gmail.com</a><a href="https://wa.me/818032483703" target="_blank" rel="noreferrer"><MessageCircle size={19}/>{c.whatsapp}</a></div></section>
  </SiteFrame></div>;
}