"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {CheckCircle2,LoaderCircle,NotebookPen} from "lucide-react";
import {createClient} from "@/lib/supabase/client";
type Row={id:string;practice_date:string;learning_question:string;observation:string|null;next_change:string|null};
export function CoachPracticeLoop({userId,lessonId}:{userId:string;lessonId?:string}){
 const db=useMemo(()=>createClient(),[]),[rows,setRows]=useState<Row[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>{void db.from("coach_practice_reflections").select("id,practice_date,learning_question,observation,next_change").eq("user_id",userId).order("practice_date",{ascending:false}).limit(4).then(({data})=>setRows((data||[]) as Row[]))},[db,userId]);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage("");const form=e.currentTarget,f=new FormData(form);const {data,error}=await db.from("coach_practice_reflections").insert({user_id:userId,lesson_id:lessonId||null,practice_date:String(f.get("date")),team_context:String(f.get("context")||"").trim()||null,age_group:String(f.get("age")||"").trim()||null,learning_question:String(f.get("question")||"").trim(),planned_constraint:String(f.get("plan")||"").trim()||null,observation:String(f.get("observation")||"").trim()||null,player_response:String(f.get("response")||"").trim()||null,coach_reflection:String(f.get("reflection")||"").trim()||null,next_change:String(f.get("next")||"").trim()||null,visibility:f.get("share")==="on"?"anonymized_for_learning":"private"}).select("id,practice_date,learning_question,observation,next_change").single();if(error){setMessage("保存できませんでした。");setBusy(false);return;}setRows(current=>[data as Row,...current].slice(0,4));const reviewed=Boolean(String(f.get("observation")||"").trim()||String(f.get("reflection")||"").trim()||String(f.get("next")||"").trim());void db.from("development_action_events").insert({user_id:userId,action_type:reviewed?"coach_review":"coach_plan",item_type:"coach_practice",item_key:data.id,metadata:{lesson_id:lessonId||null}});form.reset();setMessage(reviewed?"振り返りを保存しました。":"練習で確かめたいことを保存しました。");setBusy(false)}
 return <section className="coach-practice-loop"><div className="section-head"><div><p className="section-index">PLAN → COACH → REVIEW</p><h2>学んだことを、実際の練習で確かめる。</h2></div><p>「うまくいったメニュー」を集めるための記録ではありません。何を確かめたかったのか、選手にどんな変化が見えたのか、自分は次に何を変えるのかを残します。</p></div><form onSubmit={save}><label>実践日<input name="date" type="date" defaultValue={new Date().toISOString().slice(0,10)} required/></label><label>年代<input name="age" placeholder="例：U12"/></label><label className="wide">今回、確かめたいこと<textarea name="question" required maxLength={500} placeholder="例：守備を見て、パスとドライブを選び分ける場面を増やせるか"/></label><label className="wide">試したルール・練習の工夫<textarea name="plan" maxLength={1200}/></label><label className="wide">実際に起きたこと<textarea name="observation" maxLength={1600}/></label><label className="wide">選手に見られた反応や判断<textarea name="response" maxLength={1600}/></label><label className="wide">自分の関わり方で気づいたこと<textarea name="reflection" maxLength={1600}/></label><label className="wide">次回、変えてみること<textarea name="next" maxLength={1000}/></label><label className="coach-practice-share"><input name="share" type="checkbox"/><span>選手やチームが特定されない形に限り、今後D-HUBの学習事例として紹介することに同意する</span></label><button disabled={busy}>{busy?<LoaderCircle className="spin"/>:<NotebookPen/>}この内容を保存</button>{message?<p role="status">{message}</p>:null}</form>{rows.length?<div className="coach-practice-history"><h3>最近の振り返り</h3>{rows.map(row=><article key={row.id}><time>{row.practice_date}</time><strong>{row.learning_question}</strong>{row.observation?<p>{row.observation}</p>:null}{row.next_change?<small>次に試す → {row.next_change}</small>:null}<CheckCircle2/></article>)}</div>:null}</section>
}
