"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {CheckCircle2,LoaderCircle,NotebookPen} from "lucide-react";
import {createClient} from "@/lib/supabase/client";
type Row={id:string;practice_date:string;learning_question:string;observation:string|null;next_change:string|null};
export function CoachPracticeLoop({userId,lessonId}:{userId:string;lessonId?:string}){
 const db=useMemo(()=>createClient(),[]),[rows,setRows]=useState<Row[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>{void db.from("coach_practice_reflections").select("id,practice_date,learning_question,observation,next_change").eq("user_id",userId).order("practice_date",{ascending:false}).limit(4).then(({data})=>setRows((data||[]) as Row[]))},[db,userId]);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage("");const form=e.currentTarget,f=new FormData(form);const {data,error}=await db.from("coach_practice_reflections").insert({user_id:userId,lesson_id:lessonId||null,practice_date:String(f.get("date")),team_context:String(f.get("context")||"").trim()||null,age_group:String(f.get("age")||"").trim()||null,learning_question:String(f.get("question")||"").trim(),planned_constraint:String(f.get("plan")||"").trim()||null,observation:String(f.get("observation")||"").trim()||null,player_response:String(f.get("response")||"").trim()||null,coach_reflection:String(f.get("reflection")||"").trim()||null,next_change:String(f.get("next")||"").trim()||null,visibility:f.get("share")==="on"?"anonymized_for_learning":"private"}).select("id,practice_date,learning_question,observation,next_change").single();if(error){setMessage("保存できませんでした。");setBusy(false);return;}setRows(current=>[data as Row,...current].slice(0,4));form.reset();setMessage("実践記録を保存しました。");setBusy(false)}
 return <section className="coach-practice-loop"><div className="section-head"><div><p className="section-index">PLAN → COACH → REVIEW</p><h2>学んだことを、体育館で試した記録。</h2></div><p>うまくいった練習メニューを集めるためではありません。何を見ようとしたか、選手に何が起きたか、次に何を変えるかを残します。</p></div><form onSubmit={save}><label>実践日<input name="date" type="date" defaultValue={new Date().toISOString().slice(0,10)} required/></label><label>年代<input name="age" placeholder="例：U12"/></label><label className="wide">今回の問い<textarea name="question" required maxLength={500} placeholder="例：守備を見てパスとドライブを選ぶ回数を増やせるか"/></label><label className="wide">試した制約・設計<textarea name="plan" maxLength={1200}/></label><label className="wide">実際に観察できたこと<textarea name="observation" maxLength={1600}/></label><label className="wide">選手の反応・判断<textarea name="response" maxLength={1600}/></label><label className="wide">自分のコーチングを振り返る<textarea name="reflection" maxLength={1600}/></label><label className="wide">次回変えること<textarea name="next" maxLength={1000}/></label><label className="coach-practice-share"><input name="share" type="checkbox"/><span>個人やチームを特定できない形に限り、将来のD-HUB学習事例として利用することに同意する</span></label><button disabled={busy}>{busy?<LoaderCircle className="spin"/>:<NotebookPen/>}実践記録を保存</button>{message?<p role="status">{message}</p>:null}</form>{rows.length?<div className="coach-practice-history"><h3>最近の実践</h3>{rows.map(row=><article key={row.id}><time>{row.practice_date}</time><strong>{row.learning_question}</strong>{row.observation?<p>{row.observation}</p>:null}{row.next_change?<small>次回 → {row.next_change}</small>:null}<CheckCircle2/></article>)}</div>:null}</section>
}
