import type {Locale} from "./site-frame";
import {localePath} from "./site-frame";
import {programmeById} from "./programme-data";
import styles from "./coach-education-loop.module.css";
const copy={
 ja:{label:"RBA COACH EDUCATION",title:"毎週の実践と、世界基準の学びをつなぐ。",dTag:"WEEKLY / 48 SESSIONS",dTitle:"D-HUB",dBody:"年間48回。短い学び、現場での実践、振り返りを繰り返し、指導を少しずつ更新します。",dCta:"D-HUBを見る",tTag:"SPECIAL SESSION",tTitle:"TORSTEN LOIBL ONLINE CLINIC",tBody:"世界の育成現場で積み上げられた知見に直接触れ、練習設計とゲーム理解を深める特別講習です。",tCta:"次回クリニックを見る",flow:["D-HUBで学ぶ","Torsten講習","現場で試す","振り返る","次の学びへ"]},
 en:{label:"RBA COACH EDUCATION",title:"Connect weekly practice with world-level learning.",dTag:"WEEKLY / 48 SESSIONS",dTitle:"D-HUB",dBody:"Forty-eight sessions a year: learn briefly, apply on court, reflect and improve practice over time.",dCta:"Explore D-HUB",tTag:"SPECIAL SESSION",tTitle:"TORSTEN LOIBL ONLINE CLINIC",tBody:"Access knowledge shaped in international development environments and deepen practice design and game understanding.",tCta:"See the next clinic",flow:["Learn in D-HUB","Torsten clinic","Apply on court","Reflect","Continue"]},
 "zh-tw":{label:"RBA教練教育",title:"連結每週實踐與世界級學習。",dTag:"每週／全年48次",dTitle:"D-HUB",dBody:"全年48次，以短時間學習、場上實踐與反思，持續更新執教方法。",dCta:"查看D-HUB",tTag:"特別講座",tTitle:"TORSTEN LOIBL線上講座",tBody:"直接接觸國際培育現場的知識，深化訓練設計與比賽理解。",tCta:"查看下一場講座",flow:["D-HUB學習","Torsten講座","場上實踐","反思","下一次學習"]},
 ko:{label:"RBA 코치 교육",title:"매주의 실천과 세계 수준의 배움을 연결합니다.",dTag:"주간／연간 48회",dTitle:"D-HUB",dBody:"연간 48회, 짧게 배우고 현장에서 실천하고 돌아보며 코칭을 꾸준히 개선합니다.",dCta:"D-HUB 보기",tTag:"SPECIAL SESSION",tTitle:"TORSTEN LOIBL 온라인 클리닉",tBody:"국제 육성 현장의 지식을 직접 접하고 훈련 설계와 경기 이해를 깊게 합니다.",tCta:"다음 클리닉 보기",flow:["D-HUB 학습","Torsten 클리닉","현장 실천","성찰","다음 학습"]}
} as const;
export function CoachEducationLoop({locale}:{locale:Locale}){const c=copy[locale];const i=locale==="en"?0:locale==="ja"?1:locale==="zh-tw"?2:3;return <section className={styles.section}><div className={styles.head}><p>{c.label}</p><h2>{c.title}</h2></div><div className={styles.grid}><article className={styles.card}><span>{c.dTag}</span><h3>{c.dTitle}</h3><p>{c.dBody}</p><a href={localePath(locale,"d-hub")}>{c.dCta}<b>→</b></a></article><article className={styles.card}><span>{c.tTag} · {programmeById.torsten.date[i]}</span><h3>{c.tTitle}</h3><p>{c.tBody}</p><a href={localePath(locale,"events/torsten-loibl-online-clinic")}>{c.tCta}<b>→</b></a></article></div><div className={styles.flow}>{c.flow.map(x=><span key={x}>{x}</span>)}</div></section>}
