import {ArrowRight,ArrowUpRight,Camera,MapPin,Users} from "lucide-react";
import {Locale,localePath} from "./site-frame";


const copy={
 en:{clubs:"U15 CLUB PROJECT",clubsTitle:"Local teams. Shared development standards.",clubsIntro:"RBA is developing an expanding U15 club network. Each programme respects its local community while sharing player-centred development, S&C and responsible team operations.",areas:[["Gream Sendai","Sendai · Miyagi","In operation / programme development"],["Gream Okinawa","Okinawa","Regional programme development"],["DSM","Akita","U15 club collaboration"]],more:"We plan to add further regions as the right coaches, venues and community partners come together.",ask:"Ask about the U15 club project",support:"JOIN THE PROJECT",supportTitle:"Partners and coaches wanted.",sponsorTitle:"Become an RBA sponsor",sponsor:"Support can create safer gyms, reduce travel and participation costs, provide equipment and open learning opportunities across regions. RBA explains the purpose, use and visibility of every partnership.",sponsorCta:"Read sponsorship information",coachTitle:"Coach with RBA",coach:"We welcome coaches who put young players first, keep learning and can work responsibly with families and local partners. Coaching experience matters, but values, communication and reliability come first.",coachCta:"Ask about coaching opportunities",gallery:"CLINIC ARCHIVE",galleryTitle:"Past clinics, told through the people and the court.",galleryIntro:"This section is reserved for approved photographs from past clinics and camps. Images will be added only after confirming child safeguarding, media consent and context.",photo:"Past clinic photo",photoCta:"View RBA field stories"},
 ja:{clubs:"U15クラブチーム事業",clubsTitle:"地域に根ざし、共通の育成基準でつながる。",clubsIntro:"RBAは、地域ごとの文化や環境を大切にしながら、選手を中心にした育成、S&C、責任あるチーム運営を共有するU15クラブネットワークを展開しています。",areas:[["Gream仙台","宮城県仙台市","活動・育成プログラムを実施中"],["Gream沖縄","沖縄県","地域での活動基盤を整備中"],["DSM","秋田県","U15クラブ連携"]],more:"今後も、育成への考え方を共有できる指導者、会場、地域パートナーがそろった地域から、順次活動を広げていきます。",ask:"U15クラブ事業について問い合わせる",support:"一緒に活動する仲間を募集しています",supportTitle:"スポンサー・指導者を募集しています。",sponsorTitle:"RBAの活動を支えるスポンサー募集",sponsor:"ご支援は、安全な活動環境の整備、遠征費・参加費の負担軽減、用具の充実、地域を越えた学びの機会につながります。協賛の目的、使い道、ロゴなどの掲出方法を事前に整理し、責任を持ってご報告します。",sponsorCta:"スポンサー募集の詳細を見る",coachTitle:"選手の成長に向き合うコーチ募集",coach:"選手の成長を第一に考え、学び続け、保護者や地域の方々と誠実に関われる指導者を募集しています。指導歴だけでなく、育成への考え方、対話する力、責任感を大切にします。",coachCta:"コーチ募集について問い合わせる",gallery:"クリニック活動記録",galleryTitle:"これまでの活動を、現場の雰囲気とともに伝える。",galleryIntro:"子どもの安全と写真・映像の利用同意を確認し、活動の背景が正しく伝わる内容だけを公式SNSで公開しています。",photo:"公式SNSで活動を見る",photoCta:"RBAの活動記録を見る"},
 "zh-tw":{clubs:"U15俱樂部計畫",clubsTitle:"扎根地方，以共同培育標準連結。",clubsIntro:"RBA正在發展U15俱樂部網絡。各地尊重在地社群，同時共享以球員為中心的培育、體能訓練與負責任的球隊運作。",areas:[["Gream仙台","宮城・仙台","營運與培育計畫進行中"],["Gream沖繩","沖繩","地方計畫建置中"],["DSM","秋田","U15俱樂部合作"]],more:"未來將在合適的教練、場地與地方夥伴到位後，逐步拓展更多地區。",ask:"洽詢U15俱樂部計畫",support:"加入RBA計畫",supportTitle:"招募贊助夥伴與教練。",sponsorTitle:"成為RBA贊助夥伴",sponsor:"支持可改善安全環境、減輕交通與參加負擔、補充器材，並創造跨地區學習機會。我們會事先說明目的、用途與品牌呈現。",sponsorCta:"查看贊助資訊",coachTitle:"加入RBA教練團隊",coach:"我們歡迎以年輕球員為優先、持續學習，並能與家庭及地方夥伴負責任合作的教練。除經驗外，我們更重視價值觀、溝通與可靠度。",coachCta:"洽詢教練招募",gallery:"訓練營紀錄",galleryTitle:"用照片保存球場上的成長。",galleryIntro:"此區保留給過往訓練營與培育營的核准照片。確認兒少安全、影像同意與完整脈絡後才會上架。",photo:"過往活動照片",photoCta:"查看RBA活動紀錄"},
 ko:{clubs:"U15 클럽 프로젝트",clubsTitle:"지역에 뿌리내리고, 같은 육성 기준으로 연결합니다.",clubsIntro:"RBA는 지역 문화를 존중하면서 선수 중심 육성, S&C와 책임 있는 팀 운영을 공유하는 U15 클럽 네트워크를 확대하고 있습니다.",areas:[["Gream 센다이","미야기・센다이","운영 및 육성 프로그램 진행 중"],["Gream 오키나와","오키나와","지역 프로그램 기반 구축 중"],["DSM","아키타","U15 클럽 협력"]],more:"올바른 코치, 시설과 지역 파트너가 함께하는 지역부터 앞으로도 확장할 계획입니다.",ask:"U15 클럽 프로젝트 문의",support:"함께할 파트너 모집",supportTitle:"스폰서와 코치를 모집합니다.",sponsorTitle:"RBA 스폰서 참여",sponsor:"후원은 안전한 체육 환경, 이동 및 참가 부담 완화, 장비 지원과 지역 간 학습 기회를 만듭니다. 모든 협력의 목적, 사용처와 노출 방식을 명확히 안내합니다.",sponsorCta:"스폰서 안내 보기",coachTitle:"RBA 코치 모집",coach:"어린 선수를 우선하고 계속 배우며, 가족 및 지역 파트너와 책임 있게 협력할 코치를 찾습니다. 경력뿐 아니라 가치관, 소통과 신뢰를 중요하게 봅니다.",coachCta:"코치 모집 문의",gallery:"클리닉 아카이브",galleryTitle:"코트에서의 성장을 사진으로 기록합니다.",galleryIntro:"과거 클리닉과 캠프의 승인된 사진을 위한 공간입니다. 아동 보호, 촬영 동의와 맥락을 확인한 뒤 추가합니다.",photo:"과거 클리닉 사진",photoCta:"RBA 활동 기록 보기"}
} as const;


export function GrowthSections({locale}:{locale:Locale}){const c=copy[locale];const coachSubject=({en:"RBA coaching opportunities",ja:"RBAコーチ募集について","zh-tw":"RBA教練招募洽詢",ko:"RBA 코치 모집 문의"})[locale];return <>
 <section className="club-network section-pad" id="u15-clubs"><div className="section-head"><div><p className="section-index">{c.clubs}</p><h2>{c.clubsTitle}</h2></div><p>{c.clubsIntro}</p></div><div className="club-grid">{c.areas.map(([name,place,state])=><a href={localePath(locale,"contact")} key={name}><Users size={25}/><h3>{name}</h3><p><MapPin size={15}/>{place}</p><span>{state}</span><ArrowUpRight size={20}/></a>)}</div><div className="club-more"><p>{c.more}</p><a className="text-link" href={localePath(locale,"contact")}>{c.ask}<ArrowRight size={16}/></a></div></section>
 <section className="recruit-section section-pad"><div className="section-head"><div><p className="section-index inverse">{c.support}</p><h2>{c.supportTitle}</h2></div></div><div className="recruit-grid"><article><span>SPONSOR / PARTNER</span><h3>{c.sponsorTitle}</h3><p>{c.sponsor}</p><a className="button button-light" href={localePath(locale,"partners")}>{c.sponsorCta}<ArrowRight size={17}/></a></article><article><span>COACH / STAFF</span><h3>{c.coachTitle}</h3><p>{c.coach}</p><a className="button button-light" href={`mailto:riot.training.base@gmail.com?subject=${encodeURIComponent(coachSubject)}`}>{c.coachCta}<ArrowUpRight size={17}/></a></article></div></section>
 <section className="clinic-gallery section-pad" id="clinic-gallery"><div className="section-head"><div><p className="section-index">{c.gallery}</p><h2>{c.galleryTitle}</h2></div><p>{c.galleryIntro}</p></div><div className="gallery-grid">{[1,2,3,4,5,6].map(n=><a href="https://www.instagram.com/riot.basketball.academy/" target="_blank" rel="noreferrer" key={n}><Camera size={28}/><span>{c.photo} {String(n).padStart(2,"0")}</span></a>)}</div><a className="text-link" href={localePath(locale,"social")}>{c.photoCta}<ArrowRight size={16}/></a></section>
 </>}
