"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase/client";
import {programmeById,programmes,type Programme} from "./programme-data";
import type {Locale} from "./site-frame";
import styles from "./homecourt-overview.module.css";
import {HomecourtDiscovery} from "./homecourt-discovery";

type Props={locale:Locale;userId:string;role:"player"|"parent"|"coach"|"admin";displayName:string;region:string|null;birthYear:number|null;nextEvent:{title:string;starts_at:string;venue:string|null}|null};
type Saved={id:string;item_key:string;title:string;href:string};
type Journey={id:string;title:string;date:string;kind:"RBA"|"SELF"};
type Snapshot={official:number;applications:number;goals:number;children:number;saved:Saved[];journey:Journey[];notRelevant:string[];opportunityTypes:string[]};
const empty:Snapshot={official:0,applications:0,goals:0,children:0,saved:[],journey:[],notRelevant:[],opportunityTypes:[]};
const tx={
 ja:{week:"MY WEEK",weekTitle:"今週取り組むこと",journey:"MY JOURNEY",journeyTitle:"これまでの経験を、次の一歩につなげる。",saved:"SAVED",savedTitle:"保存した活動",opps:"NEXT OPPORTUNITIES",oppsTitle:"次に参加できる活動",next:"次の予定",none:"まだ予定はありません",region:"活動地域",age:"年代",official:"RBAで参加確認済み",applications:"申込状況・履歴",goals:"目標",savedCount:"保存",save:"保存",savedAction:"保存済み",detail:"詳細・申込",notRelevant:"今回は表示しない",emptyJourney:"Basketball Passportに参加履歴を記録すると、ここにこれまでの経験が表示されます。",emptySaved:"気になる活動を保存すると、ここからすぐに確認できます。",coachWeek:[["D-HUB","学んだことを、次の練習で試す。","/ja/d-hub","今週の学びを開く"],["TORSTEN LOIBL","世界の育成現場で磨かれてきた考え方を学ぶ特別講習。","/ja/events/torsten-loibl-online-clinic","次回講習を見る"],["COACH EDUCATION","練習設計、意思決定、長期育成、S&Cをつなげて学ぶ。","/ja/coaches","学びを選ぶ"]],playerWeek:[["PASSPORT","これまでの参加と気づきを振り返る。","#passport-title","歩みを見る"],["DISCOVER","年代・地域・目的から、次の機会を探す。","/ja/opportunities","機会を探す"],["MY FILM","写真や動画で以前の自分と見比べる。","#passport-title","成長ノートを開く"]],parentWeek:[["CHILDREN","子どもごとの予定・履歴・次の機会を確認。","#passport-title","子どもの記録を見る"],["APPLICATIONS","申込と支払い状況をまとめて確認。","/ja/payments","申込・決済を見る"],["NEXT OPPORTUNITY","年代と地域に合う次の機会を探す。","/ja/opportunities","機会を探す"]]},
 en:{week:"MY WEEK",weekTitle:"Start here this week.",journey:"MY JOURNEY",journeyTitle:"Experience becomes the next step.",saved:"SAVED",savedTitle:"Saved for later",opps:"NEXT OPPORTUNITIES",oppsTitle:"Where you can go next",next:"Next schedule",none:"Nothing scheduled",region:"Region",age:"Age group",official:"RBA confirmed",applications:"Applications",goals:"Goals",savedCount:"Saved",save:"Save",savedAction:"Saved",detail:"Details & apply",notRelevant:"Not for me",emptyJourney:"Add participation to your Passport to build your journey.",emptySaved:"Save an opportunity to return here quickly.",coachWeek:[["D-HUB","Weekly learning for the next practice.","/d-hub","Open D-HUB"],["TORSTEN LOIBL","A special session with world-level knowledge.","/events/torsten-loibl-online-clinic","See next clinic"],["COACH EDUCATION","Connect practice design, decisions, LTAD and S&C.","/coaches","Choose learning"]],playerWeek:[["PASSPORT","Review your participation and learning.","#passport-title","Open Passport"],["DISCOVER","Find the next opportunity by age and region.","/opportunities","Discover"],["MY FILM","Compare your photos and film over time.","#passport-title","Open film"]],parentWeek:[["CHILDREN","See each child’s schedule, history and next step.","#passport-title","Open records"],["APPLICATIONS","Review applications and payments.","/payments","Open payments"],["NEXT OPPORTUNITY","Find a suitable next opportunity.","/opportunities","Discover"]]},
 "zh-tw":{week:"MY WEEK",weekTitle:"本週從這裡開始。",journey:"MY JOURNEY",journeyTitle:"經驗連結下一步。",saved:"SAVED",savedTitle:"稍後查看",opps:"NEXT OPPORTUNITIES",oppsTitle:"下一個機會",next:"下一個行程",none:"尚無行程",region:"地區",age:"年齡",official:"RBA確認",applications:"申請",goals:"目標",savedCount:"收藏",save:"收藏",savedAction:"已收藏",detail:"詳情與報名",notRelevant:"這次不顯示",emptyJourney:"把參與紀錄加入Passport後，歷程會顯示在這裡。",emptySaved:"收藏感興趣的機會後，可從這裡快速返回。",coachWeek:[["D-HUB","每週學習並在下一次訓練實踐。","/zh-tw/d-hub","開啟D-HUB"],["TORSTEN LOIBL","直接接觸世界級知識的特別講座。","/zh-tw/events/torsten-loibl-online-clinic","查看講座"],["COACH EDUCATION","連結訓練設計、判斷、LTAD與S&C。","/zh-tw/coaches","選擇學習"]],playerWeek:[["PASSPORT","回顧參與與學習。","#passport-title","查看Passport"],["DISCOVER","依年齡與地區尋找機會。","/zh-tw/opportunities","尋找機會"],["MY FILM","用照片與影片比較成長。","#passport-title","開啟影片"]],parentWeek:[["CHILDREN","查看每個孩子的行程與歷程。","#passport-title","查看紀錄"],["APPLICATIONS","集中查看申請與付款。","/zh-tw/payments","查看付款"],["NEXT OPPORTUNITY","尋找適合的下一個機會。","/zh-tw/opportunities","尋找機會"]]},
 ko:{week:"MY WEEK",weekTitle:"이번 주는 여기서 시작하세요.",journey:"MY JOURNEY",journeyTitle:"경험을 다음 단계로 연결합니다.",saved:"SAVED",savedTitle:"저장한 항목",opps:"NEXT OPPORTUNITIES",oppsTitle:"다음 기회",next:"다음 일정",none:"예정된 일정이 없습니다",region:"지역",age:"연령",official:"RBA 확인",applications:"신청",goals:"목표",savedCount:"저장",save:"저장",savedAction:"저장됨",detail:"상세·신청",notRelevant:"이번에는 숨기기",emptyJourney:"Passport에 참가 기록을 남기면 여정이 여기에 쌓입니다.",emptySaved:"관심 기회를 저장하면 여기에서 바로 돌아갈 수 있습니다.",coachWeek:[["D-HUB","매주 배우고 다음 훈련에서 실천합니다.","/ko/d-hub","D-HUB 열기"],["TORSTEN LOIBL","세계 수준의 지식을 직접 만나는 특별 세션.","/ko/events/torsten-loibl-online-clinic","클리닉 보기"],["COACH EDUCATION","훈련 설계, 판단, LTAD와 S&C를 연결합니다.","/ko/coaches","학습 선택"]],playerWeek:[["PASSPORT","참가와 배움을 돌아봅니다.","#passport-title","Passport 보기"],["DISCOVER","연령과 지역으로 다음 기회를 찾습니다.","/ko/opportunities","기회 찾기"],["MY FILM","사진과 영상으로 성장을 비교합니다.","#passport-title","영상 열기"]],parentWeek:[["CHILDREN","아이별 일정, 기록과 다음 단계를 봅니다.","#passport-title","기록 보기"],["APPLICATIONS","신청과 결제를 확인합니다.","/ko/payments","결제 보기"],["NEXT OPPORTUNITY","적합한 다음 기회를 찾습니다.","/ko/opportunities","기회 찾기"]]}
} as const;
const torstenCopy={
 ja:{kicker:"WORLD CLASSROOM / 11.25",title:"世界基準を、いつものコートへ。",coach:"次の練習を変える90分。シュートフォームではなく、Spacing・Decision Making・Advantageまで含めて「良いシュートを生み出す」設計を学びます。",parent:"子どもに何を教えるかだけでなく、どんな育成環境を選ぶか。その判断材料として、世界の育成現場を知る90分です。",player:"世界のコーチがシューターをどう見て、どう育てるのか。自分のプレーを見直す新しい視点を持ち帰る90分です。",cta:"11/25 Torsten Loibl Online Clinicを見る",meta:"LIVE ¥3,300 / ON-DEMAND ¥4,400 · Zoom · 日本語逐次通訳"},
 en:{kicker:"WORLD CLASSROOM / NOV 25",title:"Bring world-level learning to your daily court.",coach:"A 90-minute session on creating better shots through spacing, decision making and advantage—not only shooting form.",parent:"Learn how world-level coaches think about development so you can better evaluate the environment around a young player.",player:"See how an international coach reads shooters, decisions and space—and bring a new lens back to your own game.",cta:"View Torsten Loibl Online Clinic",meta:"LIVE ¥3,300 / ON-DEMAND ¥4,400 · Zoom · Japanese interpretation"},
 "zh-tw":{kicker:"WORLD CLASSROOM / 11.25",title:"把世界級學習帶回日常球場。",coach:"不只談投籃動作，更從空間、判斷與優勢建立理解如何創造好出手。",parent:"透過世界級教練的觀點，理解什麼樣的培育環境更有利於孩子長期成長。",player:"了解世界級教練如何看待射手、判斷與空間，帶回新的比賽視角。",cta:"查看 Torsten Loibl Online Clinic",meta:"LIVE ¥3,300 / ON-DEMAND ¥4,400 · Zoom · 日語逐步口譯"},
 ko:{kicker:"WORLD CLASSROOM / 11.25",title:"세계 수준의 배움을 일상의 코트로.",coach:"슛 폼만이 아니라 스페이싱·판단·어드밴티지까지 연결해 좋은 슛을 만드는 과정을 배웁니다.",parent:"세계 수준의 지도 관점을 통해 아이에게 필요한 육성 환경을 보는 기준을 넓힙니다.",player:"세계 코치가 슈터와 공간, 판단을 어떻게 보는지 배우고 자신의 경기를 새롭게 봅니다.",cta:"Torsten Loibl Online Clinic 보기",meta:"LIVE ¥3,300 / ON-DEMAND ¥4,400 · Zoom · 일본어 순차통역"}
} as const;
const worldCopy={
 ja:{kicker:"WORLD VIEW",title:"自分のコートから、世界を見る。",lead:"世界を目指す必要はありません。ただ、世界を知らないまま自分の可能性を狭める必要もありません。RBAが実際につながりを持つ地域や、内容を確認できた学び・機会だけを紹介します。",notice:"予定や条件が確定していない海外企画を、募集として表示することはありません。",passport:"GLOBAL BASKETBALL PASSPORT",passportBody:"国内外のクリニック、キャンプ、オンライン講習、交流。どこで何を学び、次に何を試すかを、自分の歩みとして残します。",passportCta:"自分の歩みを残す",international:"海外交流を見る",standard:"WORLD STANDARD / RBA VIEW",standardTitle:"世界を見るための4つの視点",language:"COURT LANGUAGE",languageTitle:"世界のコートで通じる言葉",parent:"FOR PARENTS",parentTitle:"海外へ行くこと自体が目的ではありません。",parentBody:"違う文化、違う指導、違うプレースタイルに触れることで、子ども自身がより広い選択肢を持てるようになります。MY HOME COURTでは、海外も『特別な遠征』ではなく、選べる成長機会の一つとして扱います。"},
 en:{kicker:"WORLD VIEW",title:"See the world from your own court.",lead:"You do not have to chase the world. But you do not have to define your potential without seeing it either. RBA connects only real relationships, verified learning and confirmed opportunities.",notice:"Unconfirmed international plans are never shown as open opportunities.",passport:"GLOBAL BASKETBALL PASSPORT",passportBody:"Clinics, camps, online learning and exchange—record where you learned, what changed and what comes next.",passportCta:"Open your journey",international:"Explore international",standard:"WORLD STANDARD / RBA VIEW",standardTitle:"Four lenses for seeing the game",language:"COURT LANGUAGE",languageTitle:"Words that travel with you",parent:"FOR PARENTS",parentTitle:"Going abroad is not the goal.",parentBody:"Seeing different cultures, coaching and styles can keep a young player from narrowing their own possibilities too early. International experiences are treated as one development option, not a status symbol."},
 "zh-tw":{kicker:"WORLD VIEW",title:"從自己的球場，看見世界。",lead:"不一定要以世界為目標，但也不必在還沒看見世界之前就決定自己的可能性。RBA只連結實際合作、已確認的學習與機會。",notice:"尚未確定的海外企劃不會以公開招募顯示。",passport:"GLOBAL BASKETBALL PASSPORT",passportBody:"把國內外訓練營、線上學習與交流，整理成自己的成長軌跡。",passportCta:"查看成長軌跡",international:"查看國際交流",standard:"WORLD STANDARD / RBA VIEW",standardTitle:"看世界比賽的四個視角",language:"COURT LANGUAGE",languageTitle:"世界球場都能用的語言",parent:"FOR PARENTS",parentTitle:"出國本身不是目的。",parentBody:"接觸不同文化、教練與打法，能避免孩子過早限制自己的可能性。海外只是成長選項之一。"},
 ko:{kicker:"WORLD VIEW",title:"내 코트에서 세계를 봅니다.",lead:"세계를 목표로 할 필요는 없습니다. 하지만 세계를 보기도 전에 가능성을 정할 필요도 없습니다. RBA는 실제 연결과 확인된 배움, 확정된 기회만 이어갑니다.",notice:"확정되지 않은 해외 프로그램은 모집 중인 기회로 표시하지 않습니다.",passport:"GLOBAL BASKETBALL PASSPORT",passportBody:"국내외 클리닉, 캠프, 온라인 학습과 교류를 자신의 성장 여정으로 남깁니다.",passportCta:"성장 여정 보기",international:"국제 교류 보기",standard:"WORLD STANDARD / RBA VIEW",standardTitle:"경기를 보는 네 가지 관점",language:"COURT LANGUAGE",languageTitle:"세계 코트에서 통하는 말",parent:"FOR PARENTS",parentTitle:"해외에 가는 것 자체가 목적은 아닙니다.",parentBody:"다른 문화, 지도 방식과 플레이를 아는 경험은 아이가 가능성을 너무 일찍 좁히지 않게 합니다. 해외 경험도 성장 선택지 중 하나입니다."}
} as const;
const worldStandards={ja:[["SEE","状況を見る","ボールだけでなく、味方・相手・スペースを見る。"],["DECIDE","自分で決める","正解を待つのではなく、状況から選ぶ。"],["CONNECT","仲間とつながる","パス、スペーシング、声、タイミングで5人をつなぐ。"],["ADAPT","変化に適応する","相手や環境が変わっても、自分で解決策を探す。"]],en:[["SEE","Read the game","See teammates, opponents and space—not only the ball."],["DECIDE","Make decisions","Choose from the situation instead of waiting for answers."],["CONNECT","Play with others","Connect five players through space, timing and communication."],["ADAPT","Adapt","Find solutions when opponents and environments change."]],"zh-tw":[["SEE","閱讀比賽","不只看球，也看隊友、對手與空間。"],["DECIDE","自己決定","從情境中做選擇，而不是等待答案。"],["CONNECT","與隊友連結","用空間、時機與溝通連結五個人。"],["ADAPT","適應變化","面對不同對手與環境時自己找出解法。"]],ko:[["SEE","경기를 읽기","공만 보지 않고 동료, 상대, 공간을 봅니다."],["DECIDE","스스로 결정","답을 기다리지 않고 상황에서 선택합니다."],["CONNECT","동료와 연결","공간, 타이밍, 소통으로 다섯 명을 연결합니다."],["ADAPT","변화에 적응","상대와 환경이 달라져도 해결책을 찾습니다."]]} as const;
const worldPath={ja:[["YOUR COURT","日常のコート","毎日の練習を通して、今の自分を知る。"],["NEXT COURT","全国のコート","いつもと違う地域・相手・環境で試す。"],["WORLD COURT","世界のコート","アジアや世界の育成・文化・考え方に触れる。"]],en:[["YOUR COURT","Your daily court","Practice and understand where you are now."],["NEXT COURT","Courts across Japan","Test yourself with different people and environments."],["WORLD COURT","Courts around the world","Meet different cultures, coaching and ways of playing."]],"zh-tw":[["YOUR COURT","日常球場","從每天的訓練了解現在的自己。"],["NEXT COURT","日本各地","在不同地區、對手與環境中嘗試。"],["WORLD COURT","世界球場","接觸亞洲與世界不同的培育與籃球文化。"]],ko:[["YOUR COURT","일상의 코트","매일의 훈련에서 현재 위치를 압니다."],["NEXT COURT","일본의 다양한 코트","다른 지역과 상대, 환경에서 도전합니다."],["WORLD COURT","세계의 코트","아시아와 세계의 다른 육성 방식과 문화를 만납니다."]]} as const;
const courtLanguage={ja:[["SCAN","見る・確認する"],["SPACE","間隔を取る"],["ONE MORE","もう1本パスをつなぐ"],["SWITCH","守る相手を入れ替える"],["HELP","ヘルプに入る"],["NEXT PLAY","次のプレーへ切り替える"]],en:[["SCAN","Check the floor"],["SPACE","Create spacing"],["ONE MORE","Move it one more"],["SWITCH","Exchange matchups"],["HELP","Support a teammate"],["NEXT PLAY","Move on immediately"]],"zh-tw":[["SCAN","先觀察"],["SPACE","拉開空間"],["ONE MORE","再多傳一次"],["SWITCH","換防"],["HELP","協防"],["NEXT PLAY","立刻進入下一球"]],ko:[["SCAN","코트 확인"],["SPACE","간격 만들기"],["ONE MORE","한 번 더 연결"],["SWITCH","수비 전환"],["HELP","도움 수비"],["NEXT PLAY","다음 플레이로 전환"]]} as const;

const todayJst=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Tokyo",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
const localeIndex=(locale:Locale)=>locale==="en"?0:locale==="ja"?1:locale==="zh-tw"?2:3;
function ageGroup(birthYear:number|null){if(!birthYear)return null;const age=new Date().getFullYear()-birthYear;return age<=8?"U8":age<=10?"U10":age<=12?"U12":age<=15?"U15":age<=18?"U18":"ADULT";}
export function HomecourtOverview(props:Props){
 const {locale,userId,role,displayName,region,birthYear,nextEvent}=props;const c=tx[locale];const db=useMemo(()=>createClient(),[]);const [data,setData]=useState(empty);const [busy,setBusy]=useState("");const [saveError,setSaveError]=useState("");const age=ageGroup(birthYear);const actualRole=role==="admin"?"coach":role;
 const load=useCallback(async()=>{const results=await Promise.allSettled([
  db.from("participations").select("id,events(title,starts_at)").eq("player_user_id",userId).eq("attendance_status","attended").order("joined_at",{ascending:false}).limit(20),
  db.from("program_applications").select("id",{count:"exact",head:true}).or(`applicant_user_id.eq.${userId},subject_user_id.eq.${userId}`),
  db.from("homecourt_goals").select("id",{count:"exact",head:true}).eq("user_id",userId).eq("status","active"),
  db.from("homecourt_people").select("id",{count:"exact",head:true}).eq("user_id",userId).eq("relationship","child"),
  db.from("homecourt_saves").select("id,item_key,title,href").eq("user_id",userId).order("created_at",{ascending:false}),
  db.from("homecourt_history").select("id,title,occurred_on").eq("user_id",userId).order("occurred_on",{ascending:false}).limit(20),
  db.from("recommendation_feedback").select("item_key").eq("user_id",userId).eq("item_type","opportunity").eq("signal","not_relevant"),
  db.from("player_development_profiles").select("opportunity_types").eq("user_id",userId).maybeSingle()
 ]);const value=<T,>(i:number,fallback:T)=>results[i].status==="fulfilled"?(results[i] as PromiseFulfilledResult<{data?:unknown;count?:number|null}>).value:fallback as unknown as {data?:unknown;count?:number|null};
 const p=value(0,{data:[]}),a=value(1,{count:0}),g=value(2,{count:0}),ch=value(3,{count:0}),s=value(4,{data:[]}),h=value(5,{data:[]}),rf=value(6,{data:[]}),dp=value(7,{data:null});
 const official=((p.data||[]) as {id:string;events:{title:string;starts_at:string}|null}[]).map(x=>({id:x.id,title:x.events?.title||"RBA",date:x.events?.starts_at||"",kind:"RBA" as const}));
 const self=((h.data||[]) as {id:string;title:string;occurred_on:string}[]).map(x=>({id:x.id,title:x.title,date:x.occurred_on,kind:"SELF" as const}));
 setData({official:official.length,applications:a.count||0,goals:g.count||0,children:ch.count||0,saved:(s.data||[]) as Saved[],journey:[...official,...self].filter(x=>x.date).sort((x,y)=>y.date.localeCompare(x.date)).slice(0,8),notRelevant:((rf.data||[]) as {item_key:string}[]).map(x=>x.item_key),opportunityTypes:((dp.data as {opportunity_types?:string[]}|null)?.opportunity_types||[])});
 },[db,userId]);
 useEffect(()=>{const timer=window.setTimeout(()=>{void load();void db.from("analytics_events").insert([{user_id:userId,event_name:"home_view",role,locale,item_type:"homecourt",item_key:"home"},{user_id:userId,event_name:"return_visit",role,locale,item_type:"homecourt",item_key:"home"}]);},0);return()=>window.clearTimeout(timer);},[db,load,locale,role,userId]);
 const recommendations=useMemo(()=>{const open=programmes.filter(p=>!p.registrationClosed&&p.startDate>=todayJst&&!data.notRelevant.includes(p.id));if(actualRole==="coach")return open.filter(p=>p.category==="COACH").slice(0,2);const matching=age?open.filter(p=>p.ageGroups.includes(age as never)):open.filter(p=>p.category!=="COACH");const pool=[...(matching.length?matching:open)];const score=(p:Programme)=>{const key=p.region==="online"?"online":p.category==="TRAIN"?"clinic":p.category==="TRAVEL"?"camp":p.category==="PLAY"?"game":p.category==="COACH"?"coach":"";return data.opportunityTypes.includes(key)?2:0};return pool.sort((x,y)=>score(y)-score(x)||x.startDate.localeCompare(y.startDate)).slice(0,4);},[actualRole,age,data.notRelevant,data.opportunityTypes]);
 const closingSoon=(startDate:string)=>{const days=(Date.parse(`${startDate}T00:00:00+09:00`)-Date.parse(`${todayJst}T00:00:00+09:00`))/86400000;return days>=0&&days<=21;};
 const closingLabel=({ja:"開催が近い活動",en:"COMING UP","zh-tw":"即將舉行",ko:"곧 개최"})[locale];
 async function hideRecommendation(p:Programme){
  if(busy)return;setBusy(p.id);setSaveError("");
  try{const {error}=await db.from("recommendation_feedback").upsert({user_id:userId,item_type:"opportunity",item_key:p.id,signal:"not_relevant",metadata:{source:"homecourt"}},{onConflict:"user_id,item_type,item_key,signal"});if(error)throw error;await load();}
  catch{setSaveError(locale==="ja"?"表示を更新できませんでした。通信状態を確認して、もう一度お試しください。":"Could not update this activity. Please try again.");}
  finally{setBusy("");}
 }
 async function toggle(p:Programme){
  if(busy)return;setBusy(p.id);setSaveError("");
  const found=data.saved.find(x=>x.item_key===p.id);
  try{
   const result=found
    ?await db.from("homecourt_saves").delete().eq("user_id",userId).eq("id",found.id).select("id").maybeSingle()
    :await db.from("homecourt_saves").insert({user_id:userId,item_type:p.category==="COACH"?"session":"opportunity",item_key:p.id,title:p.title[localeIndex(locale)],href:p.detailPath?`${locale==="en"?"":`/${locale}`}/${p.detailPath}`:p.applicationUrl,metadata:{category:p.category,region:p.region,start_date:p.startDate}}).select("id").single();
   if(result.error||!result.data)throw result.error||new Error("save_change_not_confirmed");
   await load();
   void db.from("analytics_events").insert({user_id:userId,event_name:found?"opportunity_unsave":"opportunity_save",item_type:"opportunity",item_key:p.id,role,locale});
  }catch{setSaveError(locale==="ja"?"保存状態を更新できませんでした。通信状態を確認して、もう一度お試しください。":"Could not update your saved activities. Please try again.");}
  finally{setBusy("");}
 }
 const week=actualRole==="coach"?c.coachWeek:actualRole==="parent"?c.parentWeek:c.playerWeek;const dateLocale=locale==="zh-tw"?"zh-TW":locale;const lp=locale==="en"?"":"/"+locale;
 const position=actualRole==="coach" ? (data.official+data.applications===0 ? {label:"LEARN",title:"学びの入口",body:"D-HUB・Torsten・指導者向け記事から、今必要なテーマを一つ選びます。",href:lp+"/my-homecourt/coaches"} : data.saved.length===0 ? {label:"CONNECT",title:"学びをつなぐ",body:"参加した講習と、次に読む教材・試す練習をつなぎます。",href:lp+"/d-hub"} : {label:"APPLY",title:"現場で試す",body:"保存した学びを次の練習へ。振り返って、次の学びを選びます。",href:lp+"/events/torsten-loibl-online-clinic"}) : (data.journey.length===0 ? {label:"START",title:"最初の1件を残す",body:"過去のRBA参加や最近の経験をPassportに記録すると、これまでの歩みと次に取り組むことが整理できます。",href:lp+"/my-homecourt/participants"} : nextEvent ? {label:"NOW",title:"次の予定があります",body:"これまでの経験を振り返り、次の参加で試すことを一つ決めましょう。",href:"#passport-title"} : data.saved.length>0 ? {label:"CHOOSE",title:"次の機会を選ぶ",body:"保存した機会を見比べて、今の年代・地域・目的に合う次の一歩を選びます。",href:lp+"/opportunities"} : {label:"DISCOVER",title:"次の機会を探す",body:"参加履歴を起点に、次のクリニック・キャンプ・学びを探します。",href:lp+"/opportunities"});
 return <section className={styles.shell} aria-label="MY HOME COURT overview"><header className={styles.hero}><p className={styles.eyebrow}>MY HOME COURT / {actualRole.toUpperCase()}</p><div className={styles.heroGrid}><div><h2>{displayName}</h2><div className={styles.profile}><span>{actualRole.toUpperCase()}</span>{age&&<span>{c.age} · {age}</span>}<span>{c.region} · {region||"—"}</span></div></div><div className={styles.next}><span>{c.next}</span><strong>{nextEvent?.title||c.none}</strong>{nextEvent&&<small>{new Date(nextEvent.starts_at).toLocaleString(dateLocale,{month:"short",day:"numeric",hour:"2-digit",minute:"2-digit",timeZone:"Asia/Tokyo"})} · {nextEvent.venue||"—"}</small>}</div></div></header>
 <div className={styles.position}><div><span>YOUR POSITION</span><strong>{position.label}</strong><h3>{position.title}</h3><p>{position.body}</p></div><a href={position.href}>次に取り組むことを見る →</a><small>これは能力評価やランキングではありません。参加・学び・次の行動を整理するための目安です。</small></div>
 <div className={styles.worldIntro}><p>{torstenCopy[locale].kicker}</p><h3>{torstenCopy[locale].title}</h3><span>{actualRole==="coach"?torstenCopy[locale].coach:actualRole==="parent"?torstenCopy[locale].parent:torstenCopy[locale].player}</span><small>{torstenCopy[locale].meta}</small><div className={styles.worldLinks}><a href={`${locale==="en"?"":`/${locale}`}/events/torsten-loibl-online-clinic`} onClick={()=>void db.from("analytics_events").insert({user_id:userId,event_name:"home_torsten_click",item_type:"clinic",item_key:"torsten-vol2",role,locale})}>{torstenCopy[locale].cta} →</a><a href={`mailto:?subject=${encodeURIComponent("Torsten Loibl Online Clinic｜Riot Basketball Academy")}&body=${encodeURIComponent("11/25開催のTorsten Loibl Online Clinicです。育成年代のシュートを、フォームだけでなくSpacing・Decision Making・Advantageまで含めて考える内容です。\n\nhttps://riotbasketballacademy.com/ja/events/torsten-loibl-online-clinic")}`} onClick={()=>void db.from("analytics_events").insert({user_id:userId,event_name:"home_torsten_share",item_type:"clinic",item_key:"torsten-vol2",role,locale})}>{locale==="ja"?"指導者・保護者に共有する":locale==="ko"?"코치·보호자에게 공유":locale==="zh-tw"?"分享給教練・家長":"Share with a coach or parent"} →</a><a href={`${locale==="en"?"":`/${locale}`}/d-hub`}>{locale==="ja"?"関連する学びをD-HUBで見る":locale==="ko"?"D-HUB 관련 학습 보기":locale==="zh-tw"?"在D-HUB查看相關學習":"Continue in D-HUB"} →</a></div></div>
 <div className={styles.section}><div className={styles.sectionHead}><div><p>{c.week}</p><h3>{c.weekTitle}</h3></div></div><div className={styles.week}>{week.map(([tag,body,href,label],i)=><article className={`${styles.card} ${actualRole==="coach"&&i<2?styles.coach:""}`} key={tag}><span>{tag}</span><h4>{tag==="CHILDREN"&&data.children?`${data.children} CHILDREN`:tag}</h4><p>{body}</p><a href={href}>{label}<b>→</b></a></article>)}</div></div>
 <div className={styles.section}><div className={styles.metrics}><article className={styles.metric}><span>{c.official}</span><strong>{data.official}</strong></article><article className={styles.metric}><span>{c.applications}</span><strong>{data.applications}</strong></article><article className={styles.metric}><span>{c.goals}</span><strong>{data.goals}</strong></article><article className={styles.metric}><span>{c.savedCount}</span><strong>{data.saved.length}</strong></article></div></div>
 <div className={styles.section}><div className={styles.sectionHead}><div><p>{c.journey}</p><h3>{c.journeyTitle}</h3></div></div>{data.journey.length?<div className={styles.journey}>{data.journey.map(item=><article key={`${item.kind}-${item.id}`}><time>{new Date(`${item.date.slice(0,10)}T12:00:00+09:00`).toLocaleDateString(dateLocale,{year:"numeric",month:"short",day:"numeric"})} · {item.kind}</time><h4>{item.title}</h4></article>)}</div>:<p className={styles.empty}>{c.emptyJourney}</p>}</div>
 <div className={styles.worldSection}><div className={styles.worldIntro}><p>{worldCopy[locale].kicker}</p><h3>{worldCopy[locale].title}</h3><span>{worldCopy[locale].lead}</span><small>{worldCopy[locale].notice}</small><div className={styles.worldLinks}><a href={`${locale==="en"?"":`/${locale}`}/international`}>{worldCopy[locale].international} →</a><a href="#passport-title">{worldCopy[locale].passportCta} →</a></div></div><div className={styles.worldPassport}><span>{worldCopy[locale].passport}</span><strong>YOUR COURT → NEXT COURT → WORLD COURT</strong><p>{worldCopy[locale].passportBody}</p><div className={styles.worldPath}>{worldPath[locale].map(([tag,title,body],i)=><article key={tag}><small>0{i+1}</small><b>{tag}</b><strong>{title}</strong><span>{body}</span></article>)}</div></div><div className={styles.worldGrid}><section><p>{worldCopy[locale].standard}</p><h4>{worldCopy[locale].standardTitle}</h4>{worldStandards[locale].map(([tag,title,body])=><article key={tag}><b>{tag}</b><div><strong>{title}</strong><span>{body}</span></div></article>)}</section><section><p>{worldCopy[locale].language}</p><h4>{worldCopy[locale].languageTitle}</h4><div className={styles.languageGrid}>{courtLanguage[locale].map(([word,meaning])=><div key={word}><b>{word}</b><span>{meaning}</span></div>)}</div></section></div><div className={styles.parentWorld}><p>{worldCopy[locale].parent}</p><strong>{worldCopy[locale].parentTitle}</strong><span>{worldCopy[locale].parentBody}</span></div></div>
 {saveError&&<p role="alert" className={styles.empty}>{saveError}</p>}
 {locale==="ja"?<HomecourtDiscovery role={actualRole} savedKeys={data.saved.map(x=>x.item_key)} busy={!!busy} onSave={toggle}/>:<div className={styles.section}><div className={styles.sectionHead}><div><p>{c.opps}</p><h3>{c.oppsTitle}</h3></div></div><div className={styles.opportunities}>{recommendations.map(p=>{const saved=data.saved.some(x=>x.item_key===p.id);const href=p.detailPath?`${locale==="en"?"":`/${locale}`}/${p.detailPath}`:p.applicationUrl;return <article className={styles.opportunity} key={p.id}><span>{closingSoon(p.startDate)?`${closingLabel} · `:""}{p.category} · {p.date[localeIndex(locale)]}</span><h4>{p.title[localeIndex(locale)]}</h4><p>{p.place[localeIndex(locale)]}</p><p>{p.audience[localeIndex(locale)]}</p><div className={styles.actions}><a href={href} target={p.detailPath?undefined:"_blank"} rel={p.detailPath?undefined:"noreferrer"} onClick={()=>void db.from("analytics_events").insert({user_id:userId,event_name:"apply_open",item_type:"opportunity",item_key:p.id,role,locale})}>{c.detail}</a><button disabled={!!busy} aria-pressed={saved} onClick={()=>void toggle(p)}>{saved?c.savedAction:c.save}</button><button className={styles.dismiss} disabled={!!busy} onClick={()=>void hideRecommendation(p)}>{c.notRelevant}</button></div></article>})}</div></div>}
 <div className={styles.section}><div className={styles.sectionHead}><div><p>{c.saved}</p><h3>{c.savedTitle}</h3></div></div>{data.saved.length?<div className={styles.savedList}>{data.saved.map(x=><a key={x.id} href={x.href}>{x.title} →</a>)}</div>:<p className={styles.empty}>{c.emptySaved}</p>}</div><p className={styles.notice}><strong>NEXT STEP</strong><span>{actualRole==="coach"?`${programmeById.torsten.title[localeIndex(locale)]} → D-HUB → court practice`:"RBA ID → Passport → Next Opportunity"}</span></p></section>;
}
