"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase/client";
import {programmeById,programmes,type Programme} from "./programme-data";
import type {Locale} from "./site-frame";
import styles from "./homecourt-overview.module.css";

type Props={locale:Locale;userId:string;role:"player"|"parent"|"coach"|"admin";displayName:string;region:string|null;birthYear:number|null;nextEvent:{title:string;starts_at:string;venue:string|null}|null};
type Saved={id:string;item_key:string;title:string;href:string};
type Journey={id:string;title:string;date:string;kind:"RBA"|"SELF"};
type Snapshot={official:number;applications:number;goals:number;children:number;saved:Saved[];journey:Journey[]};
const empty:Snapshot={official:0,applications:0,goals:0,children:0,saved:[],journey:[]};
const tx={
 ja:{week:"MY WEEK",weekTitle:"今週、ここから。",journey:"MY JOURNEY",journeyTitle:"経験が、次の一歩になる。",saved:"SAVED",savedTitle:"あとで見る",opps:"NEXT OPPORTUNITIES",oppsTitle:"次に進める機会",next:"次の予定",none:"まだ予定はありません",region:"登録地域",age:"年代",official:"RBA確認済み",applications:"申込中・申込履歴",goals:"目標",savedCount:"保存",save:"保存",savedAction:"保存済み",detail:"詳細・申込",emptyJourney:"Passportに参加履歴を残すと、ここに歩みが積み上がります。",emptySaved:"気になる機会を保存すると、ここからすぐに戻れます。",coachWeek:[["D-HUB","毎週の学びを、次の練習で試す。","/ja/d-hub","今週の学びを開く"],["TORSTEN LOIBL","世界基準の知見に直接触れるSpecial Session。","/ja/events/torsten-loibl-online-clinic","次回講習を見る"],["COACH EDUCATION","練習設計、意思決定、LTAD、S&Cをつなぐ。","/ja/coaches","学びを選ぶ"]],playerWeek:[["PASSPORT","これまでの参加と気づきを振り返る。","#passport-title","歩みを見る"],["DISCOVER","年代と地域から、次の機会を探す。","/ja/opportunities","機会を探す"],["MY FILM","写真と動画で前の自分と見比べる。","#passport-title","成長ノートを開く"]],parentWeek:[["CHILDREN","子どもごとの予定・履歴・次の機会を確認。","#passport-title","子どもの記録を見る"],["APPLICATIONS","申込と支払い状況をまとめて確認。","/ja/payments","申込・決済を見る"],["NEXT OPPORTUNITY","年代と地域に合う次の機会を探す。","/ja/opportunities","機会を探す"]]},
 en:{week:"MY WEEK",weekTitle:"Start here this week.",journey:"MY JOURNEY",journeyTitle:"Experience becomes the next step.",saved:"SAVED",savedTitle:"Saved for later",opps:"NEXT OPPORTUNITIES",oppsTitle:"Where you can go next",next:"Next schedule",none:"Nothing scheduled",region:"Region",age:"Age group",official:"RBA confirmed",applications:"Applications",goals:"Goals",savedCount:"Saved",save:"Save",savedAction:"Saved",detail:"Details & apply",emptyJourney:"Add participation to your Passport to build your journey.",emptySaved:"Save an opportunity to return here quickly.",coachWeek:[["D-HUB","Weekly learning for the next practice.","/d-hub","Open D-HUB"],["TORSTEN LOIBL","A special session with world-level knowledge.","/events/torsten-loibl-online-clinic","See next clinic"],["COACH EDUCATION","Connect practice design, decisions, LTAD and S&C.","/coaches","Choose learning"]],playerWeek:[["PASSPORT","Review your participation and learning.","#passport-title","Open Passport"],["DISCOVER","Find the next opportunity by age and region.","/opportunities","Discover"],["MY FILM","Compare your photos and film over time.","#passport-title","Open film"]],parentWeek:[["CHILDREN","See each child’s schedule, history and next step.","#passport-title","Open records"],["APPLICATIONS","Review applications and payments.","/payments","Open payments"],["NEXT OPPORTUNITY","Find a suitable next opportunity.","/opportunities","Discover"]]},
 "zh-tw":{week:"MY WEEK",weekTitle:"本週從這裡開始。",journey:"MY JOURNEY",journeyTitle:"經驗連結下一步。",saved:"SAVED",savedTitle:"稍後查看",opps:"NEXT OPPORTUNITIES",oppsTitle:"下一個機會",next:"下一個行程",none:"尚無行程",region:"地區",age:"年齡",official:"RBA確認",applications:"申請",goals:"目標",savedCount:"收藏",save:"收藏",savedAction:"已收藏",detail:"詳情與報名",emptyJourney:"把參與紀錄加入Passport後，歷程會顯示在這裡。",emptySaved:"收藏感興趣的機會後，可從這裡快速返回。",coachWeek:[["D-HUB","每週學習並在下一次訓練實踐。","/zh-tw/d-hub","開啟D-HUB"],["TORSTEN LOIBL","直接接觸世界級知識的特別講座。","/zh-tw/events/torsten-loibl-online-clinic","查看講座"],["COACH EDUCATION","連結訓練設計、判斷、LTAD與S&C。","/zh-tw/coaches","選擇學習"]],playerWeek:[["PASSPORT","回顧參與與學習。","#passport-title","查看Passport"],["DISCOVER","依年齡與地區尋找機會。","/zh-tw/opportunities","尋找機會"],["MY FILM","用照片與影片比較成長。","#passport-title","開啟影片"]],parentWeek:[["CHILDREN","查看每個孩子的行程與歷程。","#passport-title","查看紀錄"],["APPLICATIONS","集中查看申請與付款。","/zh-tw/payments","查看付款"],["NEXT OPPORTUNITY","尋找適合的下一個機會。","/zh-tw/opportunities","尋找機會"]]},
 ko:{week:"MY WEEK",weekTitle:"이번 주는 여기서 시작하세요.",journey:"MY JOURNEY",journeyTitle:"경험을 다음 단계로 연결합니다.",saved:"SAVED",savedTitle:"저장한 항목",opps:"NEXT OPPORTUNITIES",oppsTitle:"다음 기회",next:"다음 일정",none:"예정된 일정이 없습니다",region:"지역",age:"연령",official:"RBA 확인",applications:"신청",goals:"목표",savedCount:"저장",save:"저장",savedAction:"저장됨",detail:"상세·신청",emptyJourney:"Passport에 참가 기록을 남기면 여정이 여기에 쌓입니다.",emptySaved:"관심 기회를 저장하면 여기에서 바로 돌아갈 수 있습니다.",coachWeek:[["D-HUB","매주 배우고 다음 훈련에서 실천합니다.","/ko/d-hub","D-HUB 열기"],["TORSTEN LOIBL","세계 수준의 지식을 직접 만나는 특별 세션.","/ko/events/torsten-loibl-online-clinic","클리닉 보기"],["COACH EDUCATION","훈련 설계, 판단, LTAD와 S&C를 연결합니다.","/ko/coaches","학습 선택"]],playerWeek:[["PASSPORT","참가와 배움을 돌아봅니다.","#passport-title","Passport 보기"],["DISCOVER","연령과 지역으로 다음 기회를 찾습니다.","/ko/opportunities","기회 찾기"],["MY FILM","사진과 영상으로 성장을 비교합니다.","#passport-title","영상 열기"]],parentWeek:[["CHILDREN","아이별 일정, 기록과 다음 단계를 봅니다.","#passport-title","기록 보기"],["APPLICATIONS","신청과 결제를 확인합니다.","/ko/payments","결제 보기"],["NEXT OPPORTUNITY","적합한 다음 기회를 찾습니다.","/ko/opportunities","기회 찾기"]]}
} as const;
const todayJst=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Tokyo",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
const localeIndex=(locale:Locale)=>locale==="en"?0:locale==="ja"?1:locale==="zh-tw"?2:3;
function ageGroup(birthYear:number|null){if(!birthYear)return null;const age=new Date().getFullYear()-birthYear;return age<=8?"U8":age<=10?"U10":age<=12?"U12":age<=15?"U15":age<=18?"U18":"ADULT";}
export function HomecourtOverview(props:Props){
 const {locale,userId,role,displayName,region,birthYear,nextEvent}=props;const c=tx[locale];const db=useMemo(()=>createClient(),[]);const [data,setData]=useState(empty);const [busy,setBusy]=useState("");const age=ageGroup(birthYear);const actualRole=role==="admin"?"coach":role;
 const load=useCallback(async()=>{const results=await Promise.allSettled([
  db.from("participations").select("id,events(title,starts_at)").eq("player_user_id",userId).eq("attendance_status","attended").order("joined_at",{ascending:false}).limit(20),
  db.from("program_applications").select("id",{count:"exact",head:true}).or(`applicant_user_id.eq.${userId},subject_user_id.eq.${userId}`),
  db.from("homecourt_goals").select("id",{count:"exact",head:true}).eq("user_id",userId).eq("status","active"),
  db.from("homecourt_people").select("id",{count:"exact",head:true}).eq("user_id",userId).eq("relationship","child"),
  db.from("homecourt_saves").select("id,item_key,title,href").eq("user_id",userId).order("created_at",{ascending:false}),
  db.from("homecourt_history").select("id,title,occurred_on").eq("user_id",userId).order("occurred_on",{ascending:false}).limit(20)
 ]);const value=<T,>(i:number,fallback:T)=>results[i].status==="fulfilled"?(results[i] as PromiseFulfilledResult<{data?:unknown;count?:number|null}>).value:fallback as unknown as {data?:unknown;count?:number|null};
 const p=value(0,{data:[]}),a=value(1,{count:0}),g=value(2,{count:0}),ch=value(3,{count:0}),s=value(4,{data:[]}),h=value(5,{data:[]});
 const official=((p.data||[]) as {id:string;events:{title:string;starts_at:string}|null}[]).map(x=>({id:x.id,title:x.events?.title||"RBA",date:x.events?.starts_at||"",kind:"RBA" as const}));
 const self=((h.data||[]) as {id:string;title:string;occurred_on:string}[]).map(x=>({id:x.id,title:x.title,date:x.occurred_on,kind:"SELF" as const}));
 setData({official:official.length,applications:a.count||0,goals:g.count||0,children:ch.count||0,saved:(s.data||[]) as Saved[],journey:[...official,...self].filter(x=>x.date).sort((x,y)=>y.date.localeCompare(x.date)).slice(0,8)});
 },[db,userId]);
 useEffect(()=>{const timer=window.setTimeout(()=>{void load();void db.from("analytics_events").insert({user_id:userId,event_name:"return_visit",role,locale,item_type:"homecourt",item_key:"home"});},0);return()=>window.clearTimeout(timer);},[db,load,locale,role,userId]);
 const recommendations=useMemo(()=>{const open=programmes.filter(p=>!p.registrationClosed&&p.startDate>=todayJst);if(actualRole==="coach")return open.filter(p=>p.category==="COACH").slice(0,2);const matching=age?open.filter(p=>p.ageGroups.includes(age as never)):open.filter(p=>p.category!=="COACH");return (matching.length?matching:open).slice(0,4);},[actualRole,age]);
 const closingSoon=(startDate:string)=>{const days=(Date.parse(`${startDate}T00:00:00+09:00`)-Date.parse(`${todayJst}T00:00:00+09:00`))/86400000;return days>=0&&days<=21;};
 const closingLabel=({ja:"締切間近",en:"CLOSING SOON","zh-tw":"即將截止",ko:"마감 임박"})[locale];
 async function toggle(p:Programme){setBusy(p.id);const found=data.saved.find(x=>x.item_key===p.id);if(found)await db.from("homecourt_saves").delete().eq("user_id",userId).eq("id",found.id);else await db.from("homecourt_saves").insert({user_id:userId,item_type:p.category==="COACH"?"session":"opportunity",item_key:p.id,title:p.title[localeIndex(locale)],href:p.detailPath?`${locale==="en"?"":`/${locale}`}/${p.detailPath}`:p.applicationUrl,metadata:{category:p.category,region:p.region,start_date:p.startDate}});await db.from("analytics_events").insert({user_id:userId,event_name:found?"unsave":"save",item_type:"opportunity",item_key:p.id,role,locale});await load();setBusy("");}
 const week=actualRole==="coach"?c.coachWeek:actualRole==="parent"?c.parentWeek:c.playerWeek;const dateLocale=locale==="zh-tw"?"zh-TW":locale;
 return <section className={styles.shell} aria-label="MY HOME COURT overview"><header className={styles.hero}><p className={styles.eyebrow}>MY HOME COURT / {actualRole.toUpperCase()}</p><div className={styles.heroGrid}><div><h2>{displayName}</h2><div className={styles.profile}><span>{actualRole.toUpperCase()}</span>{age&&<span>{c.age} · {age}</span>}<span>{c.region} · {region||"—"}</span></div></div><div className={styles.next}><span>{c.next}</span><strong>{nextEvent?.title||c.none}</strong>{nextEvent&&<small>{new Date(nextEvent.starts_at).toLocaleString(dateLocale,{month:"short",day:"numeric",hour:"2-digit",minute:"2-digit",timeZone:"Asia/Tokyo"})} · {nextEvent.venue||"—"}</small>}</div></div></header>
 <div className={styles.section}><div className={styles.sectionHead}><div><p>{c.week}</p><h3>{c.weekTitle}</h3></div></div><div className={styles.week}>{week.map(([tag,body,href,label],i)=><article className={`${styles.card} ${actualRole==="coach"&&i<2?styles.coach:""}`} key={tag}><span>{tag}</span><h4>{tag==="CHILDREN"&&data.children?`${data.children} CHILDREN`:tag}</h4><p>{body}</p><a href={href}>{label}<b>→</b></a></article>)}</div></div>
 <div className={styles.section}><div className={styles.metrics}><article className={styles.metric}><span>{c.official}</span><strong>{data.official}</strong></article><article className={styles.metric}><span>{c.applications}</span><strong>{data.applications}</strong></article><article className={styles.metric}><span>{c.goals}</span><strong>{data.goals}</strong></article><article className={styles.metric}><span>{c.savedCount}</span><strong>{data.saved.length}</strong></article></div></div>
 <div className={styles.section}><div className={styles.sectionHead}><div><p>{c.journey}</p><h3>{c.journeyTitle}</h3></div></div>{data.journey.length?<div className={styles.journey}>{data.journey.map(item=><article key={`${item.kind}-${item.id}`}><time>{new Date(`${item.date.slice(0,10)}T12:00:00+09:00`).toLocaleDateString(dateLocale,{year:"numeric",month:"short",day:"numeric"})} · {item.kind}</time><h4>{item.title}</h4></article>)}</div>:<p className={styles.empty}>{c.emptyJourney}</p>}</div>
 <div className={styles.section}><div className={styles.sectionHead}><div><p>{c.opps}</p><h3>{c.oppsTitle}</h3></div></div><div className={styles.opportunities}>{recommendations.map(p=>{const saved=data.saved.some(x=>x.item_key===p.id);const href=p.detailPath?`${locale==="en"?"":`/${locale}`}/${p.detailPath}`:p.applicationUrl;return <article className={styles.opportunity} key={p.id}><span>{closingSoon(p.startDate)?`${closingLabel} · `:""}{p.category} · {p.date[localeIndex(locale)]}</span><h4>{p.title[localeIndex(locale)]}</h4><p>{p.place[localeIndex(locale)]}</p><p>{p.audience[localeIndex(locale)]}</p><div className={styles.actions}><a href={href} target={p.detailPath?undefined:"_blank"} rel={p.detailPath?undefined:"noreferrer"} onClick={()=>void db.from("analytics_events").insert({user_id:userId,event_name:"apply_open",item_type:"opportunity",item_key:p.id,role,locale})}>{c.detail}</a><button disabled={busy===p.id} aria-pressed={saved} onClick={()=>void toggle(p)}>{saved?c.savedAction:c.save}</button></div></article>})}</div></div>
 <div className={styles.section}><div className={styles.sectionHead}><div><p>{c.saved}</p><h3>{c.savedTitle}</h3></div></div>{data.saved.length?<div className={styles.savedList}>{data.saved.map(x=><a key={x.id} href={x.href}>{x.title} →</a>)}</div>:<p className={styles.empty}>{c.emptySaved}</p>}</div><p className={styles.notice}><strong>NEXT STEP</strong><span>{actualRole==="coach"?`${programmeById.torsten.title[localeIndex(locale)]} → D-HUB → court practice`:"RBA ID → Passport → Next Opportunity"}</span></p></section>;
}
