"use client";

import { useEffect, useMemo, useState } from "react";
import { ArrowRight, CheckCircle2, Globe2, MapPin, Search, ShieldCheck } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
import type { Locale } from "./site-frame";
import styles from "./homecourt-network.module.css";

type Entity={id:string;entity_id:string;entity_type:string;name:string;country:string;region:string|null;city:string|null;description:string|null;website_url:string|null;age_groups:string[];categories:string[];recruitment_status:string;trial_status:string;last_confirmed_at:string|null;operator_confirmed_at:string|null};
type Post={id:string;entity_id:string;title:string;age_group:string;gender:string;country_from:string;city_from:string|null;target_countries:string[];mode:string;starts_on:string|null;ends_on:string|null;venue_available:boolean;languages:string[];purpose:string|null;level_note:string|null;public_note:string|null};
type PublicOrg={entity_id:string;name:string};
const countryNames:Record<Locale,Record<string,string>>={
 en:{JP:"Japan",TW:"Taiwan",KR:"Korea",MY:"Malaysia",DE:"Germany",US:"United States",AU:"Australia"},
 ja:{JP:"日本",TW:"台湾",KR:"韓国",MY:"マレーシア",DE:"ドイツ",US:"アメリカ",AU:"オーストラリア"},
 "zh-tw":{JP:"日本",TW:"台灣",KR:"韓國",MY:"馬來西亞",DE:"德國",US:"美國",AU:"澳洲"},
 ko:{JP:"일본",TW:"대만",KR:"한국",MY:"말레이시아",DE:"독일",US:"미국",AU:"호주"}
};
const copy={
 en:{exploreTitle:"Find the next place to grow.",exploreLead:"Expand your options through verified facts about youth basketball environments—not paid rankings or anonymous star ratings.",notice:"HOMECOURT does not replace federation registration.",noticeBody:"Federation membership, player registration, official eligibility and official competition entry remain with the relevant governing body. HOMECOURT is a development-discovery layer.",search:"Search team, city or activity",country:"Country",age:"Age",all:"All",operator:"Operator confirmed",source:"Public information checked",recruit:"Recruitment",trial:"Trial",unknown:"Check required",official:"Website",manage:"Manage this page",empty:"No verified listing matches yet.",matchTitle:"Make international exchange easier to start.",matchLead:"Youth teams can publish host/travel conditions for friendlies, joint practices and development exchange. No public player ranking and no unrestricted adult-to-minor DMs.",teamFirst:"Team-to-team first.",teamFirstBody:"MATCH is managed by team operators. Official competition registration and eligibility stay with the relevant federation.",open:"open matches",date:"Preferred dates",target:"Target countries",venue:"Venue",venueYes:"Host venue available",consult:"Discuss",interest:"Respond as a team"},
 "zh-tw":{exploreTitle:"找到下一個成長的地方。",exploreLead:"不靠付費排名或匿名星等，而是透過可確認的青少年籃球環境資訊，擴大球員與家庭的選擇。",notice:"HOMECOURT不取代協會的正式註冊。",noticeBody:"協會加盟、球員註冊、正式參賽資格與大會報名，仍以各主管協會制度為準。HOMECOURT負責的是培育環境與機會的探索。",search:"搜尋球隊、城市或活動",country:"國家／地區",age:"年齡",all:"全部",operator:"營運者已確認",source:"公開資訊已確認",recruit:"招募",trial:"體驗",unknown:"待確認",official:"官方網站",manage:"管理此頁",empty:"目前沒有符合條件的已確認資訊。",matchTitle:"讓國際交流不再只靠偶然。",matchLead:"青少年球隊可以依照接待／遠征條件，尋找友誼賽、共同訓練與培育交流。不做球員公開排名，也不開放成人與未成年者無限制私訊。",teamFirst:"先從球隊對球隊開始。",teamFirstBody:"MATCH由球隊營運者管理；正式大會報名與參賽資格仍以各主管協會為準。",open:"個公開募集",date:"希望日期",target:"希望國家",venue:"場地",venueYes:"可提供接待場地",consult:"另行協調",interest:"以球隊身分聯絡"},
 ko:{exploreTitle:"다음 성장 환경을 찾으세요.",exploreLead:"유료 순위나 익명 별점이 아니라 확인 가능한 유소년 농구 환경 정보로 선택지를 넓힙니다.",notice:"HOMECOURT는 협회의 공식 등록을 대체하지 않습니다.",noticeBody:"협회 가입, 선수 등록, 공식 출전 자격과 대회 신청은 각 경기단체의 공식 제도를 따릅니다. HOMECOURT는 성장 환경과 기회를 찾는 레이어입니다.",search:"팀·도시·활동 검색",country:"국가／지역",age:"연령",all:"전체",operator:"운영자 확인",source:"공개 정보 확인",recruit:"모집",trial:"체험",unknown:"확인 필요",official:"공식 사이트",manage:"이 페이지 관리",empty:"현재 조건에 맞는 확인된 정보가 없습니다.",matchTitle:"국제 교류를 우연에만 맡기지 않습니다.",matchLead:"유소년 팀이 친선 경기, 공동 훈련, 성장 교류를 위해 호스트／원정 조건을 공개할 수 있습니다. 선수 공개 랭킹과 성인-미성년자 무제한 DM은 두지 않습니다.",teamFirst:"먼저 팀 대 팀으로.",teamFirstBody:"MATCH는 팀 운영자 단위로 관리합니다. 공식 대회 신청과 출전 자격은 각 경기단체의 제도를 따릅니다.",open:"개 모집",date:"희망 일정",target:"희망 국가",venue:"장소",venueYes:"호스트 장소 제공 가능",consult:"협의",interest:"팀으로 관심 보내기"}
} as const;

export function GlobalHomecourtExplore({locale}:{locale:Exclude<Locale,"ja">}){
 const c=copy[locale],db=useMemo(()=>createClient(),[]);
 const [items,setItems]=useState<Entity[]>([]),[loading,setLoading]=useState(true),[q,setQ]=useState(""),[country,setCountry]=useState("all"),[age,setAge]=useState("all");
 useEffect(()=>{const timer=window.setTimeout(async()=>{const r=await db.from("homecourt_public_entities").select("id,entity_id,entity_type,name,country,region,city,description,website_url,age_groups,categories,recruitment_status,trial_status,last_confirmed_at,operator_confirmed_at").eq("published",true).order("last_confirmed_at",{ascending:false,nullsFirst:false});setItems((r.data||[]) as Entity[]);setLoading(false);},0);return()=>window.clearTimeout(timer);},[db]);
 const countries=Array.from(new Set(items.map(x=>x.country))).sort();
 const visible=items.filter(x=>(country==="all"||x.country===country)&&(age==="all"||x.age_groups.includes(age))&&(!q.trim()||[x.name,x.region,x.city,x.description,...x.categories].filter(Boolean).join(" ").toLowerCase().includes(q.toLowerCase())));
 return <div className={styles.page}><section className={styles.hero}><p className={styles.kicker}><Globe2/> HOMECOURT / EXPLORE</p><h1>{c.exploreTitle}</h1><p>{c.exploreLead}</p><div className={styles.heroActions}><a className={styles.primary} href={(locale==="en"?"":"/"+locale)+"/homecourt/match"}>HOMECOURT MATCH<ArrowRight/></a></div></section><section className={styles.notice}><ShieldCheck/><div><strong>{c.notice}</strong><p>{c.noticeBody}</p></div></section><section className={styles.controls}><div><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={c.search}/></div><label>{c.country}<select value={country} onChange={e=>setCountry(e.target.value)}><option value="all">{c.all}</option>{countries.map(x=><option key={x} value={x}>{countryNames[locale][x]||x}</option>)}</select></label><label>{c.age}<select value={age} onChange={e=>setAge(e.target.value)}><option value="all">{c.all}</option>{["U8","U10","U12","U15","U18"].map(x=><option key={x}>{x}</option>)}</select></label></section><section className={styles.results}>{loading?<p>Loading…</p>:visible.length?<div className={styles.grid}>{visible.map(x=><article className={styles.card} key={x.id}><div className={styles.cardTop}><span>{x.entity_type.toUpperCase()}</span><b>{x.operator_confirmed_at?<><CheckCircle2/>{c.operator}</>:c.source}</b></div><h2>{x.name}</h2><p className={styles.location}><MapPin/>{[countryNames[locale][x.country]||x.country,x.region,x.city].filter(Boolean).join(" / ")}</p>{x.description?<p>{x.description}</p>:null}<div className={styles.tags}>{x.age_groups.map(a=><span key={a}>{a}</span>)}{x.categories.slice(0,4).map(a=><span key={a}>{a}</span>)}</div><dl><div><dt>{c.recruit}</dt><dd>{x.recruitment_status||c.unknown}</dd></div><div><dt>{c.trial}</dt><dd>{x.trial_status||c.unknown}</dd></div></dl><div className={styles.cardActions}>{x.website_url?<a href={x.website_url} target="_blank" rel="noreferrer">{c.official}<ArrowRight/></a>:null}<a href={(locale==="en"?"":"/"+locale)+"/my-homecourt"}>{c.manage}<ArrowRight/></a></div></article>)}</div>:<div className={styles.empty}><Globe2/><h2>{c.empty}</h2></div>}</section></div>;
}

export function GlobalHomecourtMatch({locale}:{locale:Exclude<Locale,"ja">}){
 const c=copy[locale],db=useMemo(()=>createClient(),[]);
 const [posts,setPosts]=useState<Post[]>([]),[entities,setEntities]=useState<Record<string,PublicOrg>>({}),[loading,setLoading]=useState(true);
 useEffect(()=>{const timer=window.setTimeout(async()=>{const p=await db.rpc("get_homecourt_exchange_posts");const rows=(p.data||[]) as Post[];setPosts(rows);const ids=Array.from(new Set(rows.map(x=>x.entity_id)));if(ids.length){const e=await db.from("homecourt_public_entities").select("entity_id,name").in("entity_id",ids);const map:Record<string,PublicOrg>={};for(const x of (e.data||[]) as PublicOrg[])map[x.entity_id]=x;setEntities(map);}setLoading(false);},0);return()=>window.clearTimeout(timer);},[db]);
 return <div className={styles.page}><section className={styles.hero}><p className={styles.kicker}><Globe2/> HOMECOURT / MATCH</p><h1>{c.matchTitle}</h1><p>{c.matchLead}</p><div className={styles.heroActions}><a className={styles.primary} href={(locale==="en"?"":"/"+locale)+"/homecourt/explore"}>HOMECOURT EXPLORE<ArrowRight/></a></div></section><section className={styles.notice}><ShieldCheck/><div><strong>{c.teamFirst}</strong><p>{c.teamFirstBody}</p></div></section><section className={styles.results}>{loading?<p>Loading…</p>:posts.length?<div className={styles.grid}>{posts.map(p=><article className={styles.card} key={p.id}><div className={styles.cardTop}><span>INTERNATIONAL MATCH</span><b>{p.mode}</b></div><h2>{p.title}</h2><p className={styles.location}><MapPin/>{(entities[p.entity_id]?.name||"Team")+" · "+(countryNames[locale][p.country_from]||p.country_from)+(p.city_from?" / "+p.city_from:"")}</p><div className={styles.tags}><span>{p.age_group}</span><span>{p.gender}</span>{p.languages.map(x=><span key={x}>{x}</span>)}</div><dl><div><dt>{c.date}</dt><dd>{p.starts_on||c.consult}{p.ends_on&&p.ends_on!==p.starts_on?" – "+p.ends_on:""}</dd></div><div><dt>{c.target}</dt><dd>{p.target_countries.length?p.target_countries.map(x=>countryNames[locale][x]||x).join(" / "):c.consult}</dd></div><div><dt>{c.venue}</dt><dd>{p.venue_available?c.venueYes:c.consult}</dd></div></dl>{p.purpose?<p>{p.purpose}</p>:null}{p.public_note?<p>{p.public_note}</p>:null}<div className={styles.cardActions}><a href={(locale==="en"?"":"/"+locale)+"/my-homecourt"}>{c.interest}<ArrowRight/></a></div></article>)}</div>:<div className={styles.empty}><Globe2/><h2>0 {c.open}</h2></div>}</section></div>;
}
