"use client";
import {useState} from "react";
import Link from "next/link";
import {programmes,type Programme} from "./programme-data";
import {filterDevelopmentOpportunities,type DiscoveryFilters} from "@/lib/discovery-filter";
import styles from "./homecourt-discovery.module.css";
const initial:DiscoveryFilters={age:"",region:"",category:"",from:"",to:"",onlineOnly:false};
const regions=[["tohoku","東北"],["kanto","関東"],["kansai","関西"],["kyushu","九州"],["okinawa","沖縄"],["online","オンライン"]];
const categories=[["TRAIN","クリニック・キャンプ"],["PLAY","試合・交流"],["TRAVEL","遠征"],["COACH","指導者講習"]];
function href(p:Programme){return p.detailPath?`/ja/${p.detailPath}`:p.applicationUrl;}
export function HomecourtDiscovery({savedKeys,busy,onSave,role}:{savedKeys:string[];busy:boolean;onSave:(p:Programme)=>Promise<void>;role:string}){
 const [filters,setFilters]=useState(initial),[compare,setCompare]=useState<string[]>([]),[message,setMessage]=useState("");
 const today=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Tokyo",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
 const items=filterDevelopmentOpportunities(programmes,filters,today);
 const selected=programmes.filter(p=>compare.includes(p.id));
 function change(key:keyof DiscoveryFilters,value:string|boolean){setFilters(old=>({...old,[key]:value}));}
 function toggleCompare(id:string){if(compare.includes(id)){setCompare(compare.filter(x=>x!==id));setMessage("");return;}if(compare.length===2){setMessage("比較は2件までです。入れ替える活動の「比較から外す」を押してください。");return;}setCompare([...compare,id]);setMessage("");}
 async function share(){const url=new URL("/ja/opportunities",window.location.origin).href;try{if(navigator.share){await navigator.share({title:"RBA｜次のバスケットボールの機会",text:"一緒に、次に参加する活動を探してみませんか。",url});return;}await navigator.clipboard.writeText(url);setMessage("公開されている活動一覧のリンクをコピーしました。個人の記録は含まれません。");}catch(error){if(error instanceof Error&&error.name==="AbortError")return;setMessage("共有できませんでした。「活動一覧を開く」からURLをコピーしてください。");}}
 const card=(p:Programme,comparison=false)=><article className={styles.card} key={p.id}><p className={styles.tag}>{categories.find(([key])=>key===p.category)?.[1]}{p.region==="online"?" · オンライン":""}</p><h4>{p.title[1]}</h4><dl><div><dt>日程</dt><dd>{p.date[1]}</dd></div><div><dt>場所</dt><dd>{p.place[1]}</dd></div><div><dt>対象</dt><dd>{p.audience[1]}</dd></div><div><dt>費用</dt><dd>{p.price[1]}</dd></div><div><dt>参加方法</dt><dd>{p.payment[1]}</dd></div></dl><div className={styles.actions}><a href={href(p)} target={p.detailPath?undefined:"_blank"} rel={p.detailPath?undefined:"noopener noreferrer"}>詳細・募集状況を確認 →</a><button type="button" disabled={busy} aria-pressed={savedKeys.includes(p.id)} onClick={()=>void onSave(p)}>{savedKeys.includes(p.id)?"保存済み・解除する":"あとで見るために保存"}</button><button type="button" aria-pressed={compare.includes(p.id)} onClick={()=>toggleCompare(p.id)}>{comparison||compare.includes(p.id)?"比較から外す":"比較に追加"}</button></div></article>;
 return <section className={styles.root} aria-labelledby="discovery-title"><header><p className={styles.tag}>DISCOVER / 自分で選ぶ、次の一歩</p><h3 id="discovery-title">いつものコートの、外へ。</h3><p>違う地域、違う仲間、違う考え方。今の自分に合う機会を探して、比べて、選びましょう。</p></header>
 <form className={styles.filters} onSubmit={e=>e.preventDefault()}><label>年代・立場<select value={filters.age} onChange={e=>change("age",e.target.value)}><option value="">すべて</option>{["U8","U10","U12","U15","COACH"].map(x=><option key={x} value={x}>{x==="COACH"?"指導者":x}</option>)}</select></label><label>地域<select value={filters.region} onChange={e=>change("region",e.target.value)}><option value="">全国・オンライン</option>{regions.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>目的<select value={filters.category} onChange={e=>change("category",e.target.value)}><option value="">すべて</option>{categories.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>開始日の範囲・ここから<input type="date" value={filters.from} onChange={e=>change("from",e.target.value)}/></label><label>ここまで<input type="date" value={filters.to} min={filters.from||undefined} onChange={e=>change("to",e.target.value)}/></label><label className={styles.check}><input type="checkbox" checked={filters.onlineOnly} onChange={e=>change("onlineOnly",e.target.checked)}/>オンラインだけ見る</label><button type="button" onClick={()=>setFilters(initial)}>条件をリセット</button></form>
 {filters.from&&filters.to&&filters.from>filters.to?<p role="alert">終了日は開始日以降を選んでください。</p>:null}<p role="status">{items.length}件の活動が見つかりました。</p><p className={styles.note}>申込の締切・残席・最新の募集状況は、各活動の案内をご確認ください。</p>
 {compare.length>0&&<section className={styles.comparison} aria-labelledby="compare-title"><h4 id="compare-title">気になる活動を比べる · {compare.length}/2</h4>{compare.length===1&&<p>もう1件追加すると、同じ項目で比較できます。</p>}<div className={styles.cards}>{selected.map(p=>card(p,true))}</div><button type="button" onClick={()=>setCompare([])}>比較をクリア</button></section>}
 {message&&<p role="status">{message}</p>}<div className={styles.cards}>{items.map(p=>card(p))}</div>{!items.length&&<p className={styles.empty}>この条件に合う活動はまだありません。地域や日程を広げて探してみましょう。</p>}
 <section className={styles.world}><p className={styles.tag}>OPEN YOUR WORLD</p><h4>世界への一歩は、今日から。</h4><p>遠征だけが入口ではありません。違う育て方を知る、言葉を交わす、自分で考えて試す。その経験も、あなたの財産になります。</p><div className={styles.cards}><article><h5>{role==="coach"?"違う指導の考え方に触れる":"いつもと違うバスケを知る"}</h5><p>{role==="parent"?"お子さまと、知らない地域の活動を一つ見て「何が面白そう？」と話してみる。":role==="coach"?"海外の指導者講習から、次の練習で試すテーマを一つ選ぶ。":"違う地域や国の試合を見て、試してみたいプレーを一つ見つける。"}</p><Link href={role==="coach"?"/ja/events/torsten-loibl-online-clinic":"/ja/international"}>世界につながる活動を見る →</Link></article><article><h5>一言、自分から伝えてみる</h5><p>“My name is …” と自己紹介。 “One more!” とパスを呼ぶ。短い言葉から、仲間との距離を縮めてみる。</p><a href="#passport-title">試したことを記録する →</a></article><article><h5>自分の次の一歩を決める</h5><p>今週試すことと、振り返る日を決める。できたことも難しかったことも、次の練習のヒントになります。</p><a href="#passport-title">「これから」に目標を残す →</a></article><article><h5>学びを、練習や会話へ</h5><p>選手・保護者・指導者に向けた英語の育成ジャーナルから、違う言葉でバスケに触れる。</p><Link href="/journal">育成ジャーナルを読む（英語） →</Link></article></div></section>
 <footer className={styles.footer}><h4>次の機会を、仲間にも。</h4><p>気になる活動を家族や仲間と話すきっかけに。共有するのは公開の活動一覧です。</p><button type="button" onClick={()=>void share()}>活動一覧を共有する</button><Link href="/ja/opportunities">活動一覧を開く →</Link></footer></section>;
}
