import { ArrowRight, Globe2, MessageCircle, Plane, ShieldCheck, Users } from "lucide-react";
import { Locale, localePath, SiteFrame } from "./site-frame";
import { tr, worldPoints } from "./network-data";

const copy={
 ja:{title:"日本とアジアを、育成でつなぐ。",lead:"試合、キャンプ、指導者交流などを、目的と年代に合わせて組み立てます。海外のチーム・アカデミー・指導者と、日本での交流をつなぐ相談窓口です。",status:"現在の国際ネットワーク",statusBody:"すでに実施した連携と、現在協議を進めている連携を分けて掲載しています。",partner:"連携先",discussion:"協議中",ways:"一緒につくれること",cards:[["FRIENDLY GAME","年代・競技レベル・学びたいことを合わせた交流試合。"],["DEVELOPMENT CAMP","選手育成と指導者の学びを組み合わせたキャンプ。"],["COACH EXCHANGE","練習見学、オンライン講習、現場での対話。"],["TOURNAMENT","参加条件と運営体制を確認した大会・交流企画。"]],process:"相談から実施まで",steps:[["01","目的を共有","団体名、年代、人数、希望時期、学びたいことをお知らせください。"],["02","実現方法を整理","対戦相手、会場、指導者、通訳、安全管理、移動など、実施に必要な条件を確認します。"],["03","役割と費用を確認","実施範囲、役割分担、費用、申込条件を書面で確認します。"],["04","実施と振り返り","活動後に得られたことを振り返り、次の交流につなげます。"]],contact:"海外連携を相談する",contactBody:"英語・日本語・繁体字中国語・韓国語でご相談いただけます。",mail:"お問い合わせへ",whatsapp:"WhatsAppで相談"},
 en:{title:"Connect Japan and Asia through development.",lead:"RBA is a practical Japan contact for teams, academies and coaches planning games, camps and coach exchange with a clear learning purpose.",status:"Current international network",statusBody:"Confirmed relationships and discussions are shown separately.",partner:"Partner",discussion:"In discussion",ways:"What we can build together",cards:[["FRIENDLY GAME","Match age, level and learning purpose."],["DEVELOPMENT CAMP","Combine player development and coach learning."],["COACH EXCHANGE","Observation, online learning and court dialogue."],["TOURNAMENT","Events with clear eligibility and operating roles."]],process:"From enquiry to delivery",steps:[["01","Share the purpose","Tell us the organisation, ages, group size, timing and learning goal."],["02","Shape a realistic plan","Clarify opponents, court, coaches, language, safety and travel conditions."],["03","Confirm roles and cost","Document responsibilities, scope, fees and entry terms."],["04","Deliver and review","Review the experience and agree the next step."]],contact:"Discuss an international programme",contactBody:"Enquiries are welcome in English, Japanese, Traditional Chinese and Korean.",mail:"Open enquiry",whatsapp:"WhatsApp"},
 "zh-tw":{title:"以培育連結日本與亞洲。",lead:"為海外球隊、Academy與教練提供日本端窗口，依照目的與年齡設計比賽、培育營及教練交流。",status:"目前國際網絡",statusBody:"已確認合作與洽談中關係分開標示。",partner:"合作夥伴",discussion:"洽談中",ways:"可共同規劃",cards:[["FRIENDLY GAME","配合年齡、程度與學習目的的交流賽。"],["DEVELOPMENT CAMP","結合球員培育與教練學習。"],["COACH EXCHANGE","觀摩、線上課程與場上交流。"],["TOURNAMENT","確認資格與運營角色的賽事企劃。"]],process:"從洽詢到執行",steps:[["01","分享目的","提供單位、年齡、人數、時間與學習目標。"],["02","整理可行方案","確認對手、場地、教練、語言、安全及移動條件。"],["03","確認分工與費用","以書面確認責任、範圍、費用及參加條件。"],["04","執行與回顧","活動後整理成果與下一步。"]],contact:"洽詢國際合作",contactBody:"可使用英語、日語、繁體中文與韓語聯絡。",mail:"前往洽詢",whatsapp:"WhatsApp洽詢"},
 ko:{title:"육성으로 일본과 아시아를 연결합니다.",lead:"해외 팀, 아카데미와 코치가 목적에 맞는 경기, 캠프와 코치 교류를 만들 수 있도록 일본 측 창구가 됩니다.",status:"현재 국제 네트워크",statusBody:"확인된 협력과 협의 중 관계를 구분해 표시합니다.",partner:"파트너",discussion:"협의 중",ways:"함께 만들 수 있는 것",cards:[["FRIENDLY GAME","연령, 수준과 학습 목적을 맞춘 교류 경기."],["DEVELOPMENT CAMP","선수 성장과 코치 학습을 결합한 캠프."],["COACH EXCHANGE","훈련 관찰, 온라인 학습과 코트 대화."],["TOURNAMENT","참가 조건과 운영 역할이 명확한 대회." ]],process:"문의부터 실행까지",steps:[["01","목적 공유","단체, 연령, 인원, 시기와 학습 목표를 알려 주세요."],["02","실행안 정리","상대, 코트, 코치, 언어, 안전과 이동 조건을 확인합니다."],["03","역할과 비용 확인","책임, 범위, 비용과 참가 조건을 문서로 확인합니다."],["04","실행 및 리뷰","활동 후 성과와 다음 단계를 정리합니다."]],contact:"국제 교류 상담",contactBody:"영어, 일본어, 번체 중국어와 한국어로 문의할 수 있습니다.",mail:"문의하기",whatsapp:"WhatsApp"}
} as const;

export function InternationalPlatform({locale}:{locale:Locale}){
 const c=copy[locale];const message=encodeURIComponent(locale==="ja"?"RBAの海外連携について相談したいです。団体名、対象年代、希望時期、交流目的をお送りします。":"Hello RBA, I would like to discuss a Japan–Asia basketball programme.");
 return <SiteFrame locale={locale} languagePage="international"><div className="international-platform">
  <section className="international-hero section-pad"><a className="back-link" href={localePath(locale)}>← RBA</a><Globe2/><p className="section-index inverse">RBA INTERNATIONAL / JAPAN × ASIA</p><h1>{c.title}</h1><p>{c.lead}</p><div><a className="button button-light" href="#international-contact">{c.contact}<ArrowRight/></a><a className="text-link light-link" href={localePath("en","international")}>ENGLISH PAGE<ArrowRight/></a></div></section>
  <section className="international-network section-pad"><div className="section-head"><div><p className="section-index">JAPAN × ASIA</p><h2>{c.status}</h2></div><p>{c.statusBody}</p></div><div className="international-network-grid">{worldPoints.map(point=><article key={point.id}><span>{point.status==="partner"?c.partner:c.discussion}</span><h3>{tr(point.name,locale)}</h3><p>{tr(point.detail,locale)}</p></article>)}</div></section>
  <section className="international-programmes section-pad"><p className="section-index inverse">PROGRAMME DESIGN</p><h2>{c.ways}</h2><div>{c.cards.map(([title,body])=><article key={title}><Plane/><h3>{title}</h3><p>{body}</p></article>)}</div></section>
  <section className="international-process section-pad"><div><p className="section-index">SAFE / CLEAR / PURPOSEFUL</p><h2>{c.process}</h2><ShieldCheck/></div><ol>{c.steps.map(([no,title,body])=><li key={no}><span>{no}</span><div><strong>{title}</strong><p>{body}</p></div></li>)}</ol></section>
  <section className="international-contact section-pad" id="international-contact"><div><p className="section-index inverse">CONTACT RBA</p><h2>{c.contact}</h2><p>{c.contactBody}</p></div><div><a className="button button-light" href={localePath(locale,"contact")}><Users/>{c.mail}<ArrowRight/></a><a className="button button-light" href={`https://wa.me/818032483703?text=${message}`} target="_blank" rel="noreferrer"><MessageCircle/>{c.whatsapp}</a></div></section>
 </div></SiteFrame>;
}
