import { ArrowRight, Globe2, MessageCircle, Plane, ShieldCheck, Users } from "lucide-react";
import { Locale, localePath, SiteFrame } from "./site-frame";
import { tr, worldPoints } from "./network-data";


const taiwanExchange:Record<Locale,{eyebrow:string;title:string;intro:string;record:string;pilot:string;pilotText:string;scope:string;scopeText:string;cta:string}>={
 ja:{eyebrow:"TAIWAN / FIELD PARTNERSHIP",title:"台湾との交流を、次の育成機会へ。",intro:"2026年の沖縄での合同キャンプと台湾での女子ユース交流を足場に、現場での学びを一度きりにしない仕組みを検討しています。",record:"これまでの交流",pilot:"次の共同企画は準備段階",pilotText:"相互交流試合、育成キャンプ、指導者交流を候補に、現地パートナーと内容・日程・役割を協議します。募集や料金は決定後に公式案内します。",scope:"安全と運営の原則",scopeText:"参加者の年齢・人数、引率、緊急時対応、費用、旅行手配の責任範囲を事前に確認します。",cta:"交流の相談をする"},
 en:{eyebrow:"TAIWAN / FIELD PARTNERSHIP",title:"Make the next exchange more meaningful.",intro:"Following our 2026 joint camp in Okinawa and girls' youth exchange in Taiwan, we are exploring how to make shared learning an ongoing opportunity.",record:"Exchange to date",pilot:"Next programme under discussion",pilotText:"Potential formats include reciprocal games, development camps and coach exchange. Dates, roles and fees have not been agreed or announced.",scope:"Safety and operational clarity",scopeText:"We clarify age groups, supervision, emergency procedures, costs and responsibility for travel arrangements before any programme is offered.",cta:"Discuss an exchange"},
 "zh-tw":{eyebrow:"TAIWAN / FIELD PARTNERSHIP",title:"讓日台交流延續為長期的培育機會。",intro:"以2026年沖繩共同訓練營及台灣女子青少年交流為基礎，探索持續互相學習的合作模式。",record:"既有交流",pilot:"下一階段仍在討論中",pilotText:"可能形式包括雙向交流賽、培育營及教練交流。日期、分工與費用尚未確認，也尚未開放報名。",scope:"安全與營運責任",scopeText:"正式推出前，須確認年齡、人數、隨隊照護、緊急應變、費用及旅行安排的責任。",cta:"洽詢交流合作"},
 ko:{eyebrow:"TAIWAN / FIELD PARTNERSHIP",title:"대만과의 교류를 지속적인 배움으로.",intro:"2026년 오키나와 공동 캠프와 대만 여자 유소년 교류를 바탕으로 장기적인 육성 교류를 검토하고 있습니다.",record:"진행한 교류",pilot:"다음 공동 프로그램은 협의 단계",pilotText:"상호 교류 경기, 육성 캠프, 코치 교류 등을 검토 중입니다. 일정, 역할, 비용은 아직 확정되지 않았습니다.",scope:"안전과 운영 책임",scopeText:"모집 전에 연령, 인원, 인솔, 비상 대응, 비용, 여행 준비의 책임 범위를 확인합니다.",cta:"교류 문의"}
};

const copy={
 ja:{title:"日本とアジアを、育成でつなぐ。",lead:"試合、キャンプ、指導者交流などを、目的と年代に合わせて組み立てます。海外のチーム・アカデミー・指導者と、日本での交流をつなぐ相談窓口です。",status:"現在の国際ネットワーク",statusBody:"確認済みの連携と、準備・調整中の連携を、現在の進捗に合わせて掲載しています。",partner:"連携先",discussion:"協議中",ways:"一緒につくれること",cards:[["FRIENDLY GAME","年代・競技レベル・学びたいことを合わせた交流試合。"],["DEVELOPMENT CAMP","選手育成と指導者の学びを組み合わせたキャンプ。"],["COACH EXCHANGE","練習見学、オンライン講習、現場での対話。"],["TOURNAMENT","参加条件と運営体制を確認した大会・交流企画。"]],process:"相談から実施まで",steps:[["01","目的を共有","団体名、年代、人数、希望時期、学びたいことをお知らせください。"],["02","実現方法を整理","対戦相手、会場、指導者、通訳、安全管理、移動など、実施に必要な条件を確認します。"],["03","役割と費用を確認","実施範囲、役割分担、費用、申込条件を書面で確認します。"],["04","実施と振り返り","活動後に得られたことを振り返り、次の交流につなげます。"]],contact:"海外連携を相談する",contactBody:"英語・日本語・繁体字中国語・韓国語でご相談いただけます。",mail:"お問い合わせへ",whatsapp:"WhatsAppで相談"},
 en:{title:"Connect Japan and Asia through development.",lead:"RBA is a practical Japan contact for teams, academies and coaches planning games, camps and coach exchange with a clear learning purpose.",status:"Current international network",statusBody:"Confirmed relationships and discussions are shown separately.",partner:"Partner",discussion:"In discussion",ways:"What we can build together",cards:[["FRIENDLY GAME","Match age, level and learning purpose."],["DEVELOPMENT CAMP","Combine player development and coach learning."],["COACH EXCHANGE","Observation, online learning and court dialogue."],["TOURNAMENT","Events with clear eligibility and operating roles."]],process:"From enquiry to delivery",steps:[["01","Share the purpose","Tell us the organisation, ages, group size, timing and learning goal."],["02","Shape a realistic plan","Clarify opponents, court, coaches, language, safety and travel conditions."],["03","Confirm roles and cost","Document responsibilities, scope, fees and entry terms."],["04","Deliver and review","Review the experience and agree the next step."]],contact:"Discuss an international programme",contactBody:"Enquiries are welcome in English, Japanese, Traditional Chinese and Korean.",mail:"Open enquiry",whatsapp:"WhatsApp"},
 "zh-tw":{title:"以培育連結日本與亞洲。",lead:"為海外球隊、Academy與教練提供日本端窗口，依照目的與年齡設計比賽、培育營及教練交流。",status:"目前國際網絡",statusBody:"已確認合作與洽談中關係分開標示。",partner:"合作夥伴",discussion:"洽談中",ways:"可共同規劃",cards:[["FRIENDLY GAME","配合年齡、程度與學習目的的交流賽。"],["DEVELOPMENT CAMP","結合球員培育與教練學習。"],["COACH EXCHANGE","觀摩、線上課程與場上交流。"],["TOURNAMENT","確認資格與運營角色的賽事企劃。"]],process:"從洽詢到執行",steps:[["01","分享目的","提供單位、年齡、人數、時間與學習目標。"],["02","整理可行方案","確認對手、場地、教練、語言、安全及移動條件。"],["03","確認分工與費用","以書面確認責任、範圍、費用及參加條件。"],["04","執行與回顧","活動後整理成果與下一步。"]],contact:"洽詢國際合作",contactBody:"可使用英語、日語、繁體中文與韓語聯絡。",mail:"前往洽詢",whatsapp:"WhatsApp洽詢"},
 ko:{title:"육성으로 일본과 아시아를 연결합니다.",lead:"해외 팀, 아카데미와 코치가 목적에 맞는 경기, 캠프와 코치 교류를 만들 수 있도록 일본 측 창구가 됩니다.",status:"현재 국제 네트워크",statusBody:"확인된 협력과 협의 중 관계를 구분해 표시합니다.",partner:"파트너",discussion:"협의 중",ways:"함께 만들 수 있는 것",cards:[["FRIENDLY GAME","연령, 수준과 학습 목적을 맞춘 교류 경기."],["DEVELOPMENT CAMP","선수 성장과 코치 학습을 결합한 캠프."],["COACH EXCHANGE","훈련 관찰, 온라인 학습과 코트 대화."],["TOURNAMENT","참가 조건과 운영 역할이 명확한 대회." ]],process:"문의부터 실행까지",steps:[["01","목적 공유","단체, 연령, 인원, 시기와 학습 목표를 알려 주세요."],["02","실행안 정리","상대, 코트, 코치, 언어, 안전과 이동 조건을 확인합니다."],["03","역할과 비용 확인","책임, 범위, 비용과 참가 조건을 문서로 확인합니다."],["04","실행 및 리뷰","활동 후 성과와 다음 단계를 정리합니다."]],contact:"국제 교류 상담",contactBody:"영어, 일본어, 번체 중국어와 한국어로 문의할 수 있습니다.",mail:"문의하기",whatsapp:"WhatsApp"}
} as const;

export function InternationalPlatform({locale}:{locale:Locale}){
 const c=copy[locale];const message=encodeURIComponent(locale==="ja"?"RBAの海外連携について相談したいです。団体名、対象年代、希望時期、交流目的をお送りします。":"Hello RBA, I would like to discuss a Japan–Asia basketball programme.");
 return <SiteFrame locale={locale} languagePage="international"><div className="international-platform">
  <section className="international-hero section-pad"><a className="back-link" href={localePath(locale)}>← RBA</a><Globe2/><p className="section-index inverse">RBA INTERNATIONAL / JAPAN × ASIA</p><h1>{c.title}</h1><p>{c.lead}</p><div><a className="button button-light" href="#international-contact">{c.contact}<ArrowRight/></a><a className="text-link light-link" href={localePath("en","international")}>ENGLISH PAGE<ArrowRight/></a></div></section>
  <section className="international-network section-pad" aria-labelledby="taiwan-exchange-heading"><div className="section-head"><div><p className="section-index">{taiwanExchange[locale].eyebrow}</p><h2 id="taiwan-exchange-heading">{taiwanExchange[locale].title}</h2></div><p>{taiwanExchange[locale].intro}</p></div><div className="international-network-grid"><article><span>{taiwanExchange[locale].record}</span><h3>OKINAWA × TAIWAN · 2026</h3><p>{locale==="ja"?"沖縄での合同キャンプ、台湾での女子ユース交流。":locale==="zh-tw"?"沖繩共同訓練營、台灣女子青少年交流。":locale==="ko"?"오키나와 공동 캠프와 대만 여자 유소년 교류.":"Joint camp in Okinawa and girls' youth exchange in Taiwan."}</p></article><article><span>{taiwanExchange[locale].pilot}</span><h3>JAPAN × TAIWAN</h3><p>{taiwanExchange[locale].pilotText}</p></article><article><span>{taiwanExchange[locale].scope}</span><h3>SAFEGUARDING / OPERATIONS</h3><p>{taiwanExchange[locale].scopeText}</p></article></div><p><a className="button button-dark" href={localePath(locale,"taiwan")}>{locale==="ja"?"台湾交流の詳細を見る":locale==="zh-tw"?"了解日台交流":locale==="ko"?"대만 교류 자세히 보기":"Explore Taiwan exchange"}<ArrowRight size={18}/></a></p></section>
  <section className="international-network section-pad"><div className="section-head"><div><p className="section-index">JAPAN × ASIA</p><h2>{c.status}</h2></div><p>{c.statusBody}</p></div><div className="international-network-grid">{worldPoints.map(point=><article key={point.id}><span>{point.status==="partner"?c.partner:tr(point.statusLabel||[c.discussion,c.discussion,c.discussion,c.discussion],locale)}</span><h3>{tr(point.name,locale)}</h3><p>{tr(point.detail,locale)}</p></article>)}</div></section>
  <section className="international-programmes section-pad"><p className="section-index inverse">PROGRAMME DESIGN</p><h2>{c.ways}</h2><div>{c.cards.map(([title,body])=><article key={title}><Plane/><h3>{title}</h3><p>{body}</p></article>)}</div></section>
  <section className="international-process section-pad"><div><p className="section-index">SAFE / CLEAR / PURPOSEFUL</p><h2>{c.process}</h2><ShieldCheck/></div><ol>{c.steps.map(([no,title,body])=><li key={no}><span>{no}</span><div><strong>{title}</strong><p>{body}</p></div></li>)}</ol></section>
  <section className="international-contact section-pad" id="international-contact"><div><p className="section-index inverse">CONTACT RBA</p><h2>{c.contact}</h2><p>{c.contactBody}</p></div><div><a className="button button-light" href={localePath(locale,"contact")}><Users/>{c.mail}<ArrowRight/></a><a className="button button-light" href={`https://wa.me/818032483703?text=${message}`} target="_blank" rel="noreferrer"><MessageCircle/>{c.whatsapp}</a></div></section>
 </div></SiteFrame>;
}
