import type { Metadata } from "next";
import { ArrowLeft, ArrowRight, MessageCircle } from "lucide-react";
import { SiteFrame } from "@/components/site-frame";

export type ArticleSection={heading:string;paragraphs:string[];bullets?:string[]};

export function JournalArticle({number,title,standfirst,reading,sections,asideTitle="START HERE",asideText="Japan is not a product to consume. A useful exchange begins with a development question and respect for the people who host it.",ctaTitle="Interested in Japan? Start with RBA.",ctaBody="Send your country, organisation, age group, preferred dates and the experience you want to create. We will tell you what is realistic and what the next step should be."}:{number:string;title:string;standfirst:string;reading:string;sections:ArticleSection[];asideTitle?:string;asideText?:string;ctaTitle?:string;ctaBody?:string}){
  return <SiteFrame><article className="journal-article"><header className="article-hero section-pad"><a href="/asia" className="back-link"><ArrowLeft size={15}/> Japan Access Desk</a><p className="section-index">RBA JOURNAL / {number}</p><h1>{title}</h1><div><p>{standfirst}</p><span>{reading} · RBA JAPAN</span></div></header><div className="article-body section-pad"><aside><p>{asideTitle}</p><span>{asideText}</span></aside><div>{sections.map((section,index)=><section key={section.heading}><span>{String(index+1).padStart(2,"0")}</span><h2>{section.heading}</h2>{section.paragraphs.map(p=><p key={p}>{p}</p>)}{section.bullets&&<ul>{section.bullets.map(b=><li key={b}>{b}</li>)}</ul>}</section>)}</div></div><footer className="article-convert section-pad"><p className="section-index inverse">TELL US YOUR QUESTION</p><h2>{ctaTitle}</h2><p>{ctaBody}</p><div><a className="button button-light" href="https://wa.me/818032483703?text=Hello%20RBA%2C%20our%20team%20is%20interested%20in%20a%20basketball%20experience%20in%20Japan." target="_blank" rel="noreferrer"><MessageCircle size={17}/> Ask on WhatsApp</a><a className="button button-dark" href="/clinic-request">Send a full brief <ArrowRight size={17}/></a></div></footer></article></SiteFrame>
}

export const journalMetadata=(title:string,description:string,slug:string):Metadata=>({title,description,alternates:{canonical:`/journal/${slug}`},openGraph:{title,description,type:"article",url:`/journal/${slug}`}});