import { ui } from "./ui-copy";
import { ContactForm, contactFormUrl } from "./contact-form";
import { ArrowRight, ArrowUpRight, Mail, MessageCircle } from "lucide-react";
import { Locale, LanguagePage, SiteFrame, localePath } from "@/components/site-frame";

type Kind="about"|"approach"|"asia"|"partners"|"contact";
type PageCopy={kicker:string;title:string[];intro:string;section:string;sectionTitle:string;sectionCopy:string;cards:readonly (readonly [string,string,string])[];closing:string;closingCopy:string;primary:string;secondary:string};

const copy:Record<Locale,Record<Kind,PageCopy>>={
  en:{
    about:{kicker:"ABOUT RBA",title:["A development organisation","built in real gyms."],intro:"Riot Basketball Academy is based in Sendai and works across Japan and Asia. We connect player development, physical preparation, coach learning and international exchange.",section:"ORGANISATION PROFILE",sectionTitle:"Field work first. Structure before slogans.",sectionCopy:"RBA listens to the local environment, identifies the actual development question and builds the programme around the people responsible for that place. Representative Masato Nishio provides direction and accountability, working with coaches, performance specialists, organisers and international collaborators.",cards:[["01","PLAYER DEVELOPMENT","Game understanding, perception, decisions, timing, spacing and fundamentals."],["02","S&C","Evidence-informed preparation, load, recovery and long-term health."],["03","COACH LEARNING","Observation, practice design and direct dialogue with credible coaches."],["04","ASIA NETWORK","Relationships built around shared work, clear roles and safeguarding."]],closing:"See how RBA works",closingCopy:"Our approach explains what we prioritise from U12 through U15 and why.",primary:"Read the approach",secondary:"Contact RBA"},
    approach:{kicker:"DEVELOPMENT APPROACH",title:["See. Decide. Execute.","Then reflect."],intro:"Skill is not a collection of moves. It is the ability to recognise what the game requires and perform the right action at the right time.",section:"PLAYER-CENTRED DESIGN",sectionTitle:"Keep the player—not the coach—at the centre.",sectionCopy:"RBA builds age-appropriate practices around perception, choices and game transfer. We avoid early position limits, treat mistakes as information and make the purpose of each task clear.",cards:[["01","SEE","Read space, defenders, teammates and timing before acting."],["02","DECIDE","Choose the solution the live game actually requires."],["03","EXECUTE","Use technique with timing, purpose and responsibility to the team."],["04","REFLECT","Understand the result, adjust and try again without fear of mistakes."]],closing:"Bring the approach to your environment",closingCopy:"Share the age group, location and learning question. RBA will shape a realistic programme.",primary:"Request a clinic",secondary:"View calendar"},
    asia:{kicker:ui("en","access"),title:["Your first practical","basketball contact in Japan."],intro:"For academies, teams, coaches and families across Asia who want a meaningful learning relationship with Japan—not a generic sports tour.",section:"ONE DOOR / FOUR QUESTIONS",sectionTitle:"Who are the players? What should they learn?",sectionCopy:"Tell us your organisation, player ages, timing and learning purpose. RBA will explain what is realistic, which responsibilities stay with each organisation and what the next step should be.",cards:[["01","CLINICS IN JAPAN","A focused RBA session or multi-day programme shaped around age and context."],["02","ACADEMY EXCHANGE","Practice, observation and conversation between organisations with clear roles."],["03","COACH LEARNING","Court-based study, online preparation and reflection on development and S&C."],["04","LOCAL CONNECTION","A first introduction to relevant people and places when the fit is genuine."]],closing:"Write in your language",closingCopy:"English, Japanese, Traditional Chinese and Korean enquiries are welcome.",primary:"Start on WhatsApp",secondary:"Send an email"},
    partners:{kicker:"PARTNERS / SPONSORS",title:["Sponsors wanted:","not only the event."],intro:"RBA is currently welcoming sponsors and partners who want their support to become safer gyms, better learning opportunities and meaningful exchange across regions.",section:"PARTNERSHIP PRINCIPLES",sectionTitle:"A clear purpose. A visible use. A responsible story.",sectionCopy:"We define what support enables, where the partner is presented and how children and families are protected. We do not promise inflated reach or use youth images without appropriate consent.",cards:[["01","PROGRAMME SUPPORT","Court, travel, equipment and participation support tied to a specific project."],["02","LOCAL PARTNER","A regional organisation helping make a clinic or camp possible."],["03","KNOWLEDGE PARTNER","Medical, S&C, education or safeguarding expertise that improves quality."],["04","LONG-TERM ALLIANCE","A multi-project relationship built around shared development standards."]],closing:"Build the right partnership",closingCopy:"Tell us what your organisation values and what kind of impact you want to support.",primary:"Discuss partnership",secondary:"About RBA"},
    contact:{kicker:"CONTACT RBA",title:["Start with the","real question."],intro:"Choose the channel that matches your purpose. You do not need a finished plan before contacting us.",section:"DIRECT CONTACT",sectionTitle:"One clear next step.",sectionCopy:"For clinics and estimates, the request page collects the information needed for a useful first reply. For international exchange or partnerships, WhatsApp or email is the fastest starting point.",cards:[["01","CLINIC REQUEST","Venue, dates, age group, player count and development question."],["02","JAPAN–ASIA EXCHANGE","Organisation, player ages, timing and learning purpose."],["03","PARTNERSHIP","The project, community or development environment you want to support."],["04","GENERAL ENQUIRY","A concise question and the best way to reply."]],closing:"Riot Basketball Academy",closingCopy:"Sendai, Japan · Representative: Masato Nishio · riot.training.base@gmail.com",primary:"Email RBA",secondary:"WhatsApp RBA"}
  },
  ja:{
    about:{kicker:"RBAについて",title:["現場からつくる、","育成組織。"],intro:"Riot Basketball Academyは仙台を拠点に、日本各地とアジアで活動する育成年代のバスケットボール組織です。選手育成、S&C、指導者の学び、国際交流を一つの流れとしてつなげています。",section:"組織概要",sectionTitle:"理念を、現場で形にする。",sectionCopy:"地域ごとの環境や声に耳を傾け、本当に必要な育成課題を見極めたうえで、現場を支える方々と一緒にプログラムを組み立てます。代表の西尾優人が全体の方針と責任を担い、指導者、専門家、地域の主催者、海外パートナーと連携しています。",cards:[["01","選手育成","状況を見る力、判断する力、タイミング、スペーシング、基礎技術。"],["02","S&C","身体づくり、負荷管理、回復、長期的な健康。"],["03","指導者の学び","観察、練習設計、信頼できる指導者との直接対話。"],["04","アジア連携","共通の育成課題、明確な役割、安全への配慮を軸にした交流。"]],closing:"RBAの育成方針へ",closingCopy:"U12からU15まで、何を優先し、なぜ大切にするのかを明確にしています。",primary:"育成方針を読む",secondary:"RBAに相談する"},
    approach:{kicker:"育成方針",title:["見る。選ぶ。実行する。","そして、振り返る。"],intro:"スキルとは、できる技の数ではありません。試合の状況を読み取り、その瞬間に必要なプレーを選び、実行できる力です。",section:"選手を育成の中心に置く",sectionTitle:"指導者の都合ではなく、選手の成長を中心に。",sectionCopy:"年代に応じて、見る・判断する・実行する力を、試合で発揮できる形から逆算して育てます。早い段階で役割を固定せず、失敗を次の判断に生かす材料として捉え、練習の目的も子どもたちと共有します。",cards:[["01","見る","スペース、相手、味方、タイミングを捉える。"],["02","選ぶ","変化する試合状況の中で、必要な解決策を選ぶ。"],["03","実行する","プレーの目的とチームへの責任を意識して、技術を使う。"],["04","振り返る","結果を理解し、修正し、失敗を恐れずもう一度試す。"]],closing:"現場へ取り入れる",closingCopy:"対象年代、地域、現在の育成課題をお知らせください。状況に合わせてプログラムをご提案します。",primary:"クリニック開催を相談",secondary:"開催日程を見る"},
    asia:{kicker:ui("ja","access"),title:["日本のバスケットボールとつながるための、","最初の相談窓口。"],intro:"一般的な観光ツアーではなく、日本で意味のある学びや交流を求めるアジアのアカデミー、チーム、指導者、ご家族のための窓口です。",section:"一つの窓口で、4つのことを確認",sectionTitle:"誰が、何を学びたいのか。",sectionCopy:"団体名、対象年代、希望時期、学びの目的を教えてください。実現できるかどうか、双方の役割、必要な準備、次の一歩を一緒に整理します。",cards:[["01","日本でのクリニック","年代と育成課題に合わせた、1日または複数日のRBAプログラム。"],["02","アカデミー交流","役割と安全基準を明確にした合同練習、見学、対話。"],["03","指導者交流","現場研修、オンラインでの事前準備、育成・S&Cの振り返り。"],["04","地域とのつながり","目的に合うかを確認したうえで、人・場所・機会へつなぎます。"]],closing:"自分の言語で相談する",closingCopy:"日本語、英語、繁體中文、韓国語でお問い合わせいただけます。",primary:"WhatsAppで相談",secondary:"メールを送る"},
    partners:{kicker:"協賛・パートナー",title:["スポンサー募集中。","育成環境を支える。"],intro:"RBAでは現在、活動を継続的に支えてくださるスポンサー・協力企業を募集しています。ご支援を安全な現場、学びの機会、地域とアジアの交流に変えたい企業・団体と連携します。",section:"連携の原則",sectionTitle:"目的、使途、発信を明確に。",sectionCopy:"何を実現する支援か、どこで企業名を掲出するか、子どもと家庭をどう守るかを事前に整理します。数字を誇張せず、同意のない子どもの画像を利用しません。",cards:[["01","プログラム支援","会場、移動、備品、参加機会など特定企画への支援。"],["02","地域パートナー","地域でクリニックやキャンプを成立させる連携。"],["03","専門パートナー","医療、S&C、教育、安全管理の知見で質を高める。"],["04","長期連携","共通の育成基準に基づき複数企画を育てる関係。"]],closing:"スポンサーとしてRBAと育成環境をつくる",closingCopy:"企業・団体として大切にしている価値と、支援したい地域・活動をお聞かせください。単発協賛から継続的な連携までご相談いただけます。",primary:"協賛を相談",secondary:"RBAについて"},
    contact:{kicker:"お問い合わせ",title:["まずは、いま抱えている課題を","聞かせてください。"],intro:"目的に合う連絡先をお選びください。企画がまだ固まっていなくてもご相談いただけます。",section:"直接連絡",sectionTitle:"次の一歩を、分かりやすく。",sectionCopy:"クリニック開催と見積もりは専用ページから、海外交流や協賛についてはWhatsAppまたはメールからご連絡ください。必要な情報を整理したうえで、スムーズにご案内します。",cards:[["01","クリニック開催","会場、日程、年代、人数、育成課題。"],["02","海外交流","団体名、対象年代、希望時期、学びの目的。"],["03","協賛・連携","支援したい企画、地域、育成環境。"],["04","その他","ご質問と、ご希望の返信方法をお知らせください。"]],closing:"Riot Basketball Academy",closingCopy:"宮城県仙台市 · 代表 西尾優人 · riot.training.base@gmail.com",primary:"メールを送る",secondary:"WhatsAppで相談"}
  },
  "zh-tw":{
    about:{kicker:"關於RBA",title:["從真實球場出發的，","青少年培育機構。"],intro:"Riot Basketball Academy以日本仙台為基地，連結日本各地與亞洲，整合球員發展、體能訓練、教練學習與國際交流。",section:"組織介紹",sectionTitle:"先有現場，再談口號。",sectionCopy:"RBA先理解在地環境與真正的培育問題，再依據負責當地的人與條件設計活動。代表西尾優人負責方向與責任，並與教練、專業人員、地方主辦者及海外夥伴合作。",cards:[["01","球員發展","情境閱讀、決策、節奏、空間與基本功。"],["02","體能訓練","科學化準備、負荷管理、恢復與長期健康。"],["03","教練學習","觀察、課程設計與可信賴教練的直接交流。"],["04","亞洲網絡","以共同工作、清楚角色與兒少安全為基礎的關係。"]],closing:"了解RBA的培育方法",closingCopy:"從U12到U15，我們清楚說明優先事項與背後原因。",primary:"閱讀培育理念",secondary:"聯絡RBA"},
    approach:{kicker:"培育理念",title:["觀察。選擇。執行。","再反思。"],intro:"技術不是動作數量，而是理解比賽需要，並在正確時機完成正確行動的能力。",section:"以球員為主體",sectionTitle:"讓球員，而不是教練，成為學習中心。",sectionCopy:"RBA依年齡從情境閱讀、選擇與比賽轉化設計練習。不過早限制位置，把錯誤視為資訊，並讓球員理解每項任務的目的。",cards:[["01","觀察","讀取空間、對手、隊友與時機。"],["02","選擇","選出真實比賽當下需要的解法。"],["03","執行","帶著目的與團隊責任運用技術。"],["04","反思","理解結果、做出調整並再次嘗試。"]],closing:"把理念帶進您的環境",closingCopy:"請告訴我們年齡層、地點與培育課題，我們將設計可行方案。",primary:"邀請RBA",secondary:"查看日程"},
    asia:{kicker:ui("zh-tw","access"),title:["連結日本籃球的，","第一個實務窗口。"],intro:"為希望與日本建立真正學習關係的亞洲學院、球隊、教練與家庭服務，而不是一般運動觀光行程。",section:"一個窗口・四個問題",sectionTitle:"球員是誰？希望學到什麼？",sectionCopy:"請告訴我們單位、球員年齡、希望時間與學習目的。RBA將說明可行性、雙方責任與下一步。",cards:[["01","日本訓練營","依年齡與情境設計的單日或多日RBA課程。"],["02","學院交流","角色清楚並重視安全的共同訓練、觀察與對話。"],["03","教練學習","現場研修、線上準備，以及培育與體能反思。"],["04","在地連結","確認適合後，介紹相關人員、場地與機會。"]],closing:"使用您的語言聯絡",closingCopy:"可使用英語、日語、繁體中文與韓語洽詢。",primary:"WhatsApp洽詢",secondary:"寄送電郵"},
    partners:{kicker:"合作夥伴／贊助",title:["支持培育環境，","不只支持單次活動。"],intro:"RBA與希望將支持轉化為安全球場、學習機會及跨地區交流的企業與團體合作。",section:"合作原則",sectionTitle:"目的清楚、用途透明、發信負責。",sectionCopy:"我們事前確認支持能完成什麼、品牌如何呈現，以及如何保護兒少與家庭。不誇大觸及人數，也不使用未取得同意的兒少影像。",cards:[["01","活動支持","場地、交通、器材及參與機會等特定企劃支持。"],["02","地方夥伴","協助在地訓練營與活動實現。"],["03","知識夥伴","醫療、體能、教育與安全專業提升活動品質。"],["04","長期合作","依共同培育標準推動多個企劃。"]],closing:"建立合適的合作關係",closingCopy:"請告訴我們貴單位重視的價值，以及希望支持的影響。",primary:"洽談合作",secondary:"關於RBA"},
    contact:{kicker:"聯絡RBA",title:["從真正的問題，","開始對話。"],intro:"請選擇符合目的的聯絡方式。即使計畫尚未完成，也可以先詢問。",section:"直接聯絡",sectionTitle:"讓下一步更清楚。",sectionCopy:"訓練營與報價可從專用頁面開始；日本交流或合作夥伴建議使用WhatsApp或電郵。",cards:[["01","訓練營邀約","場地、日期、年齡、人數與培育課題。"],["02","日本交流","單位、球員年齡、時間與學習目的。"],["03","合作贊助","希望支持的企劃、社區或培育環境。"],["04","一般詢問","簡要問題與方便回覆的方式。"]],closing:"Riot Basketball Academy",closingCopy:"日本仙台 · 代表 西尾優人 · riot.training.base@gmail.com",primary:"寄送電郵",secondary:"WhatsApp洽詢"}
  },
  ko:{
    about:{kicker:"RBA 소개",title:["실제 코트에서 만들어진","유소년 육성 기관."],intro:"Riot Basketball Academy는 일본 센다이를 기반으로 일본 각지와 아시아에서 선수 육성, S&C, 코치 학습과 국제 교류를 연결합니다.",section:"기관 소개",sectionTitle:"슬로건보다 먼저 현장과 구조.",sectionCopy:"RBA는 지역 환경을 듣고 실제 육성 과제를 파악한 뒤 현장의 사람과 조건에 맞춰 프로그램을 설계합니다. 대표 Masato Nishio가 방향과 책임을 맡고 코치, 전문가, 지역 주최자 및 해외 파트너와 협력합니다.",cards:[["01","선수 육성","인지, 판단, 타이밍, 공간과 기본기."],["02","S&C","과학적 준비, 부하 관리, 회복과 장기 건강."],["03","코치 학습","관찰, 훈련 설계와 신뢰할 수 있는 코치와의 직접 대화."],["04","아시아 네트워크","공동 과제, 명확한 역할과 아동 보호에 기반한 관계."]],closing:"RBA의 육성 방식을 확인하세요",closingCopy:"U12부터 U15까지 무엇을 우선하고 왜 그렇게 하는지 설명합니다.",primary:"육성 철학 읽기",secondary:"RBA 문의"},
    approach:{kicker:"육성 철학",title:["보고. 선택하고. 실행하고.","다시 돌아봅니다."],intro:"기술은 동작의 개수가 아닙니다. 경기가 요구하는 것을 인식하고 올바른 순간에 필요한 행동을 수행하는 능력입니다.",section:"선수 중심 설계",sectionTitle:"코치가 아닌 선수를 학습의 중심에.",sectionCopy:"RBA는 인지, 선택과 경기 전이를 중심으로 연령에 맞는 훈련을 설계합니다. 이른 포지션 제한을 피하고 실수를 정보로 다루며 각 과제의 목적을 선수에게 설명합니다.",cards:[["01","보기","공간, 상대, 동료와 타이밍을 읽습니다."],["02","선택하기","실제 경기 상황에 필요한 해결책을 선택합니다."],["03","실행하기","목적과 팀에 대한 책임을 가지고 기술을 사용합니다."],["04","돌아보기","결과를 이해하고 수정하며 다시 시도합니다."]],closing:"당신의 환경에 적용하세요",closingCopy:"연령, 장소와 육성 과제를 알려 주시면 현실적인 프로그램을 설계합니다.",primary:"클리닉 요청",secondary:"일정 보기"},
    asia:{kicker:ui("ko","access"),title:["일본 농구와 연결되는","실질적인 첫 창구."],intro:"일반 스포츠 관광이 아닌, 일본과 의미 있는 학습 관계를 원하는 아시아의 아카데미, 팀, 지도자와 가족을 위한 창구입니다.",section:"하나의 창구・네 가지 질문",sectionTitle:"선수는 누구이며 무엇을 배우고 싶은가?",sectionCopy:"단체, 선수 연령, 희망 시기와 학습 목적을 알려 주세요. 가능성, 양측의 책임과 다음 단계를 명확히 안내합니다.",cards:[["01","일본 클리닉","연령과 환경에 맞춘 하루 또는 다일 RBA 프로그램."],["02","아카데미 교류","명확한 역할과 안전 기준 아래 공동 훈련, 관찰과 대화."],["03","코치 학습","현장 학습, 온라인 준비와 육성·S&C 성찰."],["04","지역 연결","목적과 적합성을 확인한 뒤 관련 사람과 장소를 연결."]],closing:"당신의 언어로 문의하세요",closingCopy:"영어, 일본어, 번체 중국어와 한국어 문의를 받습니다.",primary:"WhatsApp 상담",secondary:"이메일 보내기"},
    partners:{kicker:"파트너 / 스폰서",title:["행사뿐 아니라","성장 환경을 지원합니다."],intro:"RBA는 지원을 안전한 체육관, 더 나은 학습 기회와 지역 간 교류로 만들고 싶은 기업 및 단체와 협력합니다.",section:"파트너십 원칙",sectionTitle:"명확한 목적, 투명한 사용, 책임 있는 이야기.",sectionCopy:"지원이 무엇을 가능하게 하는지, 브랜드를 어디에 소개하는지, 아이와 가족을 어떻게 보호하는지 사전에 정리합니다. 도달 수치를 과장하거나 동의 없는 아동 이미지를 사용하지 않습니다.",cards:[["01","프로그램 지원","특정 프로젝트의 코트, 이동, 장비와 참가 기회 지원."],["02","지역 파트너","지역 클리닉과 캠프를 함께 실현하는 협력."],["03","지식 파트너","의료, S&C, 교육 및 안전 전문성으로 품질 향상."],["04","장기 협력","공동 육성 기준을 바탕으로 여러 프로젝트를 성장시키는 관계."]],closing:"적합한 파트너십을 만드세요",closingCopy:"중요하게 생각하는 가치와 지원하고 싶은 환경을 알려 주세요.",primary:"파트너십 상담",secondary:"RBA 소개"},
    contact:{kicker:"RBA 문의",title:["진짜 질문에서","대화를 시작하세요."],intro:"목적에 맞는 연락 방법을 선택하세요. 계획이 완성되지 않아도 문의할 수 있습니다.",section:"직접 연락",sectionTitle:"다음 단계를 명확하게.",sectionCopy:"클리닉 및 견적은 전용 요청 페이지에서, 일본 교류 또는 파트너십은 WhatsApp이나 이메일에서 시작하면 가장 빠릅니다.",cards:[["01","클리닉 요청","장소, 일정, 연령, 인원과 육성 과제."],["02","일본 교류","단체, 선수 연령, 시기와 학습 목적."],["03","파트너십","지원하고 싶은 프로젝트, 지역 또는 성장 환경."],["04","일반 문의","간단한 질문과 편한 회신 방법."]],closing:"Riot Basketball Academy",closingCopy:"일본 센다이 · 대표 Masato Nishio · riot.training.base@gmail.com",primary:"이메일 보내기",secondary:"WhatsApp 상담"}
  }
};

const languagePage:Record<Kind,LanguagePage>={about:"about",approach:"approach",asia:"asia",partners:"partners",contact:"contact"};

export function LocalizedCorePage({locale,kind}:{locale:Locale;kind:Kind}){
  const c=copy[locale][kind];
  const message=locale==="ja"?"RBAへ相談です。":locale==="zh-tw"?"您好RBA，我想進一步洽詢。":locale==="ko"?"안녕하세요 RBA. 상담하고 싶습니다.":"Hello RBA, I would like to discuss a project.";
  const whatsapp="https://wa.me/818032483703?text="+encodeURIComponent(message);
  const primaryHref=kind==="about"?localePath(locale,"approach"):kind==="approach"?localePath(locale,"clinic-request"):kind==="partners"?localePath(locale,"contact"):kind==="contact"?contactFormUrl:whatsapp;
  const secondaryHref=kind==="about"?localePath(locale,"contact"):kind==="approach"?localePath(locale,"schedule"):kind==="partners"?localePath(locale,"about"):kind==="contact"?whatsapp:"mailto:riot.training.base@gmail.com";
  return <div lang={locale==="zh-tw"?"zh-Hant-TW":locale}><SiteFrame locale={locale} languagePage={languagePage[kind]}>
    <section className="inner-hero section-pad"><a className="back-link" href={localePath(locale)}>← RBA</a><p className="section-index">{c.kicker}</p><h1>{c.title[0]}<br/>{c.title[1]}</h1><p>{c.intro}</p></section>
    <section className="access-promise section-pad"><p className="section-index">{c.section}</p><div><h2>{c.sectionTitle}</h2><p>{c.sectionCopy}</p></div></section>
    <section className="access-grid section-pad">{c.cards.map(([n,t,b])=><article key={n}><span>{n} / {t}</span><p>{b}</p></article>)}</section>
    {kind==="contact"&&<ContactForm locale={locale}/>}
    {kind==="contact"&&<section className="partner-call section-pad"><div><p className="section-index inverse">{ui(locale,"channels")}</p><h2>RBA / SENDAI</h2><p>{c.closingCopy}</p></div><div className="partner-contact-grid"><a href="mailto:riot.training.base@gmail.com"><Mail size={24}/><span>{ui(locale,"email")}</span><strong>riot.training.base@gmail.com</strong></a><a href={whatsapp} target="_blank" rel="noreferrer"><MessageCircle size={24}/><span>WHATSAPP</span><strong>+81 80 3248 3703</strong></a><a href={localePath(locale,"clinic-request")}><ArrowUpRight size={24}/><span>{ui(locale,"request")}</span><strong>{c.cards[0][1]}</strong></a></div></section>}
    <section className="closing-cta section-pad"><p className="eyebrow">{c.kicker}</p><h2>{c.closing}</h2><p>{c.closingCopy}</p><div className="closing-actions"><a className="button button-orange" href={primaryHref} target={primaryHref.startsWith("http")?"_blank":undefined} rel={primaryHref.startsWith("http")?"noreferrer":undefined}>{kind==="contact"?({en:"Open enquiry form",ja:"お問い合わせフォーム", "zh-tw":"開啟查詢表單",ko:"문의 양식 열기"}[locale]):c.primary}<ArrowRight size={17}/></a><a className="button button-dark" href={secondaryHref} target={secondaryHref.startsWith("http")?"_blank":undefined} rel={secondaryHref.startsWith("http")?"noreferrer":undefined}>{c.secondary}<ArrowUpRight size={17}/></a></div></section>
  </SiteFrame></div>;
}