import { ui } from "./ui-copy";
import { ArrowUpRight, Camera, MessageCircle } from "lucide-react";
import { SiteFrame } from "@/components/site-frame";
type Locale="en"|"ja"|"zh-tw"|"ko";
const copy={
 en:{kicker:"Official channels",title:<>See the field.<br/>Join the conversation.</>,intro:"Follow RBA's clinics, camps and development work, understand the thinking behind each programme and join the conversation.",igRole:"See the field",ig:"Clinics, camps, practice environments and the people supporting youth development.",thRole:"Join the conversation",th:"Observations and questions about coaching, youth development, players and families.",open:"Open",start:"Choose your next step",calendar:"Find the next programme",note:"Read development articles"},
 ja:{kicker:"公式チャンネル",title:<>活動を知り、<br />育成を一緒に考える。</>,intro:"RBAのSNSでは、活動の様子だけでなく、その背景にある育成の考え方や現場で生まれた問いも発信しています。",igRole:"RBAの活動を見る",ig:"クリニック、キャンプ、練習環境、活動を支える人々。RBAの現場で起きていることをお届けします。",thRole:"育成について考える",th:"育成、指導、選手と保護者を取り巻く環境について、日々の気づきや問いを共有します。",open:"開く",start:"自分に合う入口から始める",calendar:"次のクリニックを見る",note:"育成についての記事を読む"},
 "zh-tw":{kicker:"04 / 社群平台",title:<>看見現場，<br />參與討論。</>,intro:"RBA的社群平台不只呈現活動成果，更公開分享訓練現場、青少年培育理念，以及值得共同思考的問題。",igRole:"看見訓練現場",ig:"分享訓練營、移地活動、練習環境，以及投入青少年培育的人們。",thRole:"參與培育討論",th:"分享關於青少年培育、教練工作，以及球員與家庭環境的觀察與提問。",open:"前往",start:"選擇最適合您的入口",calendar:"查看近期活動",note:"閱讀培育觀點"},
 ko:{kicker:"04 / 소셜 허브",title:<>현장을 보고,<br />대화에 참여하세요.</>,intro:"RBA의 소셜 채널은 결과만 보여 주는 공간이 아닙니다. 실제 활동과 그 배경에 있는 육성 철학을 공유하고 함께 이야기하는 공개 기록입니다.",igRole:"훈련 현장 보기",ig:"클리닉과 캠프, 훈련 환경, 그리고 현장에서 유소년 육성을 만들어 가는 사람들의 모습을 전합니다.",thRole:"육성에 대해 대화하기",th:"유소년 육성과 코칭, 선수와 보호자를 둘러싼 환경에 대한 관찰과 질문을 나눕니다.",open:"바로가기",start:"목적에 맞는 채널에서 시작하세요",calendar:"다음 프로그램 보기",note:"육성 철학 읽기"}
} as const;
export function LocalizedSocial({locale}:{locale:Locale}){const c=copy[locale];const cards=[{name:"Instagram",role:c.igRole,copy:c.ig,href:"https://www.instagram.com/riot.basketball.academy/",Icon:Camera},{name:"Threads",role:c.thRole,copy:c.th,href:"https://www.threads.com/@riot.basketball.academy",Icon:MessageCircle}];return <div lang={locale==="zh-tw"?"zh-Hant-TW":locale}><SiteFrame locale={locale} languagePage="social"><section className="inner-hero section-pad"><a className="back-link" href={locale==="en"?"/":`/${locale}`}><span>←</span> RBA</a><p className="section-index">{c.kicker}</p><h1>{c.title}</h1><p>{c.intro}</p></section><section className="social-channels section-pad">{cards.map(({name,role,copy,href,Icon})=><article key={name}><div className="social-channel-top"><Icon size={34}/><span>{role}</span></div><h2>{name}</h2><p className="social-handle">@riot.basketball.academy</p><p className="social-copy">{copy}</p><a className="button button-dark" href={href} target="_blank" rel="noreferrer">{c.open} {name}<ArrowUpRight size={17}/></a></article>)}</section><section className="social-start section-pad"><div><p className="section-index">{ui(locale,"start")}</p><h2>{c.start}</h2></div><div className="social-start-links"><a href={locale==="en"?"/schedule":`/${locale}/schedule`}><span>{ui(locale,"family")}</span><strong>{c.calendar}</strong><ArrowUpRight size={19}/></a><a href="https://note.com/rba_official" target="_blank" rel="noreferrer"><span>{ui(locale,"coaches")}</span><strong>{c.note}</strong><ArrowUpRight size={19}/></a></div></section></SiteFrame></div>}