"use client";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { Bell, CalendarDays, CheckCircle2, ChevronRight, ClipboardList, CreditCard, House, LoaderCircle, LogOut, Menu, Plus, ShieldCheck, StickyNote, UserRound, Users } from "lucide-react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
import type { Locale } from "./site-frame";
import { MemberJourney } from "./member-journey";
import { CalendarImport } from "./calendar-import";

type Profile={id:string;role:"player"|"parent"|"coach"|"admin";display_name:string|null;preferred_language:string;timezone:string;onboarding_completed:boolean};
type UserRole={role:string;status:string};
type Team={id:string;name:string;category:string;gender:string;region:string|null;timezone:string;created_by:string};
type Membership={id:string;team_id:string;member_role:string;status:string;teams:Team|null};
type TeamEvent={id:string;team_id:string;event_type:string;title:string;starts_at:string;ends_at:string|null;venue:string|null;items_to_bring:string|null;fee_amount:number|null;availability_status:string};
type Notice={id:string;team_id:string;title:string;body:string;priority:string;published_at:string};
type Note={id:string;team_id:string|null;body:string;pinned:boolean;created_at:string};
type Collection={id:string;team_id:string;title:string;amount:number;currency:string;due_at:string|null;status:string};
type Order={id:string;order_type:string;status:string;amount_total:number|null;currency:string;created_at:string};
type Subscription={id:string;status:string;plan_key:string;current_period_end:string|null;cancel_at_period_end:boolean};
type AppData={profile:Profile|null;roles:UserRole[];memberships:Membership[];events:TeamEvent[];notices:Notice[];notes:Note[];collections:Collection[];orders:Order[];subscriptions:Subscription[]};
type AdminStats={members:number;teams:number;entities:number;offers:number;orders:number;transactions:number;volume:number;events:number};

const copy={
  ja:{home:"ホーム",calendar:"カレンダー",team:"チーム",notifications:"お知らせ",my:"MY",today:"今日やること",noToday:"今日の予定はありません。次の予定を確認しましょう。",next:"次の予定",tasks:"未対応",welcome:"RBA IDの初期設定",name:"表示名",primary:"最初に開くホーム",save:"設定して始める",teamTitle:"TEAM HOME",createTeam:"チームを登録",join:"招待コードで参加",teamName:"チーム名",category:"カテゴリー",code:"招待コード",create:"登録する",joinAction:"参加する",noTeam:"まだチームに参加していません。コーチはチームを登録し、選手・保護者は招待コードから参加できます。",addEvent:"予定を追加",eventTitle:"予定名",eventType:"種類",starts:"開始",venue:"場所",add:"追加する",notes:"簡易メモ",notePlaceholder:"今日の確認事項や練習後の振り返り",addNote:"保存",roles:"利用する役割",addRole:"役割を追加",signout:"ログアウト",loading:"読み込み中",error:"処理を完了できませんでした。もう一度お試しください。",paid:"支払い・集金",safe:"未成年者と成人が、制限なく直接やり取りできる機能は設けていません。チーム内の権限と保護者の同意を前提に運用します。",business:"RBA NETWORK",businessBody:"大会、国内外の交流、遠征、施設、人材に関する情報は、条件を確認できたものだけ公開します。",united:"RBA UNITED",connect:"RBA CONNECT",organizer:"ORGANIZER",coachDesk:"COACH HOME",coachDeskBody:"今日の練習、出欠、連絡事項、集金を一つの画面で確認できます。",memberStatus:"会員ステータス",freeMember:"RBA ID",paidMember:"RBA HOMECOURT",verified:"決済確認済み",setup:"初期設定",complete:"完了",nextStep:"次にやること",setupTeamCoach:"最初のチームを登録すると、予定・出欠・連絡をまとめて管理できます。",setupTeamMember:"チームから届いた招待コードを入力すると、予定とお知らせを確認できます。",goTeam:"TEAM HOMEを設定",account:"アカウント設定",timezone:"タイムゾーン",profileSaved:"プロフィールを更新しました",saveProfile:"プロフィールを保存",membershipDetails:"会員プランを見る",recentNotice:"最新のお知らせ",noNotice:"新しいお知らせはありません。"},
  en:{home:"Home",calendar:"Calendar",team:"Team",notifications:"Notifications",my:"My",today:"What you need today",noToday:"Nothing scheduled today. Check what is next.",next:"Next",tasks:"Open items",welcome:"Set up your RBA ID",name:"Display name",primary:"Your first HOME",save:"Save and start",teamTitle:"TEAM HOME",createTeam:"Register a team",join:"Join with code",teamName:"Team name",category:"Category",code:"Invite code",create:"Create",joinAction:"Join",noTeam:"You have not joined a team. Coaches can register one; players and parents can use an invite code.",addEvent:"Add schedule",eventTitle:"Title",eventType:"Type",starts:"Starts",venue:"Venue",add:"Add",notes:"Quick notes",notePlaceholder:"Today’s task or post-practice reflection",addNote:"Save",roles:"Active roles",addRole:"Add role",signout:"Sign out",loading:"Loading",error:"We could not complete that action. Please try again.",paid:"Payments",safe:"There is no unrestricted adult-to-minor DM. Team permissions and guardian consent come first.",business:"RBA NETWORK",businessBody:"Tournaments, exchange, trips, facilities and staffing are request-based until availability is confirmed.",united:"RBA UNITED",connect:"RBA CONNECT",organizer:"ORGANIZER",coachDesk:"COACH HOME",coachDeskBody:"Practice, attendance, communication and collections in one daily workspace.",memberStatus:"Membership",freeMember:"RBA ID",paidMember:"RBA HOMECOURT",verified:"Payment confirmed",setup:"Setup",complete:"complete",nextStep:"Next step",setupTeamCoach:"Register your first team to manage schedules, attendance and notices in one place.",setupTeamMember:"Enter the invite code from your team to see schedules and notices.",goTeam:"Set up TEAM HOME",account:"Account settings",timezone:"Time zone",profileSaved:"Profile updated",saveProfile:"Save profile",membershipDetails:"View membership plans",recentNotice:"Latest notice",noNotice:"No new notices."},
  "zh-tw":{home:"首頁",calendar:"日曆",team:"團隊",notifications:"通知",my:"MY",today:"今天需要處理",noToday:"今天沒有預定。請查看下一個行程。",next:"下一個",tasks:"待處理",welcome:"設定RBA ID",name:"顯示名稱",primary:"第一個HOME",save:"儲存並開始",teamTitle:"TEAM HOME",createTeam:"登錄團隊",join:"使用邀請碼加入",teamName:"團隊名稱",category:"類別",code:"邀請碼",create:"登錄",joinAction:"加入",noTeam:"尚未加入團隊。教練可登錄團隊；球員與家長可使用邀請碼。",addEvent:"新增行程",eventTitle:"名稱",eventType:"類型",starts:"開始",venue:"地點",add:"新增",notes:"快速備忘",notePlaceholder:"今天的事項或訓練後回顧",addNote:"儲存",roles:"使用角色",addRole:"新增角色",signout:"登出",loading:"載入中",error:"無法完成。請重試。",paid:"付款・收款",safe:"成人與未成年者不能無限制私訊。以團隊權限與家長同意為前提。",business:"RBA NETWORK",businessBody:"大會、交流、遠征、設施與人力在確認前皆標示為需要申請。",united:"RBA UNITED",connect:"RBA CONNECT",organizer:"ORGANIZER",coachDesk:"COACH HOME",coachDeskBody:"訓練、出席、通知與收款集中在每日工作區。",memberStatus:"會員狀態",freeMember:"RBA ID",paidMember:"RBA HOMECOURT",verified:"已確認付款",setup:"使用準備",complete:"完成",nextStep:"下一步",setupTeamCoach:"登錄第一個團隊後，即可集中管理行程、出席與通知。",setupTeamMember:"輸入團隊提供的邀請碼，即可查看行程與通知。",goTeam:"設定TEAM HOME",account:"帳戶設定",timezone:"時區",profileSaved:"個人資料已更新",saveProfile:"儲存個人資料",membershipDetails:"查看會員方案",recentNotice:"最新通知",noNotice:"沒有新通知。"},
  ko:{home:"홈",calendar:"캘린더",team:"팀",notifications:"알림",my:"MY",today:"오늘 필요한 것",noToday:"오늘 일정이 없습니다. 다음 일정을 확인하세요.",next:"다음",tasks:"미처리",welcome:"RBA ID 설정",name:"표시 이름",primary:"첫 HOME",save:"저장하고 시작",teamTitle:"TEAM HOME",createTeam:"팀 등록",join:"초대 코드로 참가",teamName:"팀 이름",category:"카테고리",code:"초대 코드",create:"등록",joinAction:"참가",noTeam:"아직 팀에 참가하지 않았습니다. 코치는 팀을 등록하고 선수·보호자는 초대 코드를 사용할 수 있습니다.",addEvent:"일정 추가",eventTitle:"일정명",eventType:"종류",starts:"시작",venue:"장소",add:"추가",notes:"간단 메모",notePlaceholder:"오늘 확인할 일 또는 훈련 후 회고",addNote:"저장",roles:"사용 역할",addRole:"역할 추가",signout:"로그아웃",loading:"불러오는 중",error:"처리하지 못했습니다. 다시 시도하세요.",paid:"결제・회비",safe:"성인과 미성년자의 무제한 DM은 없습니다. 팀 권한과 보호자 동의를 우선합니다.",business:"RBA NETWORK",businessBody:"대회, 교류, 원정, 시설과 인력은 확인 전까지 요청 필요로 표시합니다.",united:"RBA UNITED",connect:"RBA CONNECT",organizer:"ORGANIZER",coachDesk:"COACH HOME",coachDeskBody:"훈련, 출석, 연락과 회비를 하나의 일터에서 확인합니다.",memberStatus:"회원 상태",freeMember:"RBA ID",paidMember:"RBA HOMECOURT",verified:"결제 확인 완료",setup:"이용 준비",complete:"완료",nextStep:"다음 단계",setupTeamCoach:"첫 팀을 등록하면 일정, 출석, 공지를 한곳에서 관리할 수 있습니다.",setupTeamMember:"팀에서 받은 초대 코드를 입력하면 일정과 공지를 볼 수 있습니다.",goTeam:"TEAM HOME 설정",account:"계정 설정",timezone:"시간대",profileSaved:"프로필을 업데이트했습니다",saveProfile:"프로필 저장",membershipDetails:"회원 플랜 보기",recentNotice:"최근 공지",noNotice:"새 공지가 없습니다."}
} as const;

const empty:AppData={profile:null,roles:[],memberships:[],events:[],notices:[],notes:[],collections:[],orders:[],subscriptions:[]};
const navSections=["home","calendar","team","notifications","my","admin"] as const;
const practiceCopy={
  ja:{practice:"練習を登録",theme:"テーマ",objective:"目的",menu:"メニュー（1行に1項目）",people:"参加予定人数",courts:"コート数",equipment:"必要物品",coachNotes:"コーチメモ",save:"練習計画を保存",attend:"参加",absent:"欠席",undecided:"未定",saved:"出欠を保存しました"},
  en:{practice:"Add practice",theme:"Theme",objective:"Objective",menu:"Menu (one item per line)",people:"Expected players",courts:"Courts",equipment:"Equipment",coachNotes:"Coach note",save:"Save practice plan",attend:"Going",absent:"Absent",undecided:"Undecided",saved:"Attendance saved"},
  "zh-tw":{practice:"登錄訓練",theme:"主題",objective:"目的",menu:"菜單（每行一項）",people:"預計人數",courts:"球場數",equipment:"所需物品",coachNotes:"教練備忘",save:"儲存訓練計畫",attend:"參加",absent:"缺席",undecided:"未定",saved:"已儲存出席"},
  ko:{practice:"훈련 등록",theme:"테마",objective:"목적",menu:"메뉴(한 줄에 한 항목)",people:"예상 인원",courts:"코트 수",equipment:"필요 물품",coachNotes:"코치 메모",save:"훈련 계획 저장",attend:"참가",absent:"불참",undecided:"미정",saved:"출석을 저장했습니다"}
} as const;

const dateKeyFormatters=new Map<string,Intl.DateTimeFormat>();
function dateKey(value:Date,timeZone:string){
  let formatter=dateKeyFormatters.get(timeZone);
  if(!formatter){formatter=new Intl.DateTimeFormat("en-CA",{timeZone,year:"numeric",month:"2-digit",day:"2-digit"});dateKeyFormatters.set(timeZone,formatter);}
  return formatter.format(value);
}

function zonedInputToIso(value:string,timeZone:string){
  const match=/^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2})$/.exec(value);
  if(!match)throw new Error("Invalid date and time");
  const target=Date.UTC(Number(match[1]),Number(match[2])-1,Number(match[3]),Number(match[4]),Number(match[5]));
  let utc=target;
  const formatter=new Intl.DateTimeFormat("en-CA",{timeZone,year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",second:"2-digit",hourCycle:"h23"});
  for(let i=0;i<2;i++){
    const parts=Object.fromEntries(formatter.formatToParts(new Date(utc)).filter(part=>part.type!=="literal").map(part=>[part.type,part.value]));
    const shown=Date.UTC(Number(parts.year),Number(parts.month)-1,Number(parts.day),Number(parts.hour),Number(parts.minute),Number(parts.second));
    utc-=shown-target;
  }
  return new Date(utc).toISOString();
}

function roleStatusLabel(status:string,locale:Locale){
  if(locale!=="ja")return status.toUpperCase();
  return ({active:"利用中",pending:"確認中",suspended:"利用停止中",revoked:"無効"} as Record<string,string>)[status]||status;
}

export function MemberApp({locale,section,userId,email}:{locale:Locale;section:string;userId:string;email:string}){
  const c=locale==="ja"?{...copy.ja,today:"今日確認すること",primary:"最初に表示するページ",join:"招待コードでチームに参加",roles:"利用中の役割",addRole:"役割を追加",paid:"支払い・集金",safe:"未成年者と成人が制限なく直接やり取りできる機能は設けていません。チーム内の権限と保護者の同意を前提に運用します。",businessBody:"大会、国内外の交流、遠征、施設、人材については、空き状況や条件を確認できるまで「要確認」として扱います。",coachDeskBody:"今日の練習、出欠、連絡事項、集金を一つの画面で確認できます。",memberStatus:"会員ステータス",setup:"初期設定",membershipDetails:"会員プランを確認"}:copy[locale]; const prefix=locale==="en"?"":`/${locale}`; const active=navSections.includes(section as typeof navSections[number])?section:"home";
  const pc=practiceCopy[locale];
  const [data,setData]=useState<AppData>(empty); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(""); const [teamId,setTeamId]=useState("");
  const [loadFailed,setLoadFailed]=useState(false);
  const [adminStats,setAdminStats]=useState<AdminStats|null>(null);
  const supabase=useMemo(()=>createClient(),[]);
  const router=useRouter();
  const load=useCallback(async()=>{
    setLoading(true);setLoadFailed(false);
    try {
    const [profileQ,rolesQ,membershipQ,notesQ,ordersQ,subscriptionsQ]=await Promise.all([
      supabase.from("profiles").select("id,role,display_name,preferred_language,timezone,onboarding_completed").eq("id",userId).maybeSingle(),
      supabase.from("profile_roles").select("role,status").eq("user_id",userId),
      supabase.from("team_memberships").select("id,team_id,member_role,status,teams(id,name,category,gender,region,timezone,created_by)").eq("user_id",userId).eq("status","active"),
      supabase.from("coach_quick_notes").select("id,team_id,body,pinned,created_at").eq("user_id",userId).order("created_at",{ascending:false}).limit(8),
      supabase.from("platform_orders").select("id,order_type,status,amount_total,currency,created_at").eq("user_id",userId).order("created_at",{ascending:false}).limit(10),
      supabase.from("subscriptions").select("id,status,plan_key,current_period_end,cancel_at_period_end").eq("user_id",userId).order("updated_at",{ascending:false}),
    ]);
    if([profileQ,rolesQ,membershipQ,notesQ,ordersQ,subscriptionsQ].some(result=>result.error)){setLoadFailed(true);setMessage(copy[locale].error);setLoading(false);return;}
    const memberships=(membershipQ.data||[]) as unknown as Membership[]; const ids=memberships.map(x=>x.team_id);
    const [eventsQ,noticesQ,collectionsQ]=ids.length?await Promise.all([
      supabase.from("team_events").select("id,team_id,event_type,title,starts_at,ends_at,venue,items_to_bring,fee_amount,availability_status").in("team_id",ids).gte("starts_at",new Date(Date.now()-86400000).toISOString()).order("starts_at").limit(50),
      supabase.from("team_notices").select("id,team_id,title,body,priority,published_at").in("team_id",ids).order("published_at",{ascending:false}).limit(30),
      supabase.from("team_collections").select("id,team_id,title,amount,currency,due_at,status").in("team_id",ids).neq("status","archived").limit(30),
    ]):[{data:[],error:null},{data:[],error:null},{data:[],error:null}];
    if([eventsQ,noticesQ,collectionsQ].some(result=>result.error)){setLoadFailed(true);setMessage(copy[locale].error);setLoading(false);return;}
    setData({profile:profileQ.data as Profile|null,roles:(rolesQ.data||[]) as UserRole[],memberships,events:(eventsQ.data||[]) as TeamEvent[],notices:(noticesQ.data||[]) as Notice[],notes:(notesQ.data||[]) as Note[],collections:(collectionsQ.data||[]) as Collection[],orders:(ordersQ.data||[]) as Order[],subscriptions:(subscriptionsQ.data||[]) as Subscription[]});
    if(profileQ.data?.role==="admin"){
      const [members,allTeams,entities,offers,orders,transactions,allEvents]=await Promise.all([
        supabase.from("profiles").select("id",{count:"exact",head:true}),supabase.from("teams").select("id",{count:"exact",head:true}),supabase.from("platform_entities").select("id",{count:"exact",head:true}),supabase.from("service_offers").select("id",{count:"exact",head:true}),supabase.from("platform_orders").select("id",{count:"exact",head:true}),supabase.from("transaction_ledger").select("amount,transaction_type,status"),supabase.from("events").select("id",{count:"exact",head:true})
      ]);
      const tx=transactions.data||[];setAdminStats({members:members.count||0,teams:allTeams.count||0,entities:entities.count||0,offers:offers.count||0,orders:orders.count||0,transactions:tx.length,volume:tx.filter(x=>x.status==="succeeded"&&x.transaction_type==="charge").reduce((sum,x)=>sum+x.amount,0),events:allEvents.count||0});
    }
    setTeamId(current=>current||ids[0]||""); setLoading(false);
    } catch {setLoadFailed(true);setMessage(copy[locale].error);setLoading(false);}
  },[locale,supabase,userId]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[load]);
  const teams=data.memberships.map(m=>m.teams).filter(Boolean) as Team[];
  const selectedTeam=teams.find(t=>t.id===teamId)||teams[0];
  const displayTimeZone=data.profile?.timezone||"Asia/Tokyo";
  const calendarTimeZone=selectedTeam?.timezone||displayTimeZone;
  const now=new Date(); const todayKey=dateKey(now,displayTimeZone);
  const todayEvents=data.events.filter(e=>dateKey(new Date(e.starts_at),displayTimeZone)===todayKey);
  const nextEvent=data.events.find(e=>new Date(e.starts_at)>now);
  const roleSet=new Set(data.roles.filter(r=>r.status==="active").map(r=>r.role)); const isCoach=roleSet.has("coach")||data.profile?.role==="coach"||data.profile?.role==="admin";
  const hasPaidMembership=data.subscriptions.some(subscription=>["active","trialing"].includes(subscription.status))||data.orders.some(order=>order.order_type==="subscription"&&["paid","confirmed","fulfilled"].includes(order.status));
  const setupSteps=[Boolean(data.profile?.display_name),roleSet.size>0,teams.length>0];
  const setupPercent=Math.round(setupSteps.filter(Boolean).length/setupSteps.length*100);
  function reportError(){setMessage(c.error);setBusy(false);}
  async function onboarding(e:FormEvent<HTMLFormElement>){
    e.preventDefault();setBusy(true);setMessage("");
    const form=new FormData(e.currentTarget);const role=String(form.get("role"));
    try {
      // Ignore an existing role: its approval/status must never be overwritten.
      const roleResult=await supabase.from("profile_roles").upsert({user_id:userId,role,status:"active"},{onConflict:"user_id,role",ignoreDuplicates:true});
      if(roleResult.error)return reportError();
      const {data:updated,error}=await supabase.from("profiles").update({display_name:String(form.get("name")).trim(),role,onboarding_completed:true,terms_accepted_at:new Date().toISOString(),preferred_language:locale}).eq("id",userId).select("id").maybeSingle();
      if(error||!updated)return reportError();
      await load();
    } catch {reportError();} finally {setBusy(false);}
  }
  async function createTeam(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const formElement=e.currentTarget;const form=new FormData(formElement);const {error}=await supabase.from("teams").insert({name:String(form.get("name")),category:String(form.get("category")),gender:"mixed",country:"JP",timezone:"Asia/Tokyo",default_currency:"JPY",visibility:"private",created_by:userId});if(error)return reportError();formElement.reset();setBusy(false);await load();}
  async function joinTeam(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const formElement=e.currentTarget;const form=new FormData(formElement);const {error}=await supabase.rpc("join_team_with_code",{invite_code:String(form.get("code")).trim().toUpperCase()});if(error)return reportError();formElement.reset();setBusy(false);await load();}
  async function addEvent(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!selectedTeam)return;setBusy(true);const formElement=e.currentTarget;const form=new FormData(formElement);let startsAt:string;try{startsAt=zonedInputToIso(String(form.get("starts")),selectedTeam.timezone);}catch{return reportError();}const {error}=await supabase.from("team_events").insert({team_id:selectedTeam.id,event_type:String(form.get("type")),title:String(form.get("title")).trim(),starts_at:startsAt,timezone:selectedTeam.timezone,venue:String(form.get("venue")).trim()||null,availability_status:"confirmed",created_by:userId});if(error)return reportError();formElement.reset();setBusy(false);await load();}
  async function addPractice(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!selectedTeam)return;setBusy(true);const formElement=e.currentTarget;const form=new FormData(formElement);let startsAt:string;try{startsAt=zonedInputToIso(String(form.get("starts")),selectedTeam.timezone);}catch{return reportError();}const created=await supabase.from("team_events").insert({team_id:selectedTeam.id,event_type:"practice",title:String(form.get("title")).trim(),starts_at:startsAt,timezone:selectedTeam.timezone,venue:String(form.get("venue")).trim()||null,availability_status:"confirmed",created_by:userId}).select("id").single();if(created.error||!created.data)return reportError();const menu=String(form.get("menu")).split(/\r?\n/).map(x=>x.trim()).filter(Boolean).map((content,index)=>({order:index+1,content}));const plan=await supabase.from("practice_plans").insert({team_event_id:created.data.id,theme:String(form.get("theme")).trim()||null,objective:String(form.get("objective")).trim()||null,menu,participant_count:Number(form.get("people"))||null,court_count:Number(form.get("courts"))||null,equipment:String(form.get("equipment")).trim()||null,coach_notes:String(form.get("coach_notes")).trim()||null});if(plan.error){await supabase.from("team_events").delete().eq("id",created.data.id);return reportError();}formElement.reset();setBusy(false);await load();}
  async function setAttendance(eventId:string,status:"attending"|"absent"|"undecided"){setBusy(true);const {error}=await supabase.from("attendance_responses").upsert({team_event_id:eventId,user_id:userId,status,responded_at:new Date().toISOString(),updated_at:new Date().toISOString()},{onConflict:"team_event_id,user_id"});if(error)return reportError();setMessage(pc.saved);setBusy(false);}
  async function addNote(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const formElement=e.currentTarget;const form=new FormData(formElement);const {error}=await supabase.from("coach_quick_notes").insert({team_id:selectedTeam?.id||null,user_id:userId,body:String(form.get("body")),pinned:false});if(error)return reportError();formElement.reset();setBusy(false);await load();}
  async function addRole(role:string){if(data.roles.some(item=>item.role===role))return;setBusy(true);const status=["player","parent","coach"].includes(role)?"active":"pending";const {error}=await supabase.from("profile_roles").insert({user_id:userId,role,status});if(error)return reportError();setBusy(false);await load();}
  async function updateProfile(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const formElement=e.currentTarget;const form=new FormData(formElement);const {error}=await supabase.from("profiles").update({display_name:String(form.get("name")).trim(),timezone:String(form.get("timezone")),preferred_language:locale}).eq("id",userId);if(error)return reportError();setMessage(c.profileSaved);setBusy(false);await load();}
  async function signOut(){await supabase.auth.signOut();router.replace(`${prefix}/my-homecourt/login`);router.refresh();}
  if(loading)return <main className="member-app-loading"><LoaderCircle className="spin"/><p>{c.loading}</p></main>;
  if(loadFailed)return <main className="member-app-loading"><p role="alert">{c.error}</p><button onClick={()=>void load()}>{locale==="ja"?"再読み込み":locale==="ko"?"다시 시도":locale==="zh-tw"?"重新載入":"Try again"}</button></main>;
  if(!data.profile?.onboarding_completed)return <main className="member-onboarding"><section><p>RBA ID / MY HOME COURT</p><h1>{c.welcome}</h1><form onSubmit={onboarding}><label>{c.name}<input name="name" defaultValue={data.profile?.display_name||email.split("@")[0]} required/></label><label>{c.primary}<select name="role" defaultValue={data.profile?.role||"player"}><option value="player">PLAYER</option><option value="parent">PARENT</option><option value="coach">COACH</option></select></label><button disabled={busy}>{busy?<LoaderCircle className="spin"/>:<CheckCircle2/>}{c.save}</button>{message?<p role="alert">{message}</p>:null}</form><p className="member-safety"><ShieldCheck/>{c.safe}</p></section></main>;
  const appHref=(part:string)=>`${prefix}/my-homecourt/app${part==="home"?"":`/${part}`}`;
  return <div className="member-app"><header><a href={appHref("home")}><strong>RBA</strong><span>MY HOME COURT</span></a><div><span>{data.profile.display_name||email}</span><button aria-label={c.signout} onClick={signOut}><LogOut/></button></div></header><main>
    {message?<div className="member-alert" role="alert">{message}<button onClick={()=>setMessage("")}>×</button></div>:null}
    {active==="calendar"&&isCoach&&selectedTeam?<div className="member-import-wrap"><CalendarImport locale={locale} teamId={selectedTeam.id} timezone={selectedTeam.timezone} userId={userId} onImported={load}/></div>:null}
    {active==="home"?<><section className="member-dashboard-head"><div><p>RBA ID / {data.profile.role.toUpperCase()}</p><h1>{data.profile.display_name||email.split("@")[0]}</h1><span>{c.today}</span></div><div className="member-status-card"><span>{c.memberStatus}</span><strong>{hasPaidMembership?c.paidMember:c.freeMember}</strong><small>{hasPaidMembership?c.verified:(locale==="ja"?"RBA ID 利用中":"RBA ID ACTIVE")}</small></div></section><MemberJourney locale={locale} initialAudience={data.profile.role==="parent"?"parent":isCoach?"coach":"player"}/>{!teams.length?<section className="member-next-step"><div><UserRound/><span>{c.nextStep}</span><strong>{isCoach?c.setupTeamCoach:c.setupTeamMember}</strong></div><a href={appHref("team")}>{c.goTeam}<ChevronRight/></a></section>:null}<section className="member-today"><p>HOME / TODAY</p><h2>{c.today}</h2>{todayEvents.length?todayEvents.map(item=><article key={item.id}><CalendarDays/><div><time>{new Date(item.starts_at).toLocaleTimeString(locale,{timeZone:displayTimeZone,hour:"2-digit",minute:"2-digit"})}</time><strong>{item.title}</strong><span>{item.venue||"—"}</span></div></article>):<div className="member-empty"><CheckCircle2/><p>{c.noToday}</p></div>}</section><section className="member-summary"><article><span>{c.next}</span><strong>{nextEvent?.title||"—"}</strong><p>{nextEvent?new Date(nextEvent.starts_at).toLocaleString(locale,{timeZone:displayTimeZone,month:"short",day:"numeric",hour:"2-digit",minute:"2-digit"}):c.noToday}</p></article><article><span>{c.tasks}</span><strong>{data.collections.filter(x=>x.status==="open").length}</strong><p>{c.paid}</p></article><article className="member-setup-summary"><span>{c.setup}</span><strong>{setupPercent}%</strong><div><i style={{width:`${setupPercent}%`}}/></div><p>{setupSteps.filter(Boolean).length}/3 {c.complete}</p></article></section><section className="member-latest"><div><p>INFORMATION</p><h2>{c.recentNotice}</h2></div>{data.notices[0]?<a href={appHref("notifications")}><span>{new Date(data.notices[0].published_at).toLocaleDateString(locale,{timeZone:displayTimeZone})}</span><strong>{data.notices[0].title}</strong><ChevronRight/></a>:<div className="member-empty"><Bell/><p>{c.noNotice}</p></div>}</section>{isCoach?<section className="member-coach-desk"><p>COACH / DAILY WORKSPACE</p><h2>{c.coachDesk}</h2><p>{c.coachDeskBody}</p><div><a href={appHref("calendar")}><CalendarDays/>{c.calendar}<ChevronRight/></a><a href={appHref("team")}><ClipboardList/>{c.team}<ChevronRight/></a><a href={appHref("notifications")}><Bell/>{c.notifications}<ChevronRight/></a></div></section>:null}<section className="member-network"><p>{c.business}</p><h2>{c.business}</h2><span>{c.businessBody}</span><div><a href={`${prefix}/united`}>{c.united}<ChevronRight/></a><a href={`${prefix}/connect`}>{c.connect}<ChevronRight/></a><a href={`${prefix}/organizer`}>{c.organizer}<ChevronRight/></a></div></section></>:null}
    {active==="calendar"?<section className="member-section"><div className="member-section-head"><div><p>TEAM CALENDAR</p><h1>{c.calendar}</h1></div>{teams.length>1?<select value={teamId} onChange={e=>setTeamId(e.target.value)}>{teams.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select>:null}</div><div className="member-list">{data.events.filter(e=>!teamId||e.team_id===teamId).map(item=><article key={item.id}><time>{new Date(item.starts_at).toLocaleDateString(locale,{timeZone:calendarTimeZone,month:"short",day:"numeric",weekday:"short"})}</time><div><span>{item.event_type.toUpperCase()}</span><strong>{item.title}</strong><p>{new Date(item.starts_at).toLocaleTimeString(locale,{timeZone:calendarTimeZone,hour:"2-digit",minute:"2-digit"})} · {item.venue||"—"}</p><div className="member-attendance"><button type="button" disabled={busy} onClick={()=>setAttendance(item.id,"attending")}>{pc.attend}</button><button type="button" disabled={busy} onClick={()=>setAttendance(item.id,"absent")}>{pc.absent}</button><button type="button" disabled={busy} onClick={()=>setAttendance(item.id,"undecided")}>{pc.undecided}</button></div></div></article>)}</div>{isCoach&&selectedTeam?<><form className="member-inline-form" onSubmit={addPractice}><h2><Plus/>{pc.practice}</h2><label>{c.eventTitle}<input name="title" required/></label><label>{c.starts}<input name="starts" type="datetime-local" required/></label><label>{c.venue}<input name="venue"/></label><label>{pc.theme}<input name="theme" required/></label><label>{pc.objective}<input name="objective"/></label><label className="member-form-wide">{pc.menu}<textarea name="menu" required/></label><label>{pc.people}<input name="people" type="number" min="1"/></label><label>{pc.courts}<input name="courts" type="number" min="0.5" step="0.5"/></label><label>{pc.equipment}<input name="equipment"/></label><label>{pc.coachNotes}<input name="coach_notes"/></label><button disabled={busy}>{pc.save}</button></form><form className="member-inline-form" onSubmit={addEvent}><h2><Plus/>{c.addEvent}</h2><label>{c.eventTitle}<input name="title" required/></label><label>{c.eventType}<select name="type"><option value="match">MATCH</option><option value="tournament">TOURNAMENT</option><option value="trip">TRIP</option><option value="meeting">MEETING</option><option value="event">EVENT</option><option value="off">OFF</option></select></label><label>{c.starts}<input name="starts" type="datetime-local" required/></label><label>{c.venue}<input name="venue"/></label><button disabled={busy}>{c.add}</button></form></>:null}</section>:null}
    {active==="team"?<section className="member-section"><div className="member-section-head"><div><p>TEAM ID / TEAM HOME</p><h1>{c.teamTitle}</h1></div></div>{teams.length?<div className="member-team-grid">{teams.map(team=><button key={team.id} className={team.id===teamId?"active":""} onClick={()=>setTeamId(team.id)}><Users/><strong>{team.name}</strong><span>{team.category} · {team.region||"—"}</span></button>)}</div>:<div className="member-empty"><Users/><p>{c.noTeam}</p></div>}<div className="member-team-actions">{isCoach?<form onSubmit={createTeam}><h2>{c.createTeam}</h2><label>{c.teamName}<input name="name" required/></label><label>{c.category}<select name="category"><option>U8</option><option>U10</option><option>U12</option><option>U15</option><option>U18</option><option>ADULT</option></select></label><button disabled={busy}>{c.create}</button></form>:null}<form onSubmit={joinTeam}><h2>{c.join}</h2><label>{c.code}<input name="code" required autoCapitalize="characters"/></label><button disabled={busy}>{c.joinAction}</button></form></div>{isCoach?<form className="member-note-form" onSubmit={addNote}><h2><StickyNote/>{c.notes}</h2><textarea name="body" required placeholder={c.notePlaceholder}/><button disabled={busy}>{c.addNote}</button></form>:null}</section>:null}
    {active==="notifications"?<section className="member-section"><div className="member-section-head"><div><p>NOTIFICATIONS</p><h1>{c.notifications}</h1></div></div><div className="member-notices">{data.notices.length?data.notices.map(item=><article key={item.id}><Bell/><div><time>{new Date(item.published_at).toLocaleDateString(locale,{timeZone:displayTimeZone})}</time><strong>{item.title}</strong><p>{item.body}</p></div></article>):<div className="member-empty"><CheckCircle2/><p>NEW 0</p></div>}</div></section>:null}
    {active==="my"?<section className="member-section"><div className="member-section-head"><div><p>RBA ID</p><h1>{c.my}</h1></div></div><div className="member-plan"><div><CreditCard/><span>{c.memberStatus}</span><strong>{hasPaidMembership?c.paidMember:c.freeMember}</strong><small>{hasPaidMembership?c.verified:(locale==="ja"?"RBA ID 利用中":"RBA ID ACTIVE")}</small></div>{!hasPaidMembership?<><a href={`${prefix}/payments`}>{({ja:"プログラム・申込を確認",en:"View programmes and applications","zh-tw":"查看課程與報名",ko:"프로그램·신청 확인"})[locale]}<ChevronRight/></a></>:null}</div><form className="member-account-form" onSubmit={updateProfile}><h2>{c.account}</h2><label>{c.name}<input name="name" defaultValue={data.profile.display_name||""} required/></label><label>{c.timezone}<select name="timezone" defaultValue={data.profile.timezone||"Asia/Tokyo"}><option value="Asia/Tokyo">Asia/Tokyo</option><option value="Asia/Seoul">Asia/Seoul</option><option value="Asia/Taipei">Asia/Taipei</option><option value="Asia/Singapore">Asia/Singapore</option><option value="Australia/Sydney">Australia/Sydney</option><option value="Europe/Berlin">Europe/Berlin</option></select></label><button disabled={busy}>{busy?<LoaderCircle className="spin"/>:<CheckCircle2/>}{c.saveProfile}</button></form><div className="member-profile"><strong>{data.profile.display_name}</strong><span>{email}</span><p>{c.roles}</p><div>{data.roles.map(item=><span key={item.role}>{item.role.toUpperCase()} · {roleStatusLabel(item.status,locale)}</span>)}</div><p>{c.addRole}</p><div>{["player","parent","coach","organizer","official","facility","partner"].filter(x=>!data.roles.some(item=>item.role===x)).map(role=><button key={role} onClick={()=>addRole(role)} disabled={busy}>+ {role.toUpperCase()}</button>)}</div>{data.profile.role==="admin"?<a href={appHref("admin")}>ADMIN / BUSINESS DASHBOARD <ChevronRight/></a>:null}<p className="member-safety"><ShieldCheck/>{c.safe}</p><a href={`${prefix}/policies`}>POLICY / SAFETY <ChevronRight/></a><button className="member-signout" onClick={signOut}><LogOut/>{c.signout}</button></div></section>:null}
    {active==="admin"&&data.profile.role==="admin"?<section className="member-section"><div className="member-section-head"><div><p>RBA ADMIN / BUSINESS</p><h1>PLATFORM DASHBOARD</h1></div></div><div className="admin-metrics">{[["RBA ID",adminStats?.members||0],["TEAM",adminStats?.teams||0],["BUSINESS ENTITY",adminStats?.entities||0],["SERVICE OFFER",adminStats?.offers||0],["ORDER",adminStats?.orders||0],["TRANSACTION",adminStats?.transactions||0],["PAYMENT VOLUME",`¥${(adminStats?.volume||0).toLocaleString("ja-JP")}`],["PUBLIC EVENT",adminStats?.events||0]].map(([label,value])=><article key={label}><span>{label}</span><strong>{value}</strong></article>)}</div><div className="member-safety"><ShieldCheck/>{locale==="ja"?"売上額だけでなく、手数料・原価・返金を共通取引台帳から分離して集計できる構造です。実績がない項目は0で表示します。":"Revenue, fees, costs and refunds remain separately reportable in the transaction ledger. Unrecorded values show as zero."}</div></section>:null}
  </main><nav className="member-bottom-nav" aria-label="MY HOME COURT"><a className={active==="home"?"active":""} href={appHref("home")}><House/><span>{c.home}</span></a><a className={active==="calendar"?"active":""} href={appHref("calendar")}><CalendarDays/><span>{c.calendar}</span></a><a className={active==="team"?"active":""} href={appHref("team")}><Users/><span>{c.team}</span></a><a className={active==="notifications"?"active":""} href={appHref("notifications")}><Bell/><span>{c.notifications}</span></a><a className={active==="my"?"active":""} href={appHref("my")}><Menu/><span>{c.my}</span></a></nav></div>;
}