"use client";
import { FormEvent, useState } from "react";
import { ArrowLeft, CheckCircle2, LoaderCircle, LockKeyhole, Mail, ShieldCheck } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
import type { Locale } from "./site-frame";


const words={
  ja:{title:"RBA IDでログイン",lead:"登録とログインに必要なのは、メールアドレスだけです。メールで届くログインリンクを開くと、MY HOME COURTへ安全にアクセスできます。",email:"メールアドレス",changeEmail:"メールアドレスを変更",send:"ログインリンクを送信",sent:"メールを送信しました",sentBody:"届いたメールを開き、「ログイン」を押してください。リンクの有効期限が切れた場合は、もう一度送信できます。",role:"最初に開くページ",terms:"参加規約とプライバシーポリシーを確認し、同意します。",player:"PLAYER",parent:"PARENT",coach:"COACH",safe:"無料登録だけでは料金は発生しません。未成年者の安全を守るため、利用者の役割に応じて権限を分けています。",back:"MY HOME COURTへ戻る",error:"送信できませんでした。メールアドレスを確認し、もう一度お試しください。"},
  en:{title:"Sign in with your RBA ID",lead:"Enter your email. Open the secure link we send to access MY HOME COURT.",email:"Email address",changeEmail:"Change email address",send:"Send sign-in link",sent:"Check your email",sentBody:"Open the sign-in link in the email. You can request another if it expires.",role:"Your first HOME",terms:"I agree to the terms and privacy policy.",player:"PLAYER",parent:"PARENT",coach:"COACH",safe:"Free registration never creates a charge. Youth safety and role-based access come first.",back:"Back to MY HOME COURT",error:"We could not send the email. Check the address and try again."},
  "zh-tw":{title:"使用RBA ID登入",lead:"輸入電子郵件，開啟收到的安全連結即可進入MY HOME COURT。",email:"電子郵件",changeEmail:"更改電子郵件",send:"傳送登入連結",sent:"請查看電子郵件",sentBody:"開啟郵件中的登入連結。連結失效時可重新傳送。",role:"第一個HOME",terms:"我同意使用條款與隱私政策。",player:"PLAYER",parent:"PARENT",coach:"COACH",safe:"免費登錄不會產生費用。兒少安全與角色權限優先。",back:"返回MY HOME COURT",error:"無法傳送。請確認電子郵件後重試。"},
  ko:{title:"RBA ID로 로그인",lead:"이메일을 입력하고 전송된 보안 링크를 열어 MY HOME COURT에 접속하세요.",email:"이메일",changeEmail:"이메일 주소 변경",send:"로그인 링크 보내기",sent:"이메일을 확인하세요",sentBody:"메일의 로그인 링크를 여세요. 만료되면 다시 요청할 수 있습니다.",role:"첫 HOME",terms:"이용약관과 개인정보처리방침에 동의합니다.",player:"PLAYER",parent:"PARENT",coach:"COACH",safe:"무료 등록만으로 비용이 발생하지 않습니다. 아동 안전과 역할별 권한을 우선합니다.",back:"MY HOME COURT로 돌아가기",error:"전송하지 못했습니다. 이메일을 확인하고 다시 시도하세요."}
} as const;


export function MemberLogin({locale}:{locale:Locale}){
  const c=words[locale]; const [email,setEmail]=useState(""); const [role,setRole]=useState("player"); const [terms,setTerms]=useState(false); const [busy,setBusy]=useState(false); const [sent,setSent]=useState(false); const [error,setError]=useState("");
  const prefix=locale==="en"?"":`/${locale}`;
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");const supabase=createClient();const callback=`${location.origin}/auth/callback?next=${encodeURIComponent(`${prefix}/my-homecourt/app`)}`;const {error}=await supabase.auth.signInWithOtp({email,options:{emailRedirectTo:callback,shouldCreateUser:true,data:{role,preferred_language:locale}}});setBusy(false);if(error)setError(c.error);else setSent(true);}
  return <main className="member-login-shell"><a className="member-login-back" href={`${prefix}/my-homecourt`}><ArrowLeft size={17}/>{c.back}</a><section className="member-login-card"><div className="member-login-copy"><p>RBA ID / ONE ID</p><h1>{c.title}</h1><span>{c.lead}</span><div className="member-login-trust"><ShieldCheck/><span>{c.safe}</span></div></div>{sent?<div className="member-login-sent" role="status"><CheckCircle2/><h2>{c.sent}</h2><p>{c.sentBody}</p><button type="button" onClick={()=>setSent(false)}>{c.changeEmail}</button></div>:<form onSubmit={submit}><label>{c.email}<span><Mail size={17}/><input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email" required placeholder="you@example.com"/></span></label><fieldset><legend>{c.role}</legend><div>{["player","parent","coach"].map(item=><label key={item}><input type="radio" name="role" value={item} checked={role===item} onChange={e=>setRole(e.target.value)}/><span>{c[item as keyof typeof c]}</span></label>)}</div></fieldset><label className="member-terms"><input type="checkbox" checked={terms} onChange={e=>setTerms(e.target.checked)} required/><span>{c.terms} <a href={`${prefix}/policies`} target="_blank" rel="noreferrer">POLICY</a></span></label>{error?<p className="member-form-error" role="alert">{error}</p>:null}<button className="member-login-submit" disabled={busy||!terms}>{busy?<LoaderCircle className="spin"/>:<LockKeyhole/>}{c.send}</button></form>}</section></main>;
}