import type { Locale } from "./site-frame";
import { HOMECOURT_BILLING_PORTAL, type HomecourtSubscription } from "@/lib/homecourt-billing";
import styles from "./member-billing.module.css";
const copy={
 ja:{title:"メンバーシップ・お支払い",intro:"ご契約中の方は、カード変更・請求内容の確認・解約をStripeから行えます。",open:"契約内容・お支払いを確認する",email:"Stripeでは、決済時に使用したメールアドレスでお手続きください。",empty:"現在、月額メンバーシップはご利用いただいていません。ご希望の場合は、こちらからお申し込みいただけます。",period:"現在の利用期間",ends:"利用終了予定",pending:"終了日を確認しています。詳しくはStripeでご確認ください。",sync:"お手続き直後は、MY HOME COURTへの反映まで少し時間がかかる場合があります。",statuses:{active:"契約中",trialing:"体験期間中",past_due:"お支払いの確認が必要です",unpaid:"お支払い未完了",cancelled:"解約済み",canceled:"解約済み",inactive:"利用開始前・利用停止中"}},
 en:{title:"Subscription & billing",intro:"Manage your card, invoices and cancellation in Stripe.",open:"Manage subscription & billing",email:"Sign in with the email used for payment.",empty:"No membership subscription is recorded. If you have paid, check your subscription in Stripe.",period:"Current period ends",ends:"Access scheduled to end",pending:"End date is pending. Check Stripe.",sync:"Recent changes may take time to appear here.",statuses:{active:"Active",trialing:"Trial",past_due:"Payment needs attention",unpaid:"Unpaid",cancelled:"Cancelled",canceled:"Cancelled",inactive:"Not active"}},
 "zh-tw":{title:"訂閱與付款",intro:"前往 Stripe 更新信用卡、查看帳單或取消訂閱。",open:"管理訂閱與付款",email:"請使用付款時的電子郵件登入。",empty:"目前沒有會員訂閱紀錄。若已付款，請至 Stripe 確認。",period:"本期結束日",ends:"預計停止使用日期",pending:"結束日期確認中，請至 Stripe 查看。",sync:"剛完成的變更可能需要一些時間才會顯示。",statuses:{active:"訂閱中",trialing:"試用中",past_due:"需確認付款",unpaid:"尚未付款",cancelled:"已取消",canceled:"已取消",inactive:"未啟用"}},
 ko:{title:"구독 및 결제",intro:"Stripe에서 카드 변경, 청구서 확인, 구독 취소를 진행할 수 있습니다.",open:"구독 및 결제 관리",email:"결제에 사용한 이메일로 로그인해 주세요.",empty:"등록된 멤버십 구독이 없습니다. 결제하셨다면 Stripe에서 확인해 주세요.",period:"현재 이용 기간 종료",ends:"이용 종료 예정",pending:"종료일 확인 중입니다. Stripe에서 확인해 주세요.",sync:"최근 변경 사항이 표시되기까지 시간이 걸릴 수 있습니다.",statuses:{active:"구독 중",trialing:"체험 중",past_due:"결제 확인 필요",unpaid:"미결제",cancelled:"취소됨",canceled:"취소됨",inactive:"이용 전 또는 중지"}}
};
export function MemberBilling({subscriptions,locale}:{subscriptions:HomecourtSubscription[];locale:Locale}){
 const c=copy[locale];
 const records=subscriptions.filter(s=>s.plan_key==="homecourt_monthly");
 return <section className={styles.panel} aria-labelledby="member-billing-title"><h2 id="member-billing-title">{c.title}</h2><p>{c.intro}</p>{records.length?<><ul>{records.map(s=>{const end=s.current_period_end?new Date(s.current_period_end):null;return <li key={s.id}><strong>HOMECOURT PLUS</strong><span>{c.statuses[s.status as keyof typeof c.statuses]||c.statuses.inactive}</span>{end&&!Number.isNaN(end.getTime())?<span>{s.cancel_at_period_end?c.ends:c.period}：{end.toLocaleDateString(locale,{timeZone:"Asia/Tokyo",year:"numeric",month:"long",day:"numeric"})}</span>:s.cancel_at_period_end?<span>{c.pending}</span>:null}</li>})}</ul><a href={HOMECOURT_BILLING_PORTAL} target="_blank" rel="noopener noreferrer">{c.open}<span aria-hidden="true">↗</span></a></>:<><p>{c.empty}</p><a href={`/api/commerce/checkout/homecourt-monthly?locale=${locale}`}>{locale==="ja"?"HOMECOURT PLUSを月額3,300円で始める":locale==="zh-tw"?"每月3,300日圓開始":locale==="ko"?"월 3,300엔으로 시작":"Start for ¥3,300/month"}<span aria-hidden="true">→</span></a></>}<p className={styles.note}>{records.length?c.email:""}{records.length?<br/>:null}{c.sync}</p></section>;
}
