import { ArrowRight, ArrowUpRight, CalendarDays, Check, CreditCard, FileText, HeartHandshake, House, LifeBuoy, LockKeyhole, MessageCircle, Sparkles, Users } from "lucide-react";
import { COACH_COMMUNITY_URL, homecourtFreeRegistrationUrl, HOMECOURT_PRICE_JPY, HomecourtRole, PARENT_COMMUNITY_URL, homecourtRoles } from "./homecourt-data";
import { Locale, localePath, SiteFrame } from "./site-frame";

const copy={
  en:{title:"Your RBA starting point.",lead:"Choose PLAYER, PARENT or COACH. Join free, find your community and move to paid membership only when you need continuous programmes and benefits.",free:"Join free",freeBody:"Receive role-based programme news, learning resources and community invitations. Registration never creates a charge.",paid:"Upgrade when it fits",paidBody:"RBA HOMECOURT is JPY 3,300 per month. Review the plan on Stripe before payment; upgrading is always optional.",community:"Community",communityBody:"Useful conversations for families and coaches, connected to real programmes—not an endless social feed.",impact:"RBA IMPACT",impactBody:"See how participation, partner support and paid membership are reinvested into access, education and safer development environments.",choose:"Choose your route",tools:"Member essentials",register:"Free member registration",upgrade:"View paid membership",impactCta:"See impact & reinvestment"},
  ja:{title:"ここから、自分に合うRBAへ。",lead:"PLAYER／PARENT／COACHから自分の立場を選び、まずは無料会員として始められます。継続的なサポートや会員特典が必要になったときだけ、有料会員へ移行できます。",free:"まずは無料会員から",freeBody:"自分の立場に合った活動情報、育成コンテンツ、コミュニティのお知らせを受け取れます。登録しただけで料金が発生することはありません。",paid:"必要になったら有料会員へ",paidBody:"RBA HOMECOURTは月額3,300円です。ログイン後にStripeでプラン内容と金額を確認し、ご自身で決済を完了した場合にのみ料金が発生します。",community:"コミュニティ",communityBody:"選手・保護者・指導者が、実際の活動や育成の悩みを共有し、つながる場所です。参加者を囲い込むためのものではありません。",impact:"RBA IMPACT",impactBody:"参加費、会費、協賛金を、参加機会・指導者教育・安全な育成環境へどのように還元しているかをお伝えします。",choose:"自分に合うページを選ぶ",tools:"会員共通メニュー",register:"無料会員登録",upgrade:"有料会員について見る",impactCta:"活動実績と再投資方針を見る"},
  "zh-tw":{title:"從這裡找到適合你的RBA。",lead:"選擇PLAYER、PARENT或COACH。先免費加入，需要持續方案時再自願升級。",free:"免費加入",freeBody:"接收角色專屬活動、培育內容與社群邀請；免費登錄不會產生費用。",paid:"需要時升級",paidBody:"RBA HOMECOURT每月3,300日圓。只有在Stripe確認並付款後才收費。",community:"社群",communityBody:"以實際活動與培育問題為中心，連結家長與教練。",impact:"RBA IMPACT",impactBody:"公開會員費與合作支持如何再投入參與機會、教育與安全環境。",choose:"選擇入口",tools:"會員選單",register:"免費會員登錄",upgrade:"查看付費會員",impactCta:"查看成果與再投資"},
  ko:{title:"나에게 맞는 RBA를 여기서 시작하세요.",lead:"PLAYER, PARENT, COACH 중 역할을 선택하세요. 무료 회원으로 시작하고 지속 프로그램이 필요할 때만 유료로 전환합니다.",free:"무료 회원",freeBody:"역할별 프로그램, 성장 콘텐츠와 커뮤니티 안내를 받습니다. 무료 등록만으로 비용은 발생하지 않습니다.",paid:"필요할 때 업그레이드",paidBody:"RBA HOMECOURT는 월 3,300엔입니다. Stripe에서 확인하고 결제한 경우에만 비용이 발생합니다.",community:"커뮤니티",communityBody:"실제 프로그램과 성장 과제를 중심으로 가족과 코치를 연결합니다.",impact:"RBA IMPACT",impactBody:"회비와 파트너 지원이 참가 기회, 교육과 안전한 환경에 어떻게 재투자되는지 공개합니다.",choose:"역할 선택",tools:"회원 메뉴",register:"무료 회원 등록",upgrade:"유료 회원 보기",impactCta:"성과와 재투자 보기"},
} as const;

export function MyHomecourt({locale,role}:{locale:Locale;role?:HomecourtRole}) {
  const prefix=locale==="en"?"":`/${locale}`;
  const c=copy[locale];
  const registrationUrl=homecourtFreeRegistrationUrl(locale);
  const ja=locale==="ja";
  const selected=role?homecourtRoles[role]:null;
  const roleCommunity=role==="coaches"?COACH_COMMUNITY_URL:PARENT_COMMUNITY_URL;
  return <SiteFrame locale={locale} languagePage="my-homecourt">
    <section className="my-homecourt-hero section-pad"><div className="my-homecourt-hero-copy"><a className="back-link" href={localePath(locale,"home-court")}>← RBA HOMECOURT</a><p className="section-index inverse">RBA / OPEN DEVELOPMENT PLATFORM</p><h1>{selected?(ja?selected.label:selected.shortLabel):c.title}</h1><p>{selected?(ja?selected.description:"Your dedicated route to RBA programmes and resources."):c.lead}</p><div className="my-homecourt-hero-actions"><a className="button button-member" href={registrationUrl}><Sparkles size={17}/>{c.register}<ArrowRight size={16}/></a><a className="button button-light" href={localePath(locale,"home-court")}>{c.upgrade}<ArrowRight size={16}/></a></div></div><div className="my-homecourt-hero-mark" aria-hidden="true"><span>RBA</span><strong>MY<br/>HOME<br/>COURT</strong><small>PLAYER / PARENT / COACH</small></div></section>
    {!role?<section className="membership-path section-pad"><p className="section-index">FREE → COMMUNITY → RBA HOMECOURT</p><div className="membership-path-grid"><article><span>01 / FREE</span><Sparkles/><h2>{c.free}</h2><p>{c.freeBody}</p><a href={registrationUrl}>{c.register}<ArrowRight size={16}/></a></article><article><span>02 / CONNECT</span><MessageCircle/><h2>{c.community}</h2><p>{c.communityBody}</p><a href={localePath(locale,"community")}>{c.community}<ArrowRight size={16}/></a></article><article><span>03 / OPTIONAL</span><CreditCard/><h2>{c.paid}</h2><p>{c.paidBody}</p><a href={registrationUrl}>{locale==="ja"?"ログインして加入":locale==="zh-tw"?"登入後加入":locale==="ko"?"로그인 후 가입":"Sign in to join"} · ¥{HOMECOURT_PRICE_JPY.toLocaleString("ja-JP")} / month<ArrowRight size={16}/></a></article></div></section>:null}
    <section className="my-homecourt-role section-pad"><p className="section-index">PLAYER / PARENT / COACH</p><h2 className="member-section-title">{c.choose}</h2><div className="my-homecourt-role-grid">{Object.entries(homecourtRoles).map(([key,data])=><a key={key} className={role===key?"is-current":undefined} href={`${prefix}/my-homecourt/${key}`}><span>{data.shortLabel}</span><strong>{ja?data.label:data.shortLabel}</strong><p>{ja?data.description:"Open your RBA guide, community and next actions."}</p><ArrowRight size={20}/></a>)}</div></section>
    {selected?<section className="member-route-actions section-pad"><div><p className="section-index">{ja?"次に進む":"YOUR NEXT ACTION"}</p><h2>{ja?`${selected.label}向けのご案内`:`${selected.shortLabel} ROUTE`}</h2><p>{ja?"まずは無料登録から。活動情報やコミュニティ、必要な手続きをまとめて確認できます。有料会員への移行は任意です。":"Start free, then move to programmes, community and optional paid membership."}</p></div><div className="member-route-action-grid"><a href={registrationUrl}><Sparkles/><strong>{c.register}</strong><span>{ja?"登録しただけでは料金は発生しません":"No charge for registration"}</span><ArrowRight/></a><a href={roleCommunity} target="_blank" rel="noreferrer"><Users/><strong>{c.community}</strong><span>{ja?(role==="coaches"?"指導者向けオープンコミュニティ":"選手・保護者向けオープンコミュニティ"):"Join the relevant open community"}</span><ArrowUpRight/></a><a href={localePath(locale,"schedule")}><CalendarDays/><strong>{ja?"現在参加できる活動":"Current programmes"}</strong><span>{ja?"日程・対象・募集状況を確認":"Dates, eligibility and registration"}</span><ArrowRight/></a></div></section>:null}
    <section className="my-homecourt-tools section-pad"><div className="section-head"><div><p className="section-index">{ja?"よく使うメニュー":"QUICK ACCESS"}</p><h2>{c.tools}</h2></div><p>{ja?"無料会員も有料会員も、同じ入口から必要な情報を確認できます。":"Free and paid members use the same clear starting point."}</p></div><div className="my-homecourt-tool-grid"><a href={localePath(locale,"schedule")}><CalendarDays/><strong>{ja?"開催日程・募集中の活動":"Programme calendar"}</strong><span>{ja?"対象年代、日程、会場を確認":"Check dates and eligibility"}</span></a><a href={localePath(locale,"payments")}><CreditCard/><strong>{ja?"申込・決済":"Registration & payment"}</strong><span>{ja?"公式の申込フォームと決済先を確認":"Official forms and payment links"}</span></a><a href={localePath(locale,"policies")}><FileText/><strong>{ja?"参加規約・安全方針":"Policies & safety"}</strong><span>{ja?"参加前に確認していただきたい大切な情報":"Important information before joining"}</span></a><a href={localePath(locale,"contact")}><LifeBuoy/><strong>{ja?"RBAへ相談する":"Ask RBA"}</strong><span>{ja?"不明な点は決済前にお問い合わせください":"Ask before payment when unclear"}</span></a></div></section>
    <section className="impact-entry section-pad"><HeartHandshake size={42}/><div><p className="section-index">RBA IMPACT / REINVESTMENT</p><h2>{c.impact}</h2><p>{c.impactBody}</p></div><a className="button button-dark" href={localePath(locale,"impact")}>{c.impactCta}<ArrowRight size={17}/></a></section>
    {selected?<section className="my-homecourt-content section-pad"><div><LockKeyhole size={34}/><p className="section-index">{ja?"コンテンツ案内":"CONTENT ROADMAP"}</p><h2>{ja?`${selected.label}のコンテンツ`:"Content for this route"}</h2><p>{ja?"動画、資料、お知らせは、このページに分かりやすく整理して追加します。参加履歴や家族情報などの個人情報は、ログインした本人と、権限を付与された関係者だけに表示します。":"Videos, resources and notices will be added here. Personal records will only appear after secure authentication is introduced."}</p></div><ul>{selected.items.map(item=><li key={item}><House size={17}/>{item}</li>)}<li><Check size={17}/>{ja?"D-HUBの選抜・強化プログラムは、RBAの一般会員制度とは別に申込・選考を行います。":"D-HUB selection is separate from RBA membership."}</li></ul></section>:null}
  </SiteFrame>;
}