"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {Bell,CheckCircle2,LoaderCircle} from "lucide-react";
import {createClient} from "@/lib/supabase/client";
import type {Locale} from "./site-frame";
import styles from "./notification-preferences.module.css";

type Prefs={event_updates:boolean;payment_updates:boolean;team_updates:boolean;development_updates:boolean;opportunities:boolean;marketing:boolean;preferred_channel:string;schedule_reminders:boolean;care_reminders:boolean;wellness_reminders:boolean;event_reminder_days:number[];care_reminder_minutes:number;wellness_reminder_time:string};
const defaults:Prefs={event_updates:true,payment_updates:true,team_updates:true,development_updates:true,opportunities:true,marketing:false,preferred_channel:"email",schedule_reminders:true,care_reminders:true,wellness_reminders:false,event_reminder_days:[7,3,1,0],care_reminder_minutes:120,wellness_reminder_time:"20:00"};
const copy={
 ja:{title:"通知・メール設定",lead:"必要な連絡と、任意の案内を分けて設定できます。",event:"申込・イベントの変更",payment:"決済・請求に関する重要なお知らせ",team:"所属チームからのお知らせ",development:"振り返り・育成記録に関するお知らせ",opportunities:"新しいクリニック・キャンプ・育成機会",marketing:"RBAからのお知らせ（任意）",channel:"優先する連絡方法",save:"設定を保存",saved:"保存しました",note:"安全に関する重要なお知らせや、決済・契約に必要な連絡は、設定にかかわらず送信する場合があります。",reminders:"MY HOME COURT リマインダー",scheduleReminder:"試合・大会・イベントの準備リマインダー",careReminder:"ケア予定のリマインダー",wellnessReminder:"毎日のコンディション記録リマインダー",days:"イベント前に知らせる日",careBefore:"ケア予定の何分前に知らせるか",wellnessTime:"コンディション記録の時刻"},
 en:{title:"Notifications & email",lead:"Separate essential service messages from optional updates.",event:"Application and event changes",payment:"Important payment and billing notices",team:"Team notices",development:"Development and reflection updates",opportunities:"New clinics, camps and development opportunities",marketing:"RBA news and announcements",channel:"Preferred channel",save:"Save preferences",saved:"Saved",note:"Safety, billing or legally required service notices may still be sent when necessary.",reminders:"MY HOME COURT reminders",scheduleReminder:"Game, tournament and event preparation reminders",careReminder:"Care appointment reminders",wellnessReminder:"Daily condition-log reminder",days:"Days before event",careBefore:"Minutes before care",wellnessTime:"Condition reminder time"},
 "zh-tw":{title:"通知與電子郵件設定",lead:"可分開設定必要通知與選擇性資訊。",event:"報名與活動變更",payment:"重要付款・帳單通知",team:"球隊通知",development:"培育記錄與回顧通知",opportunities:"新的訓練營、培育營與機會",marketing:"RBA新聞與資訊",channel:"優先聯絡方式",save:"儲存設定",saved:"已儲存",note:"安全、付款或依法必要的服務通知，必要時仍可能發送。",reminders:"MY HOME COURT 提醒",scheduleReminder:"比賽・大會・活動準備提醒",careReminder:"照護予定提醒",wellnessReminder:"每日身體狀況記錄提醒",days:"活動前提醒天數",careBefore:"照護予定前幾分鐘提醒",wellnessTime:"身體狀況記錄時間"},
 ko:{title:"알림・이메일 설정",lead:"필수 서비스 알림과 선택 안내를 나누어 설정할 수 있습니다.",event:"신청・이벤트 변경",payment:"중요 결제・청구 알림",team:"팀 알림",development:"육성 기록・회고 알림",opportunities:"새 클리닉・캠프・육성 기회",marketing:"RBA 뉴스・안내",channel:"우선 연락 방법",save:"설정 저장",saved:"저장했습니다",note:"안전, 결제 또는 법적으로 필요한 서비스 알림은 필요 시 발송될 수 있습니다.",reminders:"MY HOME COURT 리마인더",scheduleReminder:"경기・대회・이벤트 준비 리마인더",careReminder:"케어 일정 리마인더",wellnessReminder:"매일 컨디션 기록 리마인더",days:"이벤트 전 알림 일수",careBefore:"케어 일정 전 알림 시간(분)",wellnessTime:"컨디션 기록 시간"}
} as const;

export function NotificationPreferences({userId,locale}:{userId:string;locale:Locale}){
 const c=copy[locale],db=useMemo(()=>createClient(),[]);
 const [prefs,setPrefs]=useState(defaults),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>{const timer=setTimeout(async()=>{const {data}=await db.from("notification_preferences").select("event_updates,payment_updates,team_updates,development_updates,opportunities,marketing,preferred_channel,schedule_reminders,care_reminders,wellness_reminders,event_reminder_days,care_reminder_minutes,wellness_reminder_time").eq("user_id",userId).maybeSingle();if(data)setPrefs({...defaults,...data});setLoading(false)},0);return()=>clearTimeout(timer)},[db,userId]);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const form=new FormData(e.currentTarget);const next:Prefs={event_updates:form.get("event_updates")==="on",payment_updates:form.get("payment_updates")==="on",team_updates:form.get("team_updates")==="on",development_updates:form.get("development_updates")==="on",opportunities:form.get("opportunities")==="on",marketing:form.get("marketing")==="on",preferred_channel:String(form.get("preferred_channel")||"email"),schedule_reminders:form.get("schedule_reminders")==="on",care_reminders:form.get("care_reminders")==="on",wellness_reminders:form.get("wellness_reminders")==="on",event_reminder_days:[30,14,7,3,1,0].filter(n=>form.get(`event_day_${n}`)==="on"),care_reminder_minutes:Number(form.get("care_reminder_minutes")||120),wellness_reminder_time:String(form.get("wellness_reminder_time")||"20:00")};const {error}=await db.from("notification_preferences").upsert({user_id:userId,...next,updated_at:new Date().toISOString()},{onConflict:"user_id"});if(!error){await db.from("profiles").update({marketing_consent:next.marketing,updated_at:new Date().toISOString()}).eq("id",userId);setPrefs(next);setMessage(c.saved)}else setMessage(locale==="ja"?"保存できませんでした。":"Could not save.");setBusy(false)}
 if(loading)return <section className={styles.shell}><LoaderCircle className={styles.spin}/></section>;
 const checks:[keyof Prefs,string][]=[["event_updates",c.event],["payment_updates",c.payment],["team_updates",c.team],["development_updates",c.development],["opportunities",c.opportunities],["marketing",c.marketing]];
 return <section className={styles.shell}><header><Bell/><div><h2>{c.title}</h2><p>{c.lead}</p></div></header><form onSubmit={save}><div className={styles.checks}>{checks.map(([key,label])=><label key={key}><input type="checkbox" name={key} defaultChecked={Boolean(prefs[key])}/><span>{label}</span></label>)}</div><label className={styles.channel}>{c.channel}<select name="preferred_channel" defaultValue={prefs.preferred_channel}><option value="email">Email</option><option value="line">LINE</option><option value="push">MY HOME COURT</option><option value="none">OFF</option></select></label><div className={styles.reminders}><h3>{c.reminders}</h3><label><input type="checkbox" name="schedule_reminders" defaultChecked={prefs.schedule_reminders}/><span>{c.scheduleReminder}</span></label><div className={styles.days}><span>{c.days}</span>{[30,14,7,3,1,0].map(day=><label key={day}><input type="checkbox" name={`event_day_${day}`} defaultChecked={prefs.event_reminder_days.includes(day)}/><b>{day===0?"当日":`D-${day}`}</b></label>)}</div><label><input type="checkbox" name="care_reminders" defaultChecked={prefs.care_reminders}/><span>{c.careReminder}</span></label><label className={styles.channel}>{c.careBefore}<select name="care_reminder_minutes" defaultValue={String(prefs.care_reminder_minutes)}><option value="30">30</option><option value="60">60</option><option value="120">120</option><option value="360">360</option><option value="720">720</option><option value="1440">1440</option></select></label><label><input type="checkbox" name="wellness_reminders" defaultChecked={prefs.wellness_reminders}/><span>{c.wellnessReminder}</span></label><label className={styles.channel}>{c.wellnessTime}<input type="time" name="wellness_reminder_time" defaultValue={String(prefs.wellness_reminder_time).slice(0,5)}/></label></div><p className={styles.note}>{c.note}</p><button disabled={busy}>{busy?<LoaderCircle className={styles.spin}/>:<CheckCircle2/>}{c.save}</button>{message?<p className={styles.message} role="status">{message}</p>:null}</form></section>
}
