"use client";
import {FormEvent,useMemo,useState} from "react";
import {CheckCircle2,LoaderCircle} from "lucide-react";
import {createClient} from "@/lib/supabase/client";
export function PartnerBetaApplication({userId}:{userId:string}){
 const db=useMemo(()=>createClient(),[]),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage("");const form=e.currentTarget,f=new FormData(form);const principles=f.get("principles")==="on";if(!principles){setMessage("共有原則への確認が必要です。");setBusy(false);return;}const {error}=await db.from("development_partner_applications").insert({submitted_by:userId,organization_name:String(f.get("organization")),organization_type:String(f.get("type")||"").trim()||null,region:String(f.get("region")||"").trim()||null,age_groups:String(f.get("ages")||"").split(",").map(x=>x.trim()).filter(Boolean),contact_name:String(f.get("name")),contact_email:String(f.get("email")),website_url:String(f.get("website")||"").trim()||null,current_activity:String(f.get("activity")),collaboration_goal:String(f.get("goal")),safeguarding_summary:String(f.get("safety")||"").trim()||null,principles_acknowledged:true});if(error){setMessage("送信できませんでした。入力内容をご確認ください。");setBusy(false);return;}form.reset();setMessage("β連携の相談を受け付けました。内容を確認してご連絡します。");setBusy(false)}
 return <section className="partner-beta-application"><div className="section-head"><div><p className="section-index">BETA APPLICATION</p><h2>まず、連携したい理由を聞かせてください。</h2></div><p>自動承認ではありません。地域での活動実態と、RBAと何を一緒に取り組みたいかを確認します。</p></div><form onSubmit={submit}><label>団体・クラブ名<input name="organization" required maxLength={160}/></label><label>団体種別<input name="type" placeholder="クラブ / スクール / 学校 / その他" maxLength={80}/></label><label>活動地域<input name="region" maxLength={100}/></label><label>対象年代<input name="ages" placeholder="U10, U12, U15"/></label><label>ご担当者名<input name="name" required maxLength={100}/></label><label>メールアドレス<input name="email" type="email" required/></label><label className="wide">Webサイト・SNS<input name="website" type="url"/></label><label className="wide">現在どのような活動をしていますか<textarea name="activity" required maxLength={1800}/></label><label className="wide">RBAと一緒に取り組みたいこと<textarea name="goal" required maxLength={1800}/></label><label className="wide">未成年者の安全・個人情報について現在行っていること<textarea name="safety" maxLength={1800}/></label><label className="wide partner-principle-check"><input name="principles" type="checkbox" required/><span>Development Partnerの共有原則を確認しました。Partner表示がRBAによる指導品質・安全性の保証ではないことも理解しています。</span></label><button disabled={busy}>{busy?<LoaderCircle className="spin"/>:<CheckCircle2/>}β連携を相談する</button>{message?<p className="wide" role="status">{message}</p>:null}</form></section>
}
