import { ArrowRight, Check, Globe2, ShieldCheck, Trophy, Users } from "lucide-react";
import { Locale, localePath, SiteFrame } from "./site-frame";


const pick=<T,>(locale:Locale,value:{en:T;ja:T;"zh-tw":T;ko:T})=>value[locale];


function PlatformPage({locale,kind}:{locale:Locale;kind:"united"|"connect"|"organizer"}){
  const data={
    united:pick(locale,{en:{tag:"INDIVIDUAL PARTICIPATION",title:"Go beyond your club. Return stronger.",lead:"RBA UNITED brings individually registered players together for a defined tournament, camp or exchange. It does not replace their home team.",cards:[["01","Apply as an individual","Check age, dates, purpose and total cost before applying."],["02","Form a time-limited team","Roles, safeguarding and staff responsibility are stated for every programme."],["03","Keep the history","Participation and the next opportunity stay connected to your RBA ID."]],cta:"See available programmes"},ja:{tag:"個人参加型プログラム",title:"所属チームの枠を越えて集まり、成長を持ち帰る。",lead:"RBA UNITEDは、個人で申し込んだ選手が、大会・遠征・国際交流などの企画ごとに期間限定のチームを組む仕組みです。現在の所属チームでの活動を続けながら参加できます。",cards:[["01","個人で申し込む","対象年代、日程、目的、総費用を確認したうえで申し込みます。"],["02","期間限定のチームをつくる","選手とスタッフの役割、安全管理、引率責任を企画ごとに明示します。"],["03","経験を記録に残す","参加履歴をRBA IDに記録し、次の機会へつなげます。"]],cta:"現在参加できる活動を見る"},"zh-tw":{tag:"個人參加型計畫",title:"跨越所屬團隊，把成長帶回去。",lead:"RBA UNITED讓個人報名球員為特定大會、遠征或交流組成期間限定團隊，不取代原所屬團隊。",cards:[["01","個人申請","申請前確認年齡、日期、目的與總費用。"],["02","期間限定團隊","每項計畫明示角色、安全與帶隊責任。"],["03","保留參加紀錄","以RBA ID連結參加歷史與下一個機會。"]],cta:"查看可參加活動"},ko:{tag:"개인 참가 프로그램",title:"소속을 넘어 모이고, 성장을 가져갑니다.",lead:"RBA UNITED는 개인 참가 선수가 대회·원정·국제교류별로 기간 한정 팀을 구성합니다. 기존 소속팀을 대체하지 않습니다.",cards:[["01","개인 신청","연령, 일정, 목적과 총비용을 확인합니다."],["02","기간 한정 팀","역할, 안전과 인솔 책임을 프로그램별로 명시합니다."],["03","참가 이력","RBA ID로 참가 기록과 다음 기회를 연결합니다."]],cta:"참가 가능한 프로그램"}}),
    connect:pick(locale,{en:{tag:"DOMESTIC / INTERNATIONAL NETWORK",title:"Connect teams to the right opportunity.",lead:"RBA CONNECT supports relationship-led introductions between teams, organisers and international partners. Availability is never presented as confirmed until it is verified.",cards:[["TEAM","Tell us what you need","Age, gender, region, timing, purpose, budget and preferred competition."],["ORGANIZER","Publish verified conditions","Dates, category, entry fee, capacity, accommodation conditions and local support."],["STATUS","Know what is real","Every opportunity is marked CONFIRMED, REQUEST REQUIRED or UNKNOWN."]],cta:"Start a CONNECT request"},ja:{tag:"国内・国際ネットワーク",title:"チームに合った機会をつなぐ。",lead:"RBA CONNECTは、これまで築かれてきた関係を大切にしながら、チーム・大会主催者・海外パートナーをつなぎます。空き状況を確認できていない企画を「参加可能」と表示することはありません。",cards:[["TEAM","希望を伝える","年代、男女、地域、希望時期、目的、予算、大会や交流試合への希望を整理します。"],["ORGANIZER","確認できた情報だけを掲載する","開催日、カテゴリー、参加費、募集枠、宿泊条件、現地で受けられるサポートを明示します。"],["STATUS","確認状況を分かりやすく示す","CONFIRMED（確定）／REQUEST REQUIRED（要確認）／UNKNOWN（未確認）を必ず区別します。"]],cta:"RBA CONNECTに相談する"},"zh-tw":{tag:"國內・國際網絡",title:"把團隊連結到合適的機會。",lead:"RBA CONNECT尊重既有人際關係，連結團隊、主辦方與海外夥伴。未確認前不顯示為可參加。",cards:[["TEAM","提出條件","年齡、性別、地區、時間、目的、預算與賽事需求。"],["ORGANIZER","公布確認條件","日期、類別、費用、名額、住宿與當地支援。"],["STATUS","明確標示狀態","區分CONFIRMED、REQUEST REQUIRED與UNKNOWN。"]],cta:"開始CONNECT洽詢"},ko:{tag:"국내・국제 네트워크",title:"팀을 알맞은 기회와 연결합니다.",lead:"RBA CONNECT는 기존 관계를 존중하며 팀, 주최자와 해외 파트너를 연결합니다. 확인 전에는 참가 가능으로 표시하지 않습니다.",cards:[["TEAM","희망 조건","연령, 성별, 지역, 시기, 목적, 예산과 대회 희망을 정리합니다."],["ORGANIZER","확인 조건 공개","날짜, 카테고리, 참가비, 모집 수, 숙박과 현지 지원을 명시합니다."],["STATUS","정확한 상태","CONFIRMED, REQUEST REQUIRED, UNKNOWN을 구분합니다."]],cta:"CONNECT 상담 시작"}}),
    organizer:pick(locale,{en:{tag:"ORGANIZER HOME",title:"One operating path from recruitment to completion.",lead:"A future workspace for tournament and event organisers. RBA is building the data foundation first; operations open only after payment, staffing and safeguarding rules are verified.",cards:[["BUILD","Create and recruit","Programme details, categories, capacity, multilingual guidance and team intake."],["OPERATE","Run the event","Participants, payment status, staff, officials, venue and communication."],["CLOSE","Complete responsibly","Receipts, results, incident records and participation history."]],cta:"Discuss an organizer project"},ja:{tag:"大会・イベント主催者向け",title:"募集から開催後まで、大会運営を一つにつなぐ。",lead:"ORGANIZER HOMEは、大会・イベント主催者の業務を一つにまとめるワークスペースとして開発を進めています。決済、人員配置、安全管理の運用を確認できた機能から、段階的に提供します。",cards:[["BUILD","大会を企画し、参加者を募集する","大会情報、カテゴリー、定員、多言語での案内、チームの受付をまとめます。"],["OPERATE","大会を運営する","参加者、支払い状況、スタッフ、審判、会場、連絡事項を管理します。"],["CLOSE","開催後の記録を残す","領収書、結果、事故・トラブルの記録、参加履歴を保管します。"]],cta:"主催者向けサービスを相談する"},"zh-tw":{tag:"主辦方專區",title:"從招募到完成，統一營運流程。",lead:"ORGANIZER HOME是大會與活動主辦方的未來工作區。付款、人力與兒少安全規則確認後分階段開放。",cards:[["BUILD","建立與招募","活動資料、類別、名額、多語案內與團隊受理。"],["OPERATE","活動營運","參加者、付款、工作人員、裁判、場地與聯絡。"],["CLOSE","負責完成","收據、結果、事故紀錄與參加歷史。"]],cta:"洽詢主辦方服務"},ko:{tag:"주최자 전용",title:"모집부터 종료까지 운영을 하나로 연결합니다.",lead:"ORGANIZER HOME는 대회·이벤트 주최자의 미래 업무 공간입니다. 결제, 인력과 안전 운영이 확인된 기능부터 단계적으로 제공합니다.",cards:[["BUILD","대회 개설과 모집","정보, 카테고리, 정원, 다국어 안내와 팀 접수."],["OPERATE","행사 운영","참가자, 결제, 스태프, 심판, 장소와 연락."],["CLOSE","책임 있는 마감","영수증, 결과, 사고 기록과 참가 이력."]],cta:"주최자 서비스 상담"}})
  }[kind];
  const Icon=kind==="united"?Users:kind==="connect"?Globe2:Trophy;
  return <SiteFrame locale={locale} languagePage={kind}><section className={`network-hero network-hero-${kind} section-pad`}><a className="back-link" href={localePath(locale)}>← RBA</a><p className="section-index inverse">RBA / {kind.toUpperCase()}</p><Icon/><h1>{kind==="united"?"RBA UNITED":kind==="connect"?"RBA CONNECT":"ORGANIZER HOME"}</h1><strong>{data.title}</strong><p>{data.lead}</p></section><section className="network-cards section-pad">{data.cards.map(([tag,title,body])=><article key={tag}><span>{tag}</span><h2>{title}</h2><p>{body}</p><Check/></article>)}</section><section className="network-release section-pad"><ShieldCheck/><div><p className="section-index">VERIFIED OPERATION</p><h2>{locale==="ja"?"確認できたものだけを公開します。":"Only verified operations go live."}</h2><p>{locale==="ja"?"料金・募集枠・在庫・手配条件を推測で掲載しません。旅行業務に該当する手配は、登録旅行会社との正式な連携を前提とします。":"RBA does not guess prices, capacity, inventory or travel conditions. Regulated travel arrangements require a licensed travel partner."}</p></div><a className="button button-member" href={kind==="united"?localePath(locale,"schedule"):localePath(locale,"contact")}>{data.cta}<ArrowRight/></a></section></SiteFrame>;
}
export const UnitedPage=({locale}:{locale:Locale})=><PlatformPage locale={locale} kind="united"/>;
export const ConnectPage=({locale}:{locale:Locale})=><PlatformPage locale={locale} kind="connect"/>;
export const OrganizerPage=({locale}:{locale:Locale})=><PlatformPage locale={locale} kind="organizer"/>;
