import { ArrowRight, ArrowUpRight, Check, CircleDollarSign, GraduationCap, HeartHandshake, MapPin, ShieldCheck, Sparkles, Target, Users } from "lucide-react";
import { COACH_COMMUNITY_URL, homecourtFreeRegistrationUrl, PARENT_COMMUNITY_URL } from "./homecourt-data";
import { Locale, localePath, SiteFrame } from "./site-frame";


const localize=<T,>(locale:Locale,values:{en:T;ja:T;"zh-tw":T;ko:T})=>values[locale];


export function CommunityPage({locale}:{locale:Locale}){
  const c=localize(locale,{
    en:{title:"Connect around better development.",lead:"RBA Community turns programme news into useful conversation for players, parents and coaches.",parent:"Player & parent community",parentBody:"Programme information, family guidance and questions about youth development.",coach:"Coach community",coachBody:"Practice design, coach education and dialogue connected to real courts.",rules:"Community principles",items:["Children’s safety and dignity come first.","No harassment, recruiting pressure or unsolicited sales.","Medical details, school names and private images stay out of open groups.","RBA membership is not required to join an open community."]},
    ja:{title:"育成を、ひとりで考えない。",lead:"RBA Communityは、募集情報を届けるだけの場所ではありません。選手・保護者・指導者が、実際の活動や育成の悩みを共有し、つながるためのコミュニティです。",parent:"選手・保護者コミュニティ",parentBody:"活動情報や家庭での支え方、育成年代ならではの悩みを共有できるオープンコミュニティです。",coach:"コーチ・指導者コミュニティ",coachBody:"練習設計や指導者講習、現場で生まれた問いを持ち寄るオープンコミュニティです。",rules:"コミュニティ方針",items:["子どもの安全と尊厳を最優先にします。","誹謗中傷、強引な勧誘、無断営業を認めません。","健康情報、学校名、非公開の写真をオープングループへ投稿しません。","オープンコミュニティへの参加に、有料会員登録は必要ありません。"]},
    "zh-tw":{title:"一起思考更好的培育。",lead:"RBA Community以實際活動與培育問題連結球員、家長與教練。",parent:"球員與家長社群",parentBody:"活動資訊、家庭支持與青少年培育對話。",coach:"教練社群",coachBody:"訓練設計、教練教育與球場實務交流。",rules:"社群原則",items:["兒少安全與尊嚴優先。","禁止騷擾、強迫招募或未經同意的銷售。","不在公開群組分享健康、學校或私人影像。","加入公開社群不需要付費會員。"]},
    ko:{title:"더 나은 성장을 함께 고민합니다.",lead:"RBA Community는 실제 프로그램과 성장 과제를 중심으로 선수, 보호자와 코치를 연결합니다.",parent:"선수·보호자 커뮤니티",parentBody:"프로그램 정보, 가정의 지원과 유소년 성장 대화.",coach:"코치 커뮤니티",coachBody:"훈련 설계, 코치 교육과 현장 질문을 나눕니다.",rules:"커뮤니티 원칙",items:["아동의 안전과 존엄을 최우선으로 합니다.","괴롭힘, 강압적 모집과 무단 영업을 금지합니다.","건강 정보, 학교명과 비공개 이미지를 공개 그룹에 올리지 않습니다.","오픈 커뮤니티는 유료 회원이 아니어도 참여할 수 있습니다."]}
  });
  return <SiteFrame locale={locale} languagePage="community"><section className="platform-hero section-pad"><a className="back-link" href={localePath(locale,"my-homecourt")}>← MY HOME COURT</a><p className="section-index inverse">RBA COMMUNITY / OPEN CONNECTION</p><h1>{c.title}</h1><p>{c.lead}</p></section><section className="community-choice section-pad"><a href={PARENT_COMMUNITY_URL} target="_blank" rel="noreferrer"><Users/><span>PLAYER / PARENT</span><h2>{c.parent}</h2><p>{c.parentBody}</p><strong>LINE OPENCHAT <ArrowUpRight size={18}/></strong></a><a href={COACH_COMMUNITY_URL} target="_blank" rel="noreferrer"><GraduationCap/><span>COACH</span><h2>{c.coach}</h2><p>{c.coachBody}</p><strong>LINE OPENCHAT <ArrowUpRight size={18}/></strong></a></section><section className="community-rules section-pad"><ShieldCheck size={40}/><div><p className="section-index">SAFE COMMUNITY</p><h2>{c.rules}</h2><ul>{c.items.map(item=><li key={item}><Check size={17}/>{item}</li>)}</ul></div><a className="button button-member" href={homecourtFreeRegistrationUrl(locale)}><Sparkles size={17}/>{locale==="ja"?"無料会員登録":"Join free"}<ArrowRight size={16}/></a></section></SiteFrame>;
}


export function ImpactPage({locale}:{locale:Locale}){
  const c=localize(locale,{
    en:{title:"Growth that returns to the court.",lead:"RBA IMPACT makes clear what our activity enables and where membership, programme and partner revenue is reinvested.",areas:[["ACCESS","Participation support","Reduce barriers to clinics, camps and regional opportunities."],["EDUCATION","Coach learning","Bring better practice design, S&C and international knowledge to local courts."],["SAFETY","Safer environments","Improve safeguarding, communication, equipment and responsible operations."],["NETWORK","Regional connections","Connect local organisers so children can find a next opportunity beyond one event."]],policy:"Reinvestment policy",policyBody:"A portion of paid membership, programme and partnership income is returned to access, education, safety and regional development. RBA will report completed actions and actual figures only after they can be verified; we do not promise a fixed percentage before each period closes."},
    ja:{title:"活動から生まれた価値を、次のコートへ。",lead:"RBA IMPACTは、活動から生まれた成果や、会費・参加費・協賛収入を育成環境へどう還元しているかを分かりやすく伝える取り組みです。",areas:[["ACCESS","参加機会","地域や家庭の事情にかかわらず、育成の機会へつながれるよう支援します。"],["EDUCATION","指導者教育","練習設計、S&C、国内外の知見を地域の指導現場へ届けます。"],["SAFETY","安全な環境","子どもの保護、連絡体制、備品の整備など、責任ある運営を支えます。"],["NETWORK","地域連携","一度の活動で終わらず、次の機会へつながる地域のネットワークをつくります。"]],policy:"再投資方針",policyBody:"有料会費、参加費、協賛収入の一部を、参加機会の提供、指導者教育、安全な環境づくり、地域連携へ再投資します。あらかじめ固定比率を掲げるのではなく、実施内容と確認できた実績を年度ごとに公開します。運営費と再投資を明確に分け、子どもの写真や参加人数を誇張して成果を見せることはしません。"},
    "zh-tw":{title:"把成長回到下一個球場。",lead:"RBA IMPACT說明會員費、活動與合作收入如何再投入培育環境。",areas:[["ACCESS","參與機會","減少參加活動與地區機會的障礙。"],["EDUCATION","教練教育","把訓練設計、體能與國際知識帶到地方。"],["SAFETY","安全環境","改善兒少保護、溝通、設備與營運。"],["NETWORK","地區連結","讓一次活動連結到下一次機會。"]],policy:"再投資方針",policyBody:"部分會員費、活動與合作收入再投入參與、教育、安全及地區發展。僅公布可驗證的實際成果，不預先承諾未確定比例。"},
    ko:{title:"성장을 다음 코트에 돌려줍니다.",lead:"RBA IMPACT는 회비, 프로그램과 파트너 수입이 어디에 재투자되는지 명확히 합니다.",areas:[["ACCESS","참가 기회","지역과 가정의 장벽을 줄입니다."],["EDUCATION","코치 교육","훈련 설계, S&C와 국제 지식을 지역에 연결합니다."],["SAFETY","안전한 환경","아동 보호, 소통, 장비와 운영을 개선합니다."],["NETWORK","지역 연결","한 번의 행사를 다음 기회로 연결합니다."]],policy:"재투자 정책",policyBody:"유료 회비, 프로그램과 파트너 수입 일부를 참가, 교육, 안전과 지역 개발에 재투자합니다. 검증된 실제 결과만 공개하며 확정 전 비율을 약속하지 않습니다."}
  });
  const icons=[MapPin,GraduationCap,ShieldCheck,HeartHandshake];
  return <SiteFrame locale={locale} languagePage="impact"><section className="impact-hero section-pad"><a className="back-link" href={localePath(locale,"my-homecourt")}>← MY HOME COURT</a><p className="section-index inverse">RBA IMPACT</p><h1>{c.title}</h1><p>{c.lead}</p></section><section className="impact-grid section-pad">{c.areas.map(([tag,title,body],i)=>{const Icon=icons[i];return <article key={tag}><Icon/><span>{tag}</span><h2>{title}</h2><p>{body}</p></article>})}</section><section className="reinvestment-policy section-pad"><CircleDollarSign size={46}/><div><p className="section-index">TRANSPARENCY / REINVESTMENT</p><h2>{c.policy}</h2><p>{c.policyBody}</p><a className="text-link" href={localePath(locale,"partners")}>{locale==="ja"?"協賛・連携方針を見る":"Partnership policy"}<ArrowRight size={17}/></a></div></section></SiteFrame>;
}


export function DHubPage({locale}:{locale:Locale}){
  const c=localize(locale,{
    en:{title:"Selection. Intensification. Competition.",lead:"D-HUB is a separate selection-based pathway for players seeking higher competitive intensity. It is not RBA’s open development platform and RBA membership does not guarantee entry.",items:[["SELECTION","Application and evaluation","Entry conditions and evaluation criteria are published for each programme."],["INTENSIFICATION","Higher training load","Advanced work is designed around readiness, recovery and long-term health."],["COMPETITION","Competitive pathway","Competition plans, team roles and costs are explained before commitment."]],boundary:"Clearly separate from RBA",boundaryBody:"RBA serves broad participation, development and education. D-HUB serves selected, competition-focused players. Branding, application, selection, fees and participation decisions are handled separately."},
    ja:{title:"選抜。強化。競技。",lead:"D-HUBは、より高い競技レベルを目指す選手のための選考制プログラムです。RBAの「普及・育成・教育」を担うプラットフォームとは別の事業であり、RBA会員であることによる選考上の優遇や参加保証はありません。",items:[["SELECTION","選考","対象年代、申込条件、評価方法を企画ごとに明示します。"],["INTENSIFICATION","強化","選手の準備状態、回復、長期的な健康を踏まえながら、高い強度の育成環境を設計します。"],["COMPETITION","競技","大会計画、チーム内での役割、費用、参加条件を、参加決定前に説明します。"]],boundary:"RBAとは明確に分けて運営",boundaryBody:"RBAは、誰もが学びや機会につながれる「普及・育成・教育」の全国プラットフォームです。D-HUBは、競技志向の選手を対象とする「選抜・強化」の別事業です。名称、募集、選考、費用、参加手続きを明確に分け、無料会員や有料会員が自動的に進級する仕組みにはしません。"},
    "zh-tw":{title:"選拔。強化。競技。",lead:"D-HUB是面向更高競技強度球員的獨立選拔方案。RBA會員不保證入選。",items:[["SELECTION","選拔","每個方案公布條件與評估方式。"],["INTENSIFICATION","強化","依準備、恢復與長期健康設計高強度訓練。"],["COMPETITION","競技","參加前說明賽事、角色、費用與條件。"]],boundary:"與RBA明確分離",boundaryBody:"RBA負責普及、培育與教育；D-HUB服務經選拔的競技型球員。品牌、申請、選拔與費用分開處理。"},
    ko:{title:"선발. 강화. 경쟁.",lead:"D-HUB는 높은 경기 강도를 원하는 선수를 위한 별도 선발 프로그램입니다. RBA 회원이라고 참가가 보장되지 않습니다.",items:[["SELECTION","선발","프로그램별 조건과 평가 방법을 공개합니다."],["INTENSIFICATION","강화","준비도, 회복과 장기 건강을 반영합니다."],["COMPETITION","경쟁","대회, 역할, 비용과 조건을 사전에 설명합니다."]],boundary:"RBA와 명확히 분리",boundaryBody:"RBA는 보급, 육성과 교육의 전국 플랫폼입니다. D-HUB는 선발된 경쟁 지향 선수를 위한 별도 사업이며 브랜드, 신청, 선발과 비용을 분리합니다."}
  });
  return <SiteFrame locale={locale} languagePage="d-hub"><section className="dhub-hero section-pad"><a className="back-link" href={localePath(locale)}>← RBA</a><p className="section-index inverse">D-HUB / SELECTED PERFORMANCE PATHWAY</p><h1>D-HUB</h1><strong>{c.title}</strong><p>{c.lead}</p></section><section className="dhub-grid section-pad">{c.items.map(([tag,title,body])=><article key={tag}><Target/><span>{tag}</span><h2>{title}</h2><p>{body}</p></article>)}</section><section className="dhub-boundary section-pad"><div><p className="section-index">RBA ≠ D-HUB</p><h2>{c.boundary}</h2><p>{c.boundaryBody}</p></div><a className="button button-dark" href={localePath(locale,"contact")}>{locale==="ja"?"D-HUBについて問い合わせる":"Ask about D-HUB"}<ArrowRight size={17}/></a></section></SiteFrame>;
}
