export type WorldYouthCategory="rules"|"competition"|"coach_education"|"talent"|"school"|"girls"|"3x3"|"environment";
export type WorldYouthEntry={
 slug:string;country:string;region:string;organization:string;category:WorldYouthCategory;
 title:string;fact:string;meaning:string;japanQuestion:string;sourceUrl:string;sourceDate:string;verifiedOn:string;articleSlug?:string;
};
export const worldYouthEntries:WorldYouthEntry[]=[
 {slug:"canada-youth-rules-2026",country:"CANADA",region:"Canada",organization:"Canada Basketball",category:"rules",title:"U7〜U14を年齢に合う競技環境として設計",fact:"Youth Rules Guidelinesは用具、ゲーム形式、出場時間、スケジュール、守備戦術を発達段階に合わせて整理する。",meaning:"大人と同じゲームをそのまま小さくするのではなく、試合の形そのものを年齢に合わせて考えている。",japanQuestion:"試合数だけでなく、出場機会や守備のルール、ゲーム形式まで年代に合っているかを見直せているか。",sourceUrl:"https://www.basketball.ca/news/canada-basketball-youth-guidelines-put-development-and-participation-first",sourceDate:"2026-09-17",verifiedOn:"2026-10-01",articleSlug:"world-map-canada-youth-rules-2026"},
 {slug:"ireland-u17-bridge-2026",country:"IRELAND",region:"Ireland",organization:"Basketball Ireland",category:"talent",title:"U16とU18の間にU17 Academyを置く",fact:"2026/27 U17 Academy ProgrammeをU16からU18へのbridgeとして位置づけ、59名を選出した。",meaning:"一度の選考だけで見切らず、身体の成長差が大きい年代を継続して見ていくための仕組みと考えられる。",japanQuestion:"15〜16歳で選抜から外れた選手を、その後もう一度見られる仕組みはあるか。",sourceUrl:"https://ireland.basketball/20260930124350-59-players-selected-to-basketball-ireland-u17-academy-programme",sourceDate:"2026-09-30",verifiedOn:"2026-10-01"},
 {slug:"wales-u13-hubs-2026",country:"WALES",region:"Wales",organization:"Basketball Wales",category:"talent",title:"クラブ外からもU13 Development Hubへ",fact:"School Years 6〜8を対象に地域Hubを設け、学校やJr. NBAなどで最近競技に触れた選手にも入口を開く。",meaning:"早くからクラブに所属できたこと自体が、育成ルートへ入る条件にならないよう入口を広げている。",japanQuestion:"所属チームにかかわらず、これから伸びる選手と出会える入口を地域につくれているか。",sourceUrl:"https://basketball.wales/basketball-wales-u13-development-hubs-2026-27-dates-announced/",sourceDate:"2026-09-06",verifiedOn:"2026-10-01"},
 {slug:"wales-coach-programme-2026",country:"WALES",region:"Wales",organization:"Basketball Wales",category:"coach_education",title:"コーチにも2年間のDevelopment Pathway",fact:"High Performance Coaching Programmeは技術戦術、振り返り、分析、他競技からの学習、個別面談、現場実践を2年間で扱う。",meaning:"資格を取って終わりではなく、実践して振り返り、フィードバックを受けるところまでコーチ育成に含めている。",japanQuestion:"若いコーチが資格を取ったあとも、継続して助言やフィードバックを受けられる場所はあるか。",sourceUrl:"https://basketball.wales/cy/basketball-wales-launches-new-high-performance-coaching-programme/",sourceDate:"2026-09-18",verifiedOn:"2026-10-01"},
 {slug:"netherlands-women-coaches-2026",country:"NETHERLANDS",region:"Netherlands",organization:"Nederlandse Basketball Bond",category:"girls",title:"女性コーチ向けBT3学習環境",fact:"Basketball Trainer 3の女性コーチ向け特別コースを2026年11月から実施する。",meaning:"女子選手を増やすだけでなく、女性コーチが学び続け、上位資格へ進める環境にも目を向けている。",japanQuestion:"U12・U15女子を支える女性コーチが、学び続けられる道筋をつくれているか。",sourceUrl:"https://basketball.nl/2026/09/25/stephanie-janssen-geeft-bt3-speciaal-gericht-op-vrouwelijke-coaches-wij-kunnen-net-zoveel-als-mannen/",sourceDate:"2026-09-25",verifiedOn:"2026-10-01"},
 {slug:"norway-more-than-sport-2026",country:"NORWAY",region:"Norway",organization:"Norges Basketballforbund",category:"school",title:"競技を始める前のアクセスを支える",fact:"Basketball – mer enn en idrettは学校、クラブ、家庭、地域をつなぎ、特に女子の無料活動や3x3の入口を作る。",meaning:"才能を見つける前に、そもそも子どもが体育館へ来られる条件を整えている。",japanQuestion:"部活動の地域展開が進む中で、子どもが最初にバスケットと出会う場を誰がつくるのか。",sourceUrl:"https://www.basket.no/en/om-nbbf/prosjekter/basketball---mer-enn-en-idrett/",sourceDate:"2026-09-01",verifiedOn:"2026-10-01"},
 {slug:"fiba-oceania-3x3-2026",country:"OCEANIA",region:"Oceania",organization:"FIBA Oceania",category:"3x3",title:"3x3で選手・コーチ・審判を同時に育成",fact:"第2回3x3 High Performance Campに女子選手20名、コーチ10名、レフェリー7名が参加した。",meaning:"一つのキャンプを、選手だけでなくコーチや審判が経験を積む場としても使っている。",japanQuestion:"3x3の大会やキャンプを、若い指導者や審判も一緒に学べる場にできないか。",sourceUrl:"https://about.fiba.basketball/en/news/oceanias-3x3-future-strengthened-as-second-high-performance-camp-tips-off",sourceDate:"2026-09-01",verifiedOn:"2026-10-01"},
 {slug:"fiba-americas-youth-bcl-2026",country:"AMERICAS",region:"Americas",organization:"FIBA Americas",category:"competition",title:"U18クラブの国際大会を新設",fact:"初のYouth Basketball Champions League AmericasをU18クラブ4チームで開催した。",meaning:"国際経験を代表活動だけに限らず、クラブの競技機会として組み込もうとしている。",japanQuestion:"海外へ行って終わりにせず、出発前の準備や帰国後の振り返りまで一つの経験としてつなげられるか。",sourceUrl:"https://about.fiba.basketball/en/news/teams-confirmed-for-inaugural-youth-bcl-americas",sourceDate:"2026-09-01",verifiedOn:"2026-10-01"}
];
