export type WorldYouthCategory="rules"|"competition"|"coach_education"|"talent"|"school"|"girls"|"3x3"|"environment";
export type WorldYouthEntry={
 slug:string;country:string;region:string;organization:string;category:WorldYouthCategory;
 title:string;fact:string;meaning:string;japanQuestion:string;sourceUrl:string;sourceDate:string;verifiedOn:string;articleSlug?:string;
};
export const worldYouthEntries:WorldYouthEntry[]=[
 {slug:"canada-youth-rules-2026",country:"CANADA",region:"Canada",organization:"Canada Basketball",category:"rules",title:"U7〜U14を年齢に合う競技環境として設計",fact:"Youth Rules Guidelinesは用具、ゲーム形式、出場時間、スケジュール、守備戦術を発達段階に合わせて整理する。",meaning:"大人の競技規則を小さくするだけでなく、試合そのものを育成環境として扱う。",japanQuestion:"大会数だけでなく、出場機会・守備戦術・ゲーム形式まで年代別に検証できているか。",sourceUrl:"https://www.basketball.ca/news/canada-basketball-youth-guidelines-put-development-and-participation-first",sourceDate:"2026-09-17",verifiedOn:"2026-10-01",articleSlug:"world-map-canada-youth-rules-2026"},
 {slug:"ireland-u17-bridge-2026",country:"IRELAND",region:"Ireland",organization:"Basketball Ireland",category:"talent",title:"U16とU18の間にU17 Academyを置く",fact:"2026/27 U17 Academy ProgrammeをU16からU18へのbridgeとして位置づけ、59名を選出した。",meaning:"一時点の選考だけでPlayer Pathwayとの接点を切らず、成熟差が大きい年代を継続して見る。",japanQuestion:"15〜16歳で選抜から外れた選手を、その後もう一度見る仕組みはあるか。",sourceUrl:"https://ireland.basketball/20260930124350-59-players-selected-to-basketball-ireland-u17-academy-programme",sourceDate:"2026-09-30",verifiedOn:"2026-10-01"},
 {slug:"wales-u13-hubs-2026",country:"WALES",region:"Wales",organization:"Basketball Wales",category:"talent",title:"クラブ外からもU13 Development Hubへ",fact:"School Years 6〜8を対象に地域Hubを設け、学校やJr. NBAなどで最近競技に触れた選手にも入口を開く。",meaning:"早期にクラブへアクセスできたこと自体をTalent Pathwayの条件にしない。",japanQuestion:"所属先ではなく、成長可能性を拾う入口を地域に作れているか。",sourceUrl:"https://basketball.wales/basketball-wales-u13-development-hubs-2026-27-dates-announced/",sourceDate:"2026-09-06",verifiedOn:"2026-10-01"},
 {slug:"wales-coach-programme-2026",country:"WALES",region:"Wales",organization:"Basketball Wales",category:"coach_education",title:"コーチにも2年間のDevelopment Pathway",fact:"High Performance Coaching Programmeは技術戦術、振り返り、分析、他競技からの学習、個別面談、現場実践を2年間で扱う。",meaning:"資格取得だけでなく、実践とフィードバックの反復をコーチ育成に含める。",japanQuestion:"若いコーチが資格取得後に継続的なフィードバックを受ける場所はあるか。",sourceUrl:"https://basketball.wales/cy/basketball-wales-launches-new-high-performance-coaching-programme/",sourceDate:"2026-09-18",verifiedOn:"2026-10-01"},
 {slug:"netherlands-women-coaches-2026",country:"NETHERLANDS",region:"Netherlands",organization:"Nederlandse Basketball Bond",category:"girls",title:"女性コーチ向けBT3学習環境",fact:"Basketball Trainer 3の女性コーチ向け特別コースを2026年11月から実施する。",meaning:"女子育成を選手数だけでなく、女性指導者が上位資格へ進む経路からも支える。",japanQuestion:"女子U12・U15を支える女性コーチが学び続けられる経路を把握できているか。",sourceUrl:"https://basketball.nl/2026/09/25/stephanie-janssen-geeft-bt3-speciaal-gericht-op-vrouwelijke-coaches-wij-kunnen-net-zoveel-als-mannen/",sourceDate:"2026-09-25",verifiedOn:"2026-10-01"},
 {slug:"norway-more-than-sport-2026",country:"NORWAY",region:"Norway",organization:"Norges Basketballforbund",category:"school",title:"競技を始める前のアクセスを支える",fact:"Basketball – mer enn en idrettは学校、クラブ、家庭、地域をつなぎ、特に女子の無料活動や3x3の入口を作る。",meaning:"Talent Identificationより前に、体育館へ来られる条件そのものを整える。",japanQuestion:"部活動の地域展開後、子どもと最初にバスケットをつなぐ役割を誰が担うのか。",sourceUrl:"https://www.basket.no/en/om-nbbf/prosjekter/basketball---mer-enn-en-idrett/",sourceDate:"2026-09-01",verifiedOn:"2026-10-01"},
 {slug:"fiba-oceania-3x3-2026",country:"OCEANIA",region:"Oceania",organization:"FIBA Oceania",category:"3x3",title:"3x3で選手・コーチ・審判を同時に育成",fact:"第2回3x3 High Performance Campに女子選手20名、コーチ10名、レフェリー7名が参加した。",meaning:"一つのイベントを選手育成だけでなく、地域のコーチングとオフィシエーティング能力の向上にも使う。",japanQuestion:"3x3イベントを地域の指導者・審判育成まで含む学習環境にできないか。",sourceUrl:"https://about.fiba.basketball/en/news/oceanias-3x3-future-strengthened-as-second-high-performance-camp-tips-off",sourceDate:"2026-09-01",verifiedOn:"2026-10-01"},
 {slug:"fiba-americas-youth-bcl-2026",country:"AMERICAS",region:"Americas",organization:"FIBA Americas",category:"competition",title:"U18クラブの国際大会を新設",fact:"初のYouth Basketball Champions League AmericasをU18クラブ4チームで開催した。",meaning:"国際経験を代表活動だけに限定せず、クラブ競技構造の中へ組み込む試み。",japanQuestion:"国際交流を単発遠征ではなく、国内での学習と帰国後の振り返りまでつなげられるか。",sourceUrl:"https://about.fiba.basketball/en/news/teams-confirmed-for-inaugural-youth-bcl-americas",sourceDate:"2026-09-01",verifiedOn:"2026-10-01"}
];
