-- Product analytics for the development loop.
-- Aggregation is per authenticated account. No public player ranking is created.

create table if not exists public.development_action_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  action_type text not null check (action_type in ('discover','learn','do','reflect','coach_plan','coach_review')),
  item_type text,
  item_key text,
  occurred_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb
);
create index if not exists development_action_events_user_time_idx on public.development_action_events(user_id,occurred_at desc);
create index if not exists development_action_events_type_time_idx on public.development_action_events(action_type,occurred_at desc);
alter table public.development_action_events enable row level security;
create policy "member reads own development actions" on public.development_action_events for select using (auth.uid()=user_id);
create policy "member inserts own development actions" on public.development_action_events for insert with check (auth.uid()=user_id);

create or replace function public.my_development_activity(days_back integer default 28)
returns table (
  active_days bigint,
  distinct_actions bigint,
  total_actions bigint,
  last_action_at timestamptz
)
language sql
security invoker
set search_path=public
as $$
  select
    count(distinct occurred_at::date),
    count(distinct action_type),
    count(*),
    max(occurred_at)
  from public.development_action_events
  where user_id=auth.uid()
    and occurred_at >= now() - make_interval(days => greatest(1,least(days_back,365)));
$$;

comment on table public.development_action_events is
'Private member development-loop telemetry. Not a player ranking, scouting score, or public performance profile.';
